package com.github.auties00.cobalt.node.mex.json.user;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Fetches the "about" status line of one or more WhatsApp users, along with
 * the associated update history entries.
 *
 * <p>The about status is the short biographical line (for example "At the
 * movies", "Busy") that a user sets in their profile; it is distinct from
 * the ephemeral text status shown on the status tab. This query returns
 * the current text and, when available, the update log used to derive the
 * "last updated" timestamp shown in the profile view.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL query. Manual edits will be overwritten
 * on the next generation run.
 *
 * @implNote WAWebMexFetchAboutStatusJobQuery.graphql: the compiled GraphQL
 * operation is dispatched through {@code WAWebMexClient.fetchQuery}.
 */
@WhatsAppWebModule(moduleName = "WAWebMexFetchAboutStatusJobQuery.graphql")
public sealed interface FetchAboutStatusMex extends MexJsonOperation permits FetchAboutStatusMex.Request, FetchAboutStatusMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexFetchAboutStatusJobQuery} GraphQL operation.
     *
     * @implNote WAWebMexFetchAboutStatusJobQuery.graphql: corresponds to the
     * {@code params.id} field of the compiled query.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexFetchAboutStatusJobQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "24535500086059408";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchAboutStatusMex {
        private final String user;

        public Request(String user) {
            this.user = user;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexFetchAboutStatusJobQuery.graphql: the single
         * {@code user} variable carries the target user JID.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexFetchAboutStatusJobQuery.graphql", exports = "params.id",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (user != null) {
                    writer.writeName("user");
                    writer.writeColon();
                    writer.writeString(user);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchAboutStatusMex {
        private final List<Item> items;

        private Response(List<Item> items) {
            this.items = items;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexFetchAboutStatusJobQuery.graphql: reads the
         * {@code items[].updates[]} array containing about-status entries.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexFetchAboutStatusJobQuery.graphql", exports = "params.id",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the list of items in this response.
         *
         * @return the list of items, empty if absent
         */
        public List<Item> items() {
            return items;
        }

        /**
         * A parsed {@code Item} object.
         */
        public static final class Item {
            private final List<Updates> updates;

            private Item(List<Updates> updates) {
                this.updates = updates;
            }

            /**
             * Returns the {@code updates} field.
             *
             * @return the list of values, empty if absent
             */
            public List<Updates> updates() {
                return updates;
            }

            /**
             * A parsed {@code Updates} object.
             */
            public static final class Updates {
                private final String text;

                private Updates(String text) {
                    this.text = text;
                }

                /**
                 * Returns the {@code text} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> text() {
                    return Optional.ofNullable(text);
                }

                /**
                 * Parses a {@code Updates} from the given JSON object.
                 *
                 * @param obj the JSON object to parse
                 * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                 */
                static Optional<Updates> of(JSONObject obj) {
                    if (obj == null) {
                        return Optional.empty();
                    }

                    var text = obj.getString("text");
                    return Optional.of(new Updates(text));
                }

                /**
                 * Parses a list of {@code Updates} from the given JSON array.
                 *
                 * @param arr the JSON array to parse
                 * @return the list of parsed results, empty if {@code arr} is {@code null}
                 */
                static List<Updates> ofArray(JSONArray arr) {
                    if (arr == null) {
                        return List.of();
                    }

                    var result = new ArrayList<Updates>(arr.size());
                    for (var i = 0; i < arr.size(); i++) {
                        of(arr.getJSONObject(i)).ifPresent(result::add);
                    }
                    return result;
                }
            }

            /**
             * Parses a {@code Item} from the given JSON object.
             *
             * @param obj the JSON object to parse
             * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
             */
            static Optional<Item> of(JSONObject obj) {
                if (obj == null) {
                    return Optional.empty();
                }

                var updates = Updates.ofArray(obj.getJSONArray("updates"));
                return Optional.of(new Item(updates));
            }

            /**
             * Parses a list of {@code Item} from the given JSON array.
             *
             * @param arr the JSON array to parse
             * @return the list of parsed results, empty if {@code arr} is {@code null}
             */
            static List<Item> ofArray(JSONArray arr) {
                if (arr == null) {
                    return List.of();
                }

                var result = new ArrayList<Item>(arr.size());
                for (var i = 0; i < arr.size(); i++) {
                    of(arr.getJSONObject(i)).ifPresent(result::add);
                }
                return result;
            }
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var rootArr = data.getJSONArray("xwa2_users_updates_since");
            var items = Item.ofArray(rootArr);

            return Optional.of(new Response(items));
        }
    }
}
