package com.github.auties00.cobalt.node.mex.json.user;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * Retrieves the most recent linked-identity (LID) change for the
 * authenticated account, returning the previous and current identifier
 * pair.
 *
 * <p>LID is WhatsApp's non-phone account identifier used during the LID
 * migration rollout. When the server rotates an account's LID, clients
 * reconcile local storage by issuing this query to learn the old-to-new
 * mapping so that chat references can be updated without losing history.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL query. Manual edits will be overwritten
 * on the next generation run.
 *
 * @implNote WAWebMexLidChangeNotificationQuery.graphql: the compiled GraphQL
 * operation is dispatched through {@code WAWebMexClient.fetchQuery} and
 * returns the {@code xwa2_notify_lid_change} record.
 */
@WhatsAppWebModule(moduleName = "WAWebMexLidChangeNotificationQuery.graphql")
public sealed interface LidChangeNotificationMex extends MexJsonOperation permits LidChangeNotificationMex.Request, LidChangeNotificationMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexLidChangeNotificationQuery} GraphQL operation.
     *
     * @implNote WAWebMexLidChangeNotificationQuery.graphql: corresponds to
     * the {@code params.id} field of the compiled query.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexLidChangeNotificationQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "9892367127524985";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements LidChangeNotificationMex {

        public Request() {
        }

        /**
         * Serialises an empty GraphQL variables envelope and wraps it in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexLidChangeNotificationQuery.graphql: the compiled
         * Relay artifact declares {@code argumentDefinitions: []} and
         * {@code params.operationKind = "query"}, so the variables envelope is
         * always empty and the IQ is dispatched with {@code type="get"} via
         * {@link MexJsonOperation#createMexNode(String, String)}.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexLidChangeNotificationQuery.graphql", exports = "params",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements LidChangeNotificationMex {
        private final String oldValue;
        private final String newValue;

        private Response(String oldValue, String newValue) {
            this.oldValue = oldValue;
            this.newValue = newValue;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexLidChangeNotificationQuery.graphql: the compiled
         * Relay {@code selections} array selects the {@code XWA2LidChange}
         * linked field {@code xwa2_notify_lid_change} carrying the scalar
         * children {@code old} and {@code new}; this method extracts both
         * straight from the JSON payload of the {@code <result>} child.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexLidChangeNotificationQuery.graphql", exports = "selections",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the previous LID value carried by the GraphQL response.
         *
         * @implNote WAWebMexLidChangeNotificationQuery.graphql: corresponds to
         * the scalar selection {@code selections[0].selections[0].name = "old"}
         * inside the {@code xwa2_notify_lid_change} linked field.
         * @return an {@link Optional} containing the value, or empty if absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexLidChangeNotificationQuery.graphql", exports = "selections",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public Optional<String> oldValue() {
            return Optional.ofNullable(oldValue);
        }

        /**
         * Returns the new LID value carried by the GraphQL response.
         *
         * @implNote WAWebMexLidChangeNotificationQuery.graphql: corresponds to
         * the scalar selection {@code selections[0].selections[1].name = "new"}
         * inside the {@code xwa2_notify_lid_change} linked field. Renamed to
         * {@code newValue()} to avoid clashing with the Java {@code new}
         * keyword.
         * @return an {@link Optional} containing the value, or empty if absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexLidChangeNotificationQuery.graphql", exports = "selections",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public Optional<String> newValue() {
            return Optional.ofNullable(newValue);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_notify_lid_change");
            if (root == null) {
                return Optional.empty();
            }

            var oldValue = root.getString("old");
            var newValue = root.getString("new");

            return Optional.of(new Response(oldValue, newValue));
        }
    }
}
