package com.github.auties00.cobalt.node.mex.json.user;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

/**
 * Checks whether a candidate username is available for registration and
 * returns a list of alternative suggestions when it is not.
 *
 * <p>This is the query that powers the live-validation indicator in the
 * username picker: the response carries a status token (available, taken,
 * invalid, reserved) together with a string of suggested alternatives the
 * client may present to the user.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL query. Manual edits will be overwritten
 * on the next generation run.
 *
 * @implNote WAWebMexUsernameAvailability.mexCheckUsernameAvailabilityQueryJob:
 * sends {@code WAWebMexUsernameAvailabilityQuery} through
 * {@code WAWebMexClient.fetchQuery}.
 */
@WhatsAppWebModule(moduleName = "WAWebMexUsernameAvailability")
@WhatsAppWebModule(moduleName = "WAWebMexUsernameAvailabilityQuery.graphql")
public sealed interface UsernameAvailabilityMex extends MexJsonOperation permits UsernameAvailabilityMex.Request, UsernameAvailabilityMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexUsernameAvailabilityQuery} GraphQL operation.
     *
     * @implNote WAWebMexUsernameAvailabilityQuery.graphql: corresponds to
     * the {@code params.id} field of the compiled query.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexUsernameAvailabilityQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "9615795045169045";

    /**
     * The {@code SUCCESS} sentinel returned by the relay's
     * {@code xwa2_username_check.result} field when the candidate username is
     * available for registration.
     *
     * @implNote WAWebMexUsernameAvailability.mexCheckUsernameAvailabilityQueryJob:
     * mirrors the {@code result === "SUCCESS"} comparison used by the JS job
     * to derive {@code isUsernameAvailable}.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexUsernameAvailability", exports = "mexCheckUsernameAvailabilityQueryJob",
            adaptation = WhatsAppAdaptation.DIRECT)
    String RESULT_SUCCESS = "SUCCESS";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements UsernameAvailabilityMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexUsernameAvailability.mexCheckUsernameAvailabilityQueryJob:
         * the single {@code input} variable carries the candidate username.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexUsernameAvailability", exports = "mexCheckUsernameAvailabilityQueryJob",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (input != null) {
                    writer.writeName("input");
                    writer.writeColon();
                    writer.writeString(input);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     *
     * <p>The fields mirror the {@code XWA2UsernameCheckResponse} GraphQL type
     * selected by {@code WAWebMexUsernameAvailabilityQuery.graphql}: a
     * {@code result} status string and a list of suggested alternative
     * usernames.
     */
    final class Response implements UsernameAvailabilityMex {
        private final String result;
        private final List<String> suggestedUsernames;

        private Response(String result, List<String> suggestedUsernames) {
            this.result = result;
            this.suggestedUsernames = suggestedUsernames;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexUsernameAvailability.mexCheckUsernameAvailabilityQueryJob:
         * reads the {@code result} and {@code suggestions} fields from
         * {@code data.xwa2_username_check}.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexUsernameAvailability", exports = "mexCheckUsernameAvailabilityQueryJob",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the raw {@code result} status token reported by the relay.
         *
         * <p>Known values include {@code "SUCCESS"} (the username is available
         * for registration) along with implementation-defined error tokens
         * surfaced by the WhatsApp backend when the candidate is rejected.
         *
         * @return an {@link Optional} containing the status token, or empty if
         *         absent
         */
        public Optional<String> result() {
            return Optional.ofNullable(result);
        }

        /**
         * Returns the list of alternative usernames suggested by the relay
         * when the candidate is not available.
         *
         * <p>The list is unmodifiable and never {@code null}; an empty list is
         * returned when the relay does not include any suggestions.
         *
         * @implNote WAWebMexUsernameAvailability.mexCheckUsernameAvailabilityQueryJob:
         * {@code u.push.apply(u, c.suggestions)} flattens the
         * {@code suggestions} array into the {@code suggestedUsernames}
         * field returned to callers.
         * @return the unmodifiable list of suggested usernames
         */
        @WhatsAppWebExport(moduleName = "WAWebMexUsernameAvailability", exports = "mexCheckUsernameAvailabilityQueryJob",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public List<String> suggestedUsernames() {
            return suggestedUsernames;
        }

        /**
         * Returns whether the queried username is available for registration.
         *
         * @implNote WAWebMexUsernameAvailability.mexCheckUsernameAvailabilityQueryJob:
         * mirrors {@code isUsernameAvailable: result === "SUCCESS"} from the
         * JS job's return shape.
         * @return {@code true} if {@link #result()} equals {@link #RESULT_SUCCESS}
         */
        @WhatsAppWebExport(moduleName = "WAWebMexUsernameAvailability", exports = "mexCheckUsernameAvailabilityQueryJob",
                adaptation = WhatsAppAdaptation.DIRECT)
        public boolean isUsernameAvailable() {
            return RESULT_SUCCESS.equals(result);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            // WAWebMexUsernameAvailability.mexCheckUsernameAvailabilityQueryJob
            // The fetchQuery wrapper unwraps the GraphQL `data` envelope before returning.
            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            // WAWebMexUsernameAvailability.mexCheckUsernameAvailabilityQueryJob: s.xwa2_username_check
            var root = data.getJSONObject("xwa2_username_check");
            if (root == null) {
                return Optional.empty();
            }

            // WAWebMexUsernameAvailability.mexCheckUsernameAvailabilityQueryJob: r.result
            var result = root.getString("result");

            // WAWebMexUsernameAvailability.mexCheckUsernameAvailabilityQueryJob:
            // u.push.apply(u, c.suggestions) -- spread `suggestions` array into the result list.
            var suggestionsArray = root.getJSONArray("suggestions");
            List<String> suggestedUsernames;
            if (suggestionsArray == null) {
                suggestedUsernames = List.of();
            } else {
                var collected = new ArrayList<String>(suggestionsArray.size());
                for (var i = 0; i < suggestionsArray.size(); i++) {
                    var entry = suggestionsArray.getString(i);
                    if (entry != null) {
                        collected.add(entry);
                    }
                }
                suggestedUsernames = Collections.unmodifiableList(collected);
            }

            return Optional.of(new Response(result, suggestedUsernames));
        }
    }
}
