package com.github.auties00.cobalt.model.bot.session;

import com.github.auties00.cobalt.model.jid.Jid;

import it.auties.protobuf.annotation.*;
import it.auties.protobuf.model.*;
import java.util.Optional;

/**
 * Attribution information attached to a forwarded AI bot message on WhatsApp.
 *
 * <p>When a user forwards a message that was originally generated by an AI
 * bot, this metadata is included in the message's context info (field 56 in
 * the {@code ContextInfo} protobuf) so the recipient can see which bot
 * generated the content and who created it. The client uses this information
 * to render a forward-attribution label, for example "Generated by Meta AI,
 * created by John".
 */
@ProtobufMessage(name = "ForwardedAIBotMessageInfo")
public final class ForwardedAIBotMessageInfo {
    /**
     * The display name of the bot that generated the message, for example
     * {@code "Meta AI"} or {@code "My Custom Bot"}.
     */
    @ProtobufProperty(index = 1, type = ProtobufType.STRING)
    String botName;

    /**
     * The JID (Jabber ID) of the bot that generated the message.
     */
    @ProtobufProperty(index = 2, type = ProtobufType.STRING)
    Jid botJid;

    /**
     * The display name of the user who created the bot (for AI Studio
     * user-generated bots), for example {@code "John Doe"}.
     */
    @ProtobufProperty(index = 3, type = ProtobufType.STRING)
    String creatorName;


    /**
     * Constructs a new {@code ForwardedAIBotMessageInfo} with the specified
     * values.
     *
     * @param botName     the bot display name, or {@code null}
     * @param botJid      the bot JID, or {@code null}
     * @param creatorName the bot creator's display name, or {@code null}
     */
    ForwardedAIBotMessageInfo(String botName, Jid botJid, String creatorName) {
        this.botName = botName;
        this.botJid = botJid;
        this.creatorName = creatorName;
    }

    /**
     * Returns the display name of the bot that generated the message.
     *
     * @return an {@code Optional} describing the bot name, or an empty
     *         {@code Optional} if not set
     */
    public Optional<String> botName() {
        return Optional.ofNullable(botName);
    }

    /**
     * Returns the JID of the bot that generated the message.
     *
     * @return an {@code Optional} describing the bot JID, or an empty
     *         {@code Optional} if not set
     */
    public Optional<Jid> botJid() {
        return Optional.ofNullable(botJid);
    }

    /**
     * Returns the display name of the user who created the bot.
     *
     * @return an {@code Optional} describing the creator name, or an empty
     *         {@code Optional} if not set
     */
    public Optional<String> creatorName() {
        return Optional.ofNullable(creatorName);
    }

    /**
     * Sets the display name of the bot that generated the message.
     *
     * @param botName the new bot name, or {@code null}
     */
    public void setBotName(String botName) {
        this.botName = botName;
    }

    /**
     * Sets the JID of the bot that generated the message.
     *
     * @param botJid the new bot JID, or {@code null}
     */
    public void setBotJid(Jid botJid) {
        this.botJid = botJid;
    }

    /**
     * Sets the display name of the user who created the bot.
     *
     * @param creatorName the new creator name, or {@code null}
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }
}
