// Generated by jextract

package com.github.auties00.cobalt.store.persistent.mdbx.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct iovec {
 *     void *iov_base;
 *     size_t iov_len;
 * } MDBX_val
 * }
 */
public class MDBX_val extends iovec {

    MDBX_val() {
        // Should not be called directly
    }
}

