// Generated by jextract

package com.github.auties00.cobalt.call.video.h264.bindings;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _tagVersion {
 *     unsigned int uMajor;
 *     unsigned int uMinor;
 *     unsigned int uRevision;
 *     unsigned int uReserved;
 * }
 * }
 */
public class _tagVersion {

    _tagVersion() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        OpenH264.C_INT.withName("uMajor"),
        OpenH264.C_INT.withName("uMinor"),
        OpenH264.C_INT.withName("uRevision"),
        OpenH264.C_INT.withName("uReserved")
    ).withName("_tagVersion");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt uMajor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("uMajor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int uMajor
     * }
     */
    public static final OfInt uMajor$layout() {
        return uMajor$LAYOUT;
    }

    private static final long uMajor$OFFSET = $LAYOUT.byteOffset(groupElement("uMajor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int uMajor
     * }
     */
    public static final long uMajor$offset() {
        return uMajor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int uMajor
     * }
     */
    public static int uMajor(MemorySegment struct) {
        return struct.get(uMajor$LAYOUT, uMajor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int uMajor
     * }
     */
    public static void uMajor(MemorySegment struct, int fieldValue) {
        struct.set(uMajor$LAYOUT, uMajor$OFFSET, fieldValue);
    }

    private static final OfInt uMinor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("uMinor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int uMinor
     * }
     */
    public static final OfInt uMinor$layout() {
        return uMinor$LAYOUT;
    }

    private static final long uMinor$OFFSET = $LAYOUT.byteOffset(groupElement("uMinor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int uMinor
     * }
     */
    public static final long uMinor$offset() {
        return uMinor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int uMinor
     * }
     */
    public static int uMinor(MemorySegment struct) {
        return struct.get(uMinor$LAYOUT, uMinor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int uMinor
     * }
     */
    public static void uMinor(MemorySegment struct, int fieldValue) {
        struct.set(uMinor$LAYOUT, uMinor$OFFSET, fieldValue);
    }

    private static final OfInt uRevision$LAYOUT = (OfInt)$LAYOUT.select(groupElement("uRevision"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int uRevision
     * }
     */
    public static final OfInt uRevision$layout() {
        return uRevision$LAYOUT;
    }

    private static final long uRevision$OFFSET = $LAYOUT.byteOffset(groupElement("uRevision"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int uRevision
     * }
     */
    public static final long uRevision$offset() {
        return uRevision$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int uRevision
     * }
     */
    public static int uRevision(MemorySegment struct) {
        return struct.get(uRevision$LAYOUT, uRevision$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int uRevision
     * }
     */
    public static void uRevision(MemorySegment struct, int fieldValue) {
        struct.set(uRevision$LAYOUT, uRevision$OFFSET, fieldValue);
    }

    private static final OfInt uReserved$LAYOUT = (OfInt)$LAYOUT.select(groupElement("uReserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int uReserved
     * }
     */
    public static final OfInt uReserved$layout() {
        return uReserved$LAYOUT;
    }

    private static final long uReserved$OFFSET = $LAYOUT.byteOffset(groupElement("uReserved"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int uReserved
     * }
     */
    public static final long uReserved$offset() {
        return uReserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int uReserved
     * }
     */
    public static int uReserved(MemorySegment struct) {
        return struct.get(uReserved$LAYOUT, uReserved$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int uReserved
     * }
     */
    public static void uReserved(MemorySegment struct, int fieldValue) {
        struct.set(uReserved$LAYOUT, uReserved$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

