// Generated by jextract

package com.github.auties00.cobalt.call.video.h264.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ISVCEncoderVtbl {
 *     int (*Initialize)(ISVCEncoder *, const SEncParamBase *);
 *     int (*InitializeExt)(ISVCEncoder *, const SEncParamExt *);
 *     int (*GetDefaultParams)(ISVCEncoder *, SEncParamExt *);
 *     int (*Uninitialize)(ISVCEncoder *);
 *     int (*EncodeFrame)(ISVCEncoder *, const SSourcePicture *, SFrameBSInfo *);
 *     int (*EncodeParameterSets)(ISVCEncoder *, SFrameBSInfo *);
 *     int (*ForceIntraFrame)(ISVCEncoder *, bool);
 *     int (*SetOption)(ISVCEncoder *, ENCODER_OPTION, void *);
 *     int (*GetOption)(ISVCEncoder *, ENCODER_OPTION, void *);
 * }
 * }
 */
public class ISVCEncoderVtbl {

    ISVCEncoderVtbl() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        OpenH264.C_POINTER.withName("Initialize"),
        OpenH264.C_POINTER.withName("InitializeExt"),
        OpenH264.C_POINTER.withName("GetDefaultParams"),
        OpenH264.C_POINTER.withName("Uninitialize"),
        OpenH264.C_POINTER.withName("EncodeFrame"),
        OpenH264.C_POINTER.withName("EncodeParameterSets"),
        OpenH264.C_POINTER.withName("ForceIntraFrame"),
        OpenH264.C_POINTER.withName("SetOption"),
        OpenH264.C_POINTER.withName("GetOption")
    ).withName("ISVCEncoderVtbl");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * int (*Initialize)(ISVCEncoder *, const SEncParamBase *)
     * }
     */
    public final static class Initialize {

        private Initialize() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(Initialize.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Initialize.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Initialize$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Initialize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*Initialize)(ISVCEncoder *, const SEncParamBase *)
     * }
     */
    public static final AddressLayout Initialize$layout() {
        return Initialize$LAYOUT;
    }

    private static final long Initialize$OFFSET = $LAYOUT.byteOffset(groupElement("Initialize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*Initialize)(ISVCEncoder *, const SEncParamBase *)
     * }
     */
    public static final long Initialize$offset() {
        return Initialize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*Initialize)(ISVCEncoder *, const SEncParamBase *)
     * }
     */
    public static MemorySegment Initialize(MemorySegment struct) {
        return struct.get(Initialize$LAYOUT, Initialize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*Initialize)(ISVCEncoder *, const SEncParamBase *)
     * }
     */
    public static void Initialize(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Initialize$LAYOUT, Initialize$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*InitializeExt)(ISVCEncoder *, const SEncParamExt *)
     * }
     */
    public final static class InitializeExt {

        private InitializeExt() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(InitializeExt.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(InitializeExt.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout InitializeExt$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("InitializeExt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*InitializeExt)(ISVCEncoder *, const SEncParamExt *)
     * }
     */
    public static final AddressLayout InitializeExt$layout() {
        return InitializeExt$LAYOUT;
    }

    private static final long InitializeExt$OFFSET = $LAYOUT.byteOffset(groupElement("InitializeExt"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*InitializeExt)(ISVCEncoder *, const SEncParamExt *)
     * }
     */
    public static final long InitializeExt$offset() {
        return InitializeExt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*InitializeExt)(ISVCEncoder *, const SEncParamExt *)
     * }
     */
    public static MemorySegment InitializeExt(MemorySegment struct) {
        return struct.get(InitializeExt$LAYOUT, InitializeExt$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*InitializeExt)(ISVCEncoder *, const SEncParamExt *)
     * }
     */
    public static void InitializeExt(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(InitializeExt$LAYOUT, InitializeExt$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*GetDefaultParams)(ISVCEncoder *, SEncParamExt *)
     * }
     */
    public final static class GetDefaultParams {

        private GetDefaultParams() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(GetDefaultParams.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(GetDefaultParams.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout GetDefaultParams$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("GetDefaultParams"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*GetDefaultParams)(ISVCEncoder *, SEncParamExt *)
     * }
     */
    public static final AddressLayout GetDefaultParams$layout() {
        return GetDefaultParams$LAYOUT;
    }

    private static final long GetDefaultParams$OFFSET = $LAYOUT.byteOffset(groupElement("GetDefaultParams"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*GetDefaultParams)(ISVCEncoder *, SEncParamExt *)
     * }
     */
    public static final long GetDefaultParams$offset() {
        return GetDefaultParams$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*GetDefaultParams)(ISVCEncoder *, SEncParamExt *)
     * }
     */
    public static MemorySegment GetDefaultParams(MemorySegment struct) {
        return struct.get(GetDefaultParams$LAYOUT, GetDefaultParams$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*GetDefaultParams)(ISVCEncoder *, SEncParamExt *)
     * }
     */
    public static void GetDefaultParams(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(GetDefaultParams$LAYOUT, GetDefaultParams$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*Uninitialize)(ISVCEncoder *)
     * }
     */
    public final static class Uninitialize {

        private Uninitialize() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(Uninitialize.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Uninitialize.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Uninitialize$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Uninitialize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*Uninitialize)(ISVCEncoder *)
     * }
     */
    public static final AddressLayout Uninitialize$layout() {
        return Uninitialize$LAYOUT;
    }

    private static final long Uninitialize$OFFSET = $LAYOUT.byteOffset(groupElement("Uninitialize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*Uninitialize)(ISVCEncoder *)
     * }
     */
    public static final long Uninitialize$offset() {
        return Uninitialize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*Uninitialize)(ISVCEncoder *)
     * }
     */
    public static MemorySegment Uninitialize(MemorySegment struct) {
        return struct.get(Uninitialize$LAYOUT, Uninitialize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*Uninitialize)(ISVCEncoder *)
     * }
     */
    public static void Uninitialize(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Uninitialize$LAYOUT, Uninitialize$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*EncodeFrame)(ISVCEncoder *, const SSourcePicture *, SFrameBSInfo *)
     * }
     */
    public final static class EncodeFrame {

        private EncodeFrame() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(EncodeFrame.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(EncodeFrame.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout EncodeFrame$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("EncodeFrame"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*EncodeFrame)(ISVCEncoder *, const SSourcePicture *, SFrameBSInfo *)
     * }
     */
    public static final AddressLayout EncodeFrame$layout() {
        return EncodeFrame$LAYOUT;
    }

    private static final long EncodeFrame$OFFSET = $LAYOUT.byteOffset(groupElement("EncodeFrame"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*EncodeFrame)(ISVCEncoder *, const SSourcePicture *, SFrameBSInfo *)
     * }
     */
    public static final long EncodeFrame$offset() {
        return EncodeFrame$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*EncodeFrame)(ISVCEncoder *, const SSourcePicture *, SFrameBSInfo *)
     * }
     */
    public static MemorySegment EncodeFrame(MemorySegment struct) {
        return struct.get(EncodeFrame$LAYOUT, EncodeFrame$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*EncodeFrame)(ISVCEncoder *, const SSourcePicture *, SFrameBSInfo *)
     * }
     */
    public static void EncodeFrame(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(EncodeFrame$LAYOUT, EncodeFrame$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*EncodeParameterSets)(ISVCEncoder *, SFrameBSInfo *)
     * }
     */
    public final static class EncodeParameterSets {

        private EncodeParameterSets() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(EncodeParameterSets.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(EncodeParameterSets.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout EncodeParameterSets$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("EncodeParameterSets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*EncodeParameterSets)(ISVCEncoder *, SFrameBSInfo *)
     * }
     */
    public static final AddressLayout EncodeParameterSets$layout() {
        return EncodeParameterSets$LAYOUT;
    }

    private static final long EncodeParameterSets$OFFSET = $LAYOUT.byteOffset(groupElement("EncodeParameterSets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*EncodeParameterSets)(ISVCEncoder *, SFrameBSInfo *)
     * }
     */
    public static final long EncodeParameterSets$offset() {
        return EncodeParameterSets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*EncodeParameterSets)(ISVCEncoder *, SFrameBSInfo *)
     * }
     */
    public static MemorySegment EncodeParameterSets(MemorySegment struct) {
        return struct.get(EncodeParameterSets$LAYOUT, EncodeParameterSets$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*EncodeParameterSets)(ISVCEncoder *, SFrameBSInfo *)
     * }
     */
    public static void EncodeParameterSets(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(EncodeParameterSets$LAYOUT, EncodeParameterSets$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*ForceIntraFrame)(ISVCEncoder *, bool)
     * }
     */
    public final static class ForceIntraFrame {

        private ForceIntraFrame() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, boolean _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_BOOL
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(ForceIntraFrame.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ForceIntraFrame.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, boolean _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ForceIntraFrame$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ForceIntraFrame"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*ForceIntraFrame)(ISVCEncoder *, bool)
     * }
     */
    public static final AddressLayout ForceIntraFrame$layout() {
        return ForceIntraFrame$LAYOUT;
    }

    private static final long ForceIntraFrame$OFFSET = $LAYOUT.byteOffset(groupElement("ForceIntraFrame"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*ForceIntraFrame)(ISVCEncoder *, bool)
     * }
     */
    public static final long ForceIntraFrame$offset() {
        return ForceIntraFrame$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*ForceIntraFrame)(ISVCEncoder *, bool)
     * }
     */
    public static MemorySegment ForceIntraFrame(MemorySegment struct) {
        return struct.get(ForceIntraFrame$LAYOUT, ForceIntraFrame$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*ForceIntraFrame)(ISVCEncoder *, bool)
     * }
     */
    public static void ForceIntraFrame(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ForceIntraFrame$LAYOUT, ForceIntraFrame$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*SetOption)(ISVCEncoder *, ENCODER_OPTION, void *)
     * }
     */
    public final static class SetOption {

        private SetOption() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_INT,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(SetOption.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetOption.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetOption$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetOption"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*SetOption)(ISVCEncoder *, ENCODER_OPTION, void *)
     * }
     */
    public static final AddressLayout SetOption$layout() {
        return SetOption$LAYOUT;
    }

    private static final long SetOption$OFFSET = $LAYOUT.byteOffset(groupElement("SetOption"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*SetOption)(ISVCEncoder *, ENCODER_OPTION, void *)
     * }
     */
    public static final long SetOption$offset() {
        return SetOption$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*SetOption)(ISVCEncoder *, ENCODER_OPTION, void *)
     * }
     */
    public static MemorySegment SetOption(MemorySegment struct) {
        return struct.get(SetOption$LAYOUT, SetOption$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*SetOption)(ISVCEncoder *, ENCODER_OPTION, void *)
     * }
     */
    public static void SetOption(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetOption$LAYOUT, SetOption$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*GetOption)(ISVCEncoder *, ENCODER_OPTION, void *)
     * }
     */
    public final static class GetOption {

        private GetOption() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_INT,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(GetOption.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(GetOption.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout GetOption$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("GetOption"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*GetOption)(ISVCEncoder *, ENCODER_OPTION, void *)
     * }
     */
    public static final AddressLayout GetOption$layout() {
        return GetOption$LAYOUT;
    }

    private static final long GetOption$OFFSET = $LAYOUT.byteOffset(groupElement("GetOption"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*GetOption)(ISVCEncoder *, ENCODER_OPTION, void *)
     * }
     */
    public static final long GetOption$offset() {
        return GetOption$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*GetOption)(ISVCEncoder *, ENCODER_OPTION, void *)
     * }
     */
    public static MemorySegment GetOption(MemorySegment struct) {
        return struct.get(GetOption$LAYOUT, GetOption$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*GetOption)(ISVCEncoder *, ENCODER_OPTION, void *)
     * }
     */
    public static void GetOption(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(GetOption$LAYOUT, GetOption$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

