// Generated by jextract

package com.github.auties00.cobalt.call.video.h264.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;

public class OpenH264 extends OpenH264$shared {

    OpenH264() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int videoFormatI420 = (int)23L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.videoFormatI420 = 23
     * }
     */
    public static int videoFormatI420() {
        return videoFormatI420;
    }
    private static final int videoFrameTypeInvalid = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.videoFrameTypeInvalid = 0
     * }
     */
    public static int videoFrameTypeInvalid() {
        return videoFrameTypeInvalid;
    }
    private static final int videoFrameTypeIDR = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.videoFrameTypeIDR = 1
     * }
     */
    public static int videoFrameTypeIDR() {
        return videoFrameTypeIDR;
    }
    private static final int videoFrameTypeI = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.videoFrameTypeI = 2
     * }
     */
    public static int videoFrameTypeI() {
        return videoFrameTypeI;
    }
    private static final int videoFrameTypeP = (int)3L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.videoFrameTypeP = 3
     * }
     */
    public static int videoFrameTypeP() {
        return videoFrameTypeP;
    }
    private static final int videoFrameTypeSkip = (int)4L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.videoFrameTypeSkip = 4
     * }
     */
    public static int videoFrameTypeSkip() {
        return videoFrameTypeSkip;
    }
    private static final int ENCODER_OPTION_BITRATE = (int)5L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.ENCODER_OPTION_BITRATE = 5
     * }
     */
    public static int ENCODER_OPTION_BITRATE() {
        return ENCODER_OPTION_BITRATE;
    }
    private static final int SPATIAL_LAYER_ALL = (int)4L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.SPATIAL_LAYER_ALL = 4
     * }
     */
    public static int SPATIAL_LAYER_ALL() {
        return SPATIAL_LAYER_ALL;
    }
    private static final int RC_QUALITY_MODE = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.RC_QUALITY_MODE = 0
     * }
     */
    public static int RC_QUALITY_MODE() {
        return RC_QUALITY_MODE;
    }
    private static final int RC_BITRATE_MODE = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.RC_BITRATE_MODE = 1
     * }
     */
    public static int RC_BITRATE_MODE() {
        return RC_BITRATE_MODE;
    }
    private static final int RC_BUFFERBASED_MODE = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.RC_BUFFERBASED_MODE = 2
     * }
     */
    public static int RC_BUFFERBASED_MODE() {
        return RC_BUFFERBASED_MODE;
    }
    private static final int RC_TIMESTAMP_MODE = (int)3L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.RC_TIMESTAMP_MODE = 3
     * }
     */
    public static int RC_TIMESTAMP_MODE() {
        return RC_TIMESTAMP_MODE;
    }
    private static final int RC_OFF_MODE = (int)-1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.RC_OFF_MODE = -1
     * }
     */
    public static int RC_OFF_MODE() {
        return RC_OFF_MODE;
    }
    private static final int CAMERA_VIDEO_REAL_TIME = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.CAMERA_VIDEO_REAL_TIME = 0
     * }
     */
    public static int CAMERA_VIDEO_REAL_TIME() {
        return CAMERA_VIDEO_REAL_TIME;
    }
    private static final int SCREEN_CONTENT_REAL_TIME = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.SCREEN_CONTENT_REAL_TIME = 1
     * }
     */
    public static int SCREEN_CONTENT_REAL_TIME() {
        return SCREEN_CONTENT_REAL_TIME;
    }
    private static final int LOW_COMPLEXITY = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.LOW_COMPLEXITY = 0
     * }
     */
    public static int LOW_COMPLEXITY() {
        return LOW_COMPLEXITY;
    }
    private static final int MEDIUM_COMPLEXITY = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.MEDIUM_COMPLEXITY = 1
     * }
     */
    public static int MEDIUM_COMPLEXITY() {
        return MEDIUM_COMPLEXITY;
    }
    private static final int HIGH_COMPLEXITY = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.HIGH_COMPLEXITY = 2
     * }
     */
    public static int HIGH_COMPLEXITY() {
        return HIGH_COMPLEXITY;
    }

    private static class WelsCreateSVCEncoder {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("WelsCreateSVCEncoder");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int WelsCreateSVCEncoder(ISVCEncoder **ppEncoder)
     * }
     */
    public static FunctionDescriptor WelsCreateSVCEncoder$descriptor() {
        return WelsCreateSVCEncoder.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int WelsCreateSVCEncoder(ISVCEncoder **ppEncoder)
     * }
     */
    public static MethodHandle WelsCreateSVCEncoder$handle() {
        return WelsCreateSVCEncoder.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int WelsCreateSVCEncoder(ISVCEncoder **ppEncoder)
     * }
     */
    public static MemorySegment WelsCreateSVCEncoder$address() {
        return WelsCreateSVCEncoder.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int WelsCreateSVCEncoder(ISVCEncoder **ppEncoder)
     * }
     */
    public static int WelsCreateSVCEncoder(MemorySegment ppEncoder) {
        var mh$ = WelsCreateSVCEncoder.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("WelsCreateSVCEncoder", ppEncoder);
            }
            return (int)mh$.invokeExact(ppEncoder);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class WelsDestroySVCEncoder {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            OpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("WelsDestroySVCEncoder");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void WelsDestroySVCEncoder(ISVCEncoder *pEncoder)
     * }
     */
    public static FunctionDescriptor WelsDestroySVCEncoder$descriptor() {
        return WelsDestroySVCEncoder.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void WelsDestroySVCEncoder(ISVCEncoder *pEncoder)
     * }
     */
    public static MethodHandle WelsDestroySVCEncoder$handle() {
        return WelsDestroySVCEncoder.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void WelsDestroySVCEncoder(ISVCEncoder *pEncoder)
     * }
     */
    public static MemorySegment WelsDestroySVCEncoder$address() {
        return WelsDestroySVCEncoder.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void WelsDestroySVCEncoder(ISVCEncoder *pEncoder)
     * }
     */
    public static void WelsDestroySVCEncoder(MemorySegment pEncoder) {
        var mh$ = WelsDestroySVCEncoder.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("WelsDestroySVCEncoder", pEncoder);
            }
            mh$.invokeExact(pEncoder);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class WelsGetDecoderCapability {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("WelsGetDecoderCapability");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int WelsGetDecoderCapability(SDecoderCapability *pDecCapability)
     * }
     */
    public static FunctionDescriptor WelsGetDecoderCapability$descriptor() {
        return WelsGetDecoderCapability.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int WelsGetDecoderCapability(SDecoderCapability *pDecCapability)
     * }
     */
    public static MethodHandle WelsGetDecoderCapability$handle() {
        return WelsGetDecoderCapability.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int WelsGetDecoderCapability(SDecoderCapability *pDecCapability)
     * }
     */
    public static MemorySegment WelsGetDecoderCapability$address() {
        return WelsGetDecoderCapability.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int WelsGetDecoderCapability(SDecoderCapability *pDecCapability)
     * }
     */
    public static int WelsGetDecoderCapability(MemorySegment pDecCapability) {
        var mh$ = WelsGetDecoderCapability.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("WelsGetDecoderCapability", pDecCapability);
            }
            return (int)mh$.invokeExact(pDecCapability);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class WelsCreateDecoder {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            OpenH264.C_LONG,
            OpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("WelsCreateDecoder");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * long WelsCreateDecoder(ISVCDecoder **ppDecoder)
     * }
     */
    public static FunctionDescriptor WelsCreateDecoder$descriptor() {
        return WelsCreateDecoder.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * long WelsCreateDecoder(ISVCDecoder **ppDecoder)
     * }
     */
    public static MethodHandle WelsCreateDecoder$handle() {
        return WelsCreateDecoder.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * long WelsCreateDecoder(ISVCDecoder **ppDecoder)
     * }
     */
    public static MemorySegment WelsCreateDecoder$address() {
        return WelsCreateDecoder.ADDR;
    }

    /**
     * {@snippet lang=c :
     * long WelsCreateDecoder(ISVCDecoder **ppDecoder)
     * }
     */
    public static int WelsCreateDecoder(MemorySegment ppDecoder) {
        var mh$ = WelsCreateDecoder.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("WelsCreateDecoder", ppDecoder);
            }
            return (int)mh$.invokeExact(ppDecoder);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class WelsDestroyDecoder {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            OpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("WelsDestroyDecoder");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void WelsDestroyDecoder(ISVCDecoder *pDecoder)
     * }
     */
    public static FunctionDescriptor WelsDestroyDecoder$descriptor() {
        return WelsDestroyDecoder.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void WelsDestroyDecoder(ISVCDecoder *pDecoder)
     * }
     */
    public static MethodHandle WelsDestroyDecoder$handle() {
        return WelsDestroyDecoder.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void WelsDestroyDecoder(ISVCDecoder *pDecoder)
     * }
     */
    public static MemorySegment WelsDestroyDecoder$address() {
        return WelsDestroyDecoder.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void WelsDestroyDecoder(ISVCDecoder *pDecoder)
     * }
     */
    public static void WelsDestroyDecoder(MemorySegment pDecoder) {
        var mh$ = WelsDestroyDecoder.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("WelsDestroyDecoder", pDecoder);
            }
            mh$.invokeExact(pDecoder);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class WelsGetCodecVersion {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            _tagVersion.layout()    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("WelsGetCodecVersion");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * OpenH264Version WelsGetCodecVersion()
     * }
     */
    public static FunctionDescriptor WelsGetCodecVersion$descriptor() {
        return WelsGetCodecVersion.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * OpenH264Version WelsGetCodecVersion()
     * }
     */
    public static MethodHandle WelsGetCodecVersion$handle() {
        return WelsGetCodecVersion.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * OpenH264Version WelsGetCodecVersion()
     * }
     */
    public static MemorySegment WelsGetCodecVersion$address() {
        return WelsGetCodecVersion.ADDR;
    }

    /**
     * {@snippet lang=c :
     * OpenH264Version WelsGetCodecVersion()
     * }
     */
    public static MemorySegment WelsGetCodecVersion(SegmentAllocator allocator) {
        var mh$ = WelsGetCodecVersion.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("WelsGetCodecVersion", allocator);
            }
            return (MemorySegment)mh$.invokeExact(allocator);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class WelsGetCodecVersionEx {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            OpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("WelsGetCodecVersionEx");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void WelsGetCodecVersionEx(OpenH264Version *pVersion)
     * }
     */
    public static FunctionDescriptor WelsGetCodecVersionEx$descriptor() {
        return WelsGetCodecVersionEx.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void WelsGetCodecVersionEx(OpenH264Version *pVersion)
     * }
     */
    public static MethodHandle WelsGetCodecVersionEx$handle() {
        return WelsGetCodecVersionEx.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void WelsGetCodecVersionEx(OpenH264Version *pVersion)
     * }
     */
    public static MemorySegment WelsGetCodecVersionEx$address() {
        return WelsGetCodecVersionEx.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void WelsGetCodecVersionEx(OpenH264Version *pVersion)
     * }
     */
    public static void WelsGetCodecVersionEx(MemorySegment pVersion) {
        var mh$ = WelsGetCodecVersionEx.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("WelsGetCodecVersionEx", pVersion);
            }
            mh$.invokeExact(pVersion);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

