// Generated by jextract

package com.github.auties00.cobalt.call.video.h264.bindings;

/**
 * {@snippet lang=c :
 * typedef struct TagSVCDecodingParam {
 *     char *pFileNameRestructed;
 *     unsigned int uiCpuLoad;
 *     unsigned char uiTargetDqLayer;
 *     ERROR_CON_IDC eEcActiveIdc;
 *     bool bParseOnly;
 *     SVideoProperty sVideoProperty;
 * } SDecodingParam
 * }
 */
public class SDecodingParam extends TagSVCDecodingParam {

    SDecodingParam() {
        // Should not be called directly
    }
}

