// Generated by jextract

package com.github.auties00.cobalt.call.video.h264.bindings;

/**
 * {@snippet lang=c :
 * typedef struct TagEncParamExt {
 *     EUsageType iUsageType;
 *     int iPicWidth;
 *     int iPicHeight;
 *     int iTargetBitrate;
 *     RC_MODES iRCMode;
 *     float fMaxFrameRate;
 *     int iTemporalLayerNum;
 *     int iSpatialLayerNum;
 *     SSpatialLayerConfig sSpatialLayers[4];
 *     ECOMPLEXITY_MODE iComplexityMode;
 *     unsigned int uiIntraPeriod;
 *     int iNumRefFrame;
 *     EParameterSetStrategy eSpsPpsIdStrategy;
 *     bool bPrefixNalAddingCtrl;
 *     bool bEnableSSEI;
 *     bool bSimulcastAVC;
 *     int iPaddingFlag;
 *     int iEntropyCodingModeFlag;
 *     bool bEnableFrameSkip;
 *     int iMaxBitrate;
 *     int iMaxQp;
 *     int iMinQp;
 *     unsigned int uiMaxNalSize;
 *     bool bEnableLongTermReference;
 *     int iLTRRefNum;
 *     unsigned int iLtrMarkPeriod;
 *     unsigned short iMultipleThreadIdc;
 *     bool bUseLoadBalancing;
 *     int iLoopFilterDisableIdc;
 *     int iLoopFilterAlphaC0Offset;
 *     int iLoopFilterBetaOffset;
 *     bool bEnableDenoise;
 *     bool bEnableBackgroundDetection;
 *     bool bEnableAdaptiveQuant;
 *     bool bEnableFrameCroppingFlag;
 *     bool bEnableSceneChangeDetect;
 *     bool bIsLosslessLink;
 *     bool bFixRCOverShoot;
 *     int iIdrBitrateRatio;
 * } SEncParamExt
 * }
 */
public class SEncParamExt extends TagEncParamExt {

    SEncParamExt() {
        // Should not be called directly
    }
}

