// Generated by jextract

package com.github.auties00.cobalt.call.video.h264.bindings;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     unsigned int uiFeedbackType;
 *     unsigned int uiIDRPicId;
 *     int iLastCorrectFrameNum;
 *     int iCurrentFrameNum;
 *     int iLayerId;
 * }
 * }
 */
public class SLTRRecoverRequest {

    SLTRRecoverRequest() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        OpenH264.C_INT.withName("uiFeedbackType"),
        OpenH264.C_INT.withName("uiIDRPicId"),
        OpenH264.C_INT.withName("iLastCorrectFrameNum"),
        OpenH264.C_INT.withName("iCurrentFrameNum"),
        OpenH264.C_INT.withName("iLayerId")
    ).withName("$anon$239:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt uiFeedbackType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("uiFeedbackType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int uiFeedbackType
     * }
     */
    public static final OfInt uiFeedbackType$layout() {
        return uiFeedbackType$LAYOUT;
    }

    private static final long uiFeedbackType$OFFSET = $LAYOUT.byteOffset(groupElement("uiFeedbackType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int uiFeedbackType
     * }
     */
    public static final long uiFeedbackType$offset() {
        return uiFeedbackType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int uiFeedbackType
     * }
     */
    public static int uiFeedbackType(MemorySegment struct) {
        return struct.get(uiFeedbackType$LAYOUT, uiFeedbackType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int uiFeedbackType
     * }
     */
    public static void uiFeedbackType(MemorySegment struct, int fieldValue) {
        struct.set(uiFeedbackType$LAYOUT, uiFeedbackType$OFFSET, fieldValue);
    }

    private static final OfInt uiIDRPicId$LAYOUT = (OfInt)$LAYOUT.select(groupElement("uiIDRPicId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int uiIDRPicId
     * }
     */
    public static final OfInt uiIDRPicId$layout() {
        return uiIDRPicId$LAYOUT;
    }

    private static final long uiIDRPicId$OFFSET = $LAYOUT.byteOffset(groupElement("uiIDRPicId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int uiIDRPicId
     * }
     */
    public static final long uiIDRPicId$offset() {
        return uiIDRPicId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int uiIDRPicId
     * }
     */
    public static int uiIDRPicId(MemorySegment struct) {
        return struct.get(uiIDRPicId$LAYOUT, uiIDRPicId$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int uiIDRPicId
     * }
     */
    public static void uiIDRPicId(MemorySegment struct, int fieldValue) {
        struct.set(uiIDRPicId$LAYOUT, uiIDRPicId$OFFSET, fieldValue);
    }

    private static final OfInt iLastCorrectFrameNum$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iLastCorrectFrameNum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int iLastCorrectFrameNum
     * }
     */
    public static final OfInt iLastCorrectFrameNum$layout() {
        return iLastCorrectFrameNum$LAYOUT;
    }

    private static final long iLastCorrectFrameNum$OFFSET = $LAYOUT.byteOffset(groupElement("iLastCorrectFrameNum"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int iLastCorrectFrameNum
     * }
     */
    public static final long iLastCorrectFrameNum$offset() {
        return iLastCorrectFrameNum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int iLastCorrectFrameNum
     * }
     */
    public static int iLastCorrectFrameNum(MemorySegment struct) {
        return struct.get(iLastCorrectFrameNum$LAYOUT, iLastCorrectFrameNum$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int iLastCorrectFrameNum
     * }
     */
    public static void iLastCorrectFrameNum(MemorySegment struct, int fieldValue) {
        struct.set(iLastCorrectFrameNum$LAYOUT, iLastCorrectFrameNum$OFFSET, fieldValue);
    }

    private static final OfInt iCurrentFrameNum$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iCurrentFrameNum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int iCurrentFrameNum
     * }
     */
    public static final OfInt iCurrentFrameNum$layout() {
        return iCurrentFrameNum$LAYOUT;
    }

    private static final long iCurrentFrameNum$OFFSET = $LAYOUT.byteOffset(groupElement("iCurrentFrameNum"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int iCurrentFrameNum
     * }
     */
    public static final long iCurrentFrameNum$offset() {
        return iCurrentFrameNum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int iCurrentFrameNum
     * }
     */
    public static int iCurrentFrameNum(MemorySegment struct) {
        return struct.get(iCurrentFrameNum$LAYOUT, iCurrentFrameNum$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int iCurrentFrameNum
     * }
     */
    public static void iCurrentFrameNum(MemorySegment struct, int fieldValue) {
        struct.set(iCurrentFrameNum$LAYOUT, iCurrentFrameNum$OFFSET, fieldValue);
    }

    private static final OfInt iLayerId$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iLayerId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int iLayerId
     * }
     */
    public static final OfInt iLayerId$layout() {
        return iLayerId$LAYOUT;
    }

    private static final long iLayerId$OFFSET = $LAYOUT.byteOffset(groupElement("iLayerId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int iLayerId
     * }
     */
    public static final long iLayerId$offset() {
        return iLayerId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int iLayerId
     * }
     */
    public static int iLayerId(MemorySegment struct) {
        return struct.get(iLayerId$LAYOUT, iLayerId$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int iLayerId
     * }
     */
    public static void iLayerId(MemorySegment struct, int fieldValue) {
        struct.set(iLayerId$LAYOUT, iLayerId$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

