// Generated by jextract

package com.github.auties00.cobalt.call.video.h264.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     SliceModeEnum uiSliceMode;
 *     unsigned int uiSliceNum;
 *     unsigned int uiSliceMbNum[35];
 *     unsigned int uiSliceSizeConstraint;
 * }
 * }
 */
public class SSliceArgument {

    SSliceArgument() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        OpenH264.C_INT.withName("uiSliceMode"),
        OpenH264.C_INT.withName("uiSliceNum"),
        MemoryLayout.sequenceLayout(35, OpenH264.C_INT).withName("uiSliceMbNum"),
        OpenH264.C_INT.withName("uiSliceSizeConstraint")
    ).withName("$anon$348:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt uiSliceMode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("uiSliceMode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SliceModeEnum uiSliceMode
     * }
     */
    public static final OfInt uiSliceMode$layout() {
        return uiSliceMode$LAYOUT;
    }

    private static final long uiSliceMode$OFFSET = $LAYOUT.byteOffset(groupElement("uiSliceMode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SliceModeEnum uiSliceMode
     * }
     */
    public static final long uiSliceMode$offset() {
        return uiSliceMode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SliceModeEnum uiSliceMode
     * }
     */
    public static int uiSliceMode(MemorySegment struct) {
        return struct.get(uiSliceMode$LAYOUT, uiSliceMode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SliceModeEnum uiSliceMode
     * }
     */
    public static void uiSliceMode(MemorySegment struct, int fieldValue) {
        struct.set(uiSliceMode$LAYOUT, uiSliceMode$OFFSET, fieldValue);
    }

    private static final OfInt uiSliceNum$LAYOUT = (OfInt)$LAYOUT.select(groupElement("uiSliceNum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int uiSliceNum
     * }
     */
    public static final OfInt uiSliceNum$layout() {
        return uiSliceNum$LAYOUT;
    }

    private static final long uiSliceNum$OFFSET = $LAYOUT.byteOffset(groupElement("uiSliceNum"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int uiSliceNum
     * }
     */
    public static final long uiSliceNum$offset() {
        return uiSliceNum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int uiSliceNum
     * }
     */
    public static int uiSliceNum(MemorySegment struct) {
        return struct.get(uiSliceNum$LAYOUT, uiSliceNum$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int uiSliceNum
     * }
     */
    public static void uiSliceNum(MemorySegment struct, int fieldValue) {
        struct.set(uiSliceNum$LAYOUT, uiSliceNum$OFFSET, fieldValue);
    }

    private static final SequenceLayout uiSliceMbNum$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("uiSliceMbNum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int uiSliceMbNum[35]
     * }
     */
    public static final SequenceLayout uiSliceMbNum$layout() {
        return uiSliceMbNum$LAYOUT;
    }

    private static final long uiSliceMbNum$OFFSET = $LAYOUT.byteOffset(groupElement("uiSliceMbNum"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int uiSliceMbNum[35]
     * }
     */
    public static final long uiSliceMbNum$offset() {
        return uiSliceMbNum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int uiSliceMbNum[35]
     * }
     */
    public static MemorySegment uiSliceMbNum(MemorySegment struct) {
        return struct.asSlice(uiSliceMbNum$OFFSET, uiSliceMbNum$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int uiSliceMbNum[35]
     * }
     */
    public static void uiSliceMbNum(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, uiSliceMbNum$OFFSET, uiSliceMbNum$LAYOUT.byteSize());
    }

    private static long[] uiSliceMbNum$DIMS = { 35 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * unsigned int uiSliceMbNum[35]
     * }
     */
    public static long[] uiSliceMbNum$dimensions() {
        return uiSliceMbNum$DIMS;
    }
    private static final VarHandle uiSliceMbNum$ELEM_HANDLE = uiSliceMbNum$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * unsigned int uiSliceMbNum[35]
     * }
     */
    public static int uiSliceMbNum(MemorySegment struct, long index0) {
        return (int)uiSliceMbNum$ELEM_HANDLE.get(struct, uiSliceMbNum$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * unsigned int uiSliceMbNum[35]
     * }
     */
    public static void uiSliceMbNum(MemorySegment struct, long index0, int fieldValue) {
        uiSliceMbNum$ELEM_HANDLE.set(struct, uiSliceMbNum$OFFSET, index0, fieldValue);
    }

    private static final OfInt uiSliceSizeConstraint$LAYOUT = (OfInt)$LAYOUT.select(groupElement("uiSliceSizeConstraint"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int uiSliceSizeConstraint
     * }
     */
    public static final OfInt uiSliceSizeConstraint$layout() {
        return uiSliceSizeConstraint$LAYOUT;
    }

    private static final long uiSliceSizeConstraint$OFFSET = $LAYOUT.byteOffset(groupElement("uiSliceSizeConstraint"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int uiSliceSizeConstraint
     * }
     */
    public static final long uiSliceSizeConstraint$offset() {
        return uiSliceSizeConstraint$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int uiSliceSizeConstraint
     * }
     */
    public static int uiSliceSizeConstraint(MemorySegment struct) {
        return struct.get(uiSliceSizeConstraint$LAYOUT, uiSliceSizeConstraint$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int uiSliceSizeConstraint
     * }
     */
    public static void uiSliceSizeConstraint(MemorySegment struct, int fieldValue) {
        struct.set(uiSliceSizeConstraint$LAYOUT, uiSliceSizeConstraint$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

