// Generated by jextract

package com.github.auties00.cobalt.call.video.h264.bindings;

/**
 * {@snippet lang=c :
 * typedef struct Source_Picture_s {
 *     int iColorFormat;
 *     int iStride[4];
 *     unsigned char *pData[4];
 *     int iPicWidth;
 *     int iPicHeight;
 *     long long uiTimeStamp;
 * } SSourcePicture
 * }
 */
public class SSourcePicture extends Source_Picture_s {

    SSourcePicture() {
        // Should not be called directly
    }
}

