// Generated by jextract

package com.github.auties00.cobalt.call.video.h264.bindings;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TagBitrateInfo {
 *     LAYER_NUM iLayer;
 *     int iBitrate;
 * }
 * }
 */
public class TagBitrateInfo {

    TagBitrateInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        OpenH264.C_INT.withName("iLayer"),
        OpenH264.C_INT.withName("iBitrate")
    ).withName("TagBitrateInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt iLayer$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iLayer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * LAYER_NUM iLayer
     * }
     */
    public static final OfInt iLayer$layout() {
        return iLayer$LAYOUT;
    }

    private static final long iLayer$OFFSET = $LAYOUT.byteOffset(groupElement("iLayer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * LAYER_NUM iLayer
     * }
     */
    public static final long iLayer$offset() {
        return iLayer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * LAYER_NUM iLayer
     * }
     */
    public static int iLayer(MemorySegment struct) {
        return struct.get(iLayer$LAYOUT, iLayer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * LAYER_NUM iLayer
     * }
     */
    public static void iLayer(MemorySegment struct, int fieldValue) {
        struct.set(iLayer$LAYOUT, iLayer$OFFSET, fieldValue);
    }

    private static final OfInt iBitrate$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iBitrate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int iBitrate
     * }
     */
    public static final OfInt iBitrate$layout() {
        return iBitrate$LAYOUT;
    }

    private static final long iBitrate$OFFSET = $LAYOUT.byteOffset(groupElement("iBitrate"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int iBitrate
     * }
     */
    public static final long iBitrate$offset() {
        return iBitrate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int iBitrate
     * }
     */
    public static int iBitrate(MemorySegment struct) {
        return struct.get(iBitrate$LAYOUT, iBitrate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int iBitrate
     * }
     */
    public static void iBitrate(MemorySegment struct, int fieldValue) {
        struct.set(iBitrate$LAYOUT, iBitrate$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

