// Generated by jextract

package com.github.auties00.cobalt.call.video.h264.bindings;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TagParserBsInfo {
 *     int iNalNum;
 *     int *pNalLenInByte;
 *     unsigned char *pDstBuff;
 *     int iSpsWidthInPixel;
 *     int iSpsHeightInPixel;
 *     unsigned long long uiInBsTimeStamp;
 *     unsigned long long uiOutBsTimeStamp;
 * }
 * }
 */
public class TagParserBsInfo {

    TagParserBsInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        OpenH264.C_INT.withName("iNalNum"),
        MemoryLayout.paddingLayout(4),
        OpenH264.C_POINTER.withName("pNalLenInByte"),
        OpenH264.C_POINTER.withName("pDstBuff"),
        OpenH264.C_INT.withName("iSpsWidthInPixel"),
        OpenH264.C_INT.withName("iSpsHeightInPixel"),
        OpenH264.C_LONG_LONG.withName("uiInBsTimeStamp"),
        OpenH264.C_LONG_LONG.withName("uiOutBsTimeStamp")
    ).withName("TagParserBsInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt iNalNum$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iNalNum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int iNalNum
     * }
     */
    public static final OfInt iNalNum$layout() {
        return iNalNum$LAYOUT;
    }

    private static final long iNalNum$OFFSET = $LAYOUT.byteOffset(groupElement("iNalNum"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int iNalNum
     * }
     */
    public static final long iNalNum$offset() {
        return iNalNum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int iNalNum
     * }
     */
    public static int iNalNum(MemorySegment struct) {
        return struct.get(iNalNum$LAYOUT, iNalNum$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int iNalNum
     * }
     */
    public static void iNalNum(MemorySegment struct, int fieldValue) {
        struct.set(iNalNum$LAYOUT, iNalNum$OFFSET, fieldValue);
    }

    private static final AddressLayout pNalLenInByte$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pNalLenInByte"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *pNalLenInByte
     * }
     */
    public static final AddressLayout pNalLenInByte$layout() {
        return pNalLenInByte$LAYOUT;
    }

    private static final long pNalLenInByte$OFFSET = $LAYOUT.byteOffset(groupElement("pNalLenInByte"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *pNalLenInByte
     * }
     */
    public static final long pNalLenInByte$offset() {
        return pNalLenInByte$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *pNalLenInByte
     * }
     */
    public static MemorySegment pNalLenInByte(MemorySegment struct) {
        return struct.get(pNalLenInByte$LAYOUT, pNalLenInByte$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *pNalLenInByte
     * }
     */
    public static void pNalLenInByte(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pNalLenInByte$LAYOUT, pNalLenInByte$OFFSET, fieldValue);
    }

    private static final AddressLayout pDstBuff$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pDstBuff"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *pDstBuff
     * }
     */
    public static final AddressLayout pDstBuff$layout() {
        return pDstBuff$LAYOUT;
    }

    private static final long pDstBuff$OFFSET = $LAYOUT.byteOffset(groupElement("pDstBuff"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *pDstBuff
     * }
     */
    public static final long pDstBuff$offset() {
        return pDstBuff$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *pDstBuff
     * }
     */
    public static MemorySegment pDstBuff(MemorySegment struct) {
        return struct.get(pDstBuff$LAYOUT, pDstBuff$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *pDstBuff
     * }
     */
    public static void pDstBuff(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pDstBuff$LAYOUT, pDstBuff$OFFSET, fieldValue);
    }

    private static final OfInt iSpsWidthInPixel$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iSpsWidthInPixel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int iSpsWidthInPixel
     * }
     */
    public static final OfInt iSpsWidthInPixel$layout() {
        return iSpsWidthInPixel$LAYOUT;
    }

    private static final long iSpsWidthInPixel$OFFSET = $LAYOUT.byteOffset(groupElement("iSpsWidthInPixel"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int iSpsWidthInPixel
     * }
     */
    public static final long iSpsWidthInPixel$offset() {
        return iSpsWidthInPixel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int iSpsWidthInPixel
     * }
     */
    public static int iSpsWidthInPixel(MemorySegment struct) {
        return struct.get(iSpsWidthInPixel$LAYOUT, iSpsWidthInPixel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int iSpsWidthInPixel
     * }
     */
    public static void iSpsWidthInPixel(MemorySegment struct, int fieldValue) {
        struct.set(iSpsWidthInPixel$LAYOUT, iSpsWidthInPixel$OFFSET, fieldValue);
    }

    private static final OfInt iSpsHeightInPixel$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iSpsHeightInPixel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int iSpsHeightInPixel
     * }
     */
    public static final OfInt iSpsHeightInPixel$layout() {
        return iSpsHeightInPixel$LAYOUT;
    }

    private static final long iSpsHeightInPixel$OFFSET = $LAYOUT.byteOffset(groupElement("iSpsHeightInPixel"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int iSpsHeightInPixel
     * }
     */
    public static final long iSpsHeightInPixel$offset() {
        return iSpsHeightInPixel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int iSpsHeightInPixel
     * }
     */
    public static int iSpsHeightInPixel(MemorySegment struct) {
        return struct.get(iSpsHeightInPixel$LAYOUT, iSpsHeightInPixel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int iSpsHeightInPixel
     * }
     */
    public static void iSpsHeightInPixel(MemorySegment struct, int fieldValue) {
        struct.set(iSpsHeightInPixel$LAYOUT, iSpsHeightInPixel$OFFSET, fieldValue);
    }

    private static final OfLong uiInBsTimeStamp$LAYOUT = (OfLong)$LAYOUT.select(groupElement("uiInBsTimeStamp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long long uiInBsTimeStamp
     * }
     */
    public static final OfLong uiInBsTimeStamp$layout() {
        return uiInBsTimeStamp$LAYOUT;
    }

    private static final long uiInBsTimeStamp$OFFSET = $LAYOUT.byteOffset(groupElement("uiInBsTimeStamp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long long uiInBsTimeStamp
     * }
     */
    public static final long uiInBsTimeStamp$offset() {
        return uiInBsTimeStamp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long long uiInBsTimeStamp
     * }
     */
    public static long uiInBsTimeStamp(MemorySegment struct) {
        return struct.get(uiInBsTimeStamp$LAYOUT, uiInBsTimeStamp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long long uiInBsTimeStamp
     * }
     */
    public static void uiInBsTimeStamp(MemorySegment struct, long fieldValue) {
        struct.set(uiInBsTimeStamp$LAYOUT, uiInBsTimeStamp$OFFSET, fieldValue);
    }

    private static final OfLong uiOutBsTimeStamp$LAYOUT = (OfLong)$LAYOUT.select(groupElement("uiOutBsTimeStamp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long long uiOutBsTimeStamp
     * }
     */
    public static final OfLong uiOutBsTimeStamp$layout() {
        return uiOutBsTimeStamp$LAYOUT;
    }

    private static final long uiOutBsTimeStamp$OFFSET = $LAYOUT.byteOffset(groupElement("uiOutBsTimeStamp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long long uiOutBsTimeStamp
     * }
     */
    public static final long uiOutBsTimeStamp$offset() {
        return uiOutBsTimeStamp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long long uiOutBsTimeStamp
     * }
     */
    public static long uiOutBsTimeStamp(MemorySegment struct) {
        return struct.get(uiOutBsTimeStamp$LAYOUT, uiOutBsTimeStamp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long long uiOutBsTimeStamp
     * }
     */
    public static void uiOutBsTimeStamp(MemorySegment struct, long fieldValue) {
        struct.set(uiOutBsTimeStamp$LAYOUT, uiOutBsTimeStamp$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

