package com.github.auties00.cobalt.device;

import com.github.auties00.cobalt.model.jid.Jid;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Smoke tests for {@link DeviceFixtures}.
 *
 * @apiNote
 * Exercises the four entry points every downstream device test relies on:
 * oracle loading round-trips the JSON-stringified {@code result.value} payload,
 * the {@code self-identity} oracle parses into the bare PN and LID this
 * session captured against, {@link DeviceFixtures#isAvailable} discriminates
 * between committed-corpus topics and topics that have not yet been captured,
 * and {@link DeviceFixtures#temporaryStore} returns a store with the
 * caller-supplied self JID and LID actually set on it.
 *
 * @implNote
 * This implementation uses the {@code self-identity} fixture and the
 * {@code phash-samples} fixture as the canonical test data; both are
 * already-committed corpus files and are not regenerated by these tests.
 */
class DeviceFixturesTest {

    /**
     * Verifies the self-identity oracle parses the expected PN, LID, device
     * JID, and device id.
     */
    @Test
    void selfIdentityOracleParses() {
        var oracle = DeviceFixtures.loadOracle("self-identity");
        assertEquals("19254863482@c.us", oracle.getString("mePn"));
        assertEquals("83116928594056@lid", oracle.getString("meLid"));
        assertEquals("19254863482:1@c.us", oracle.getString("meDevicePn"));
        assertEquals("83116928594056:1@lid", oracle.getString("meDeviceLid"));
        assertEquals(1, oracle.getIntValue("meDeviceId"));
    }

    /**
     * Verifies the phash oracle exposes the four sample shapes downstream KAT
     * tests depend on.
     *
     * @implNote
     * If the corpus is regenerated with a different sample count this test
     * pins the contract that downstream tests rely on.
     */
    @Test
    void phashOracleHasFourSamples() {
        var oracle = DeviceFixtures.loadOracle("phash-samples");
        assertEquals(4, oracle.size());
        for (var key : oracle.keySet()) {
            var sample = oracle.getJSONObject(key);
            assertNotNull(sample.getJSONArray("devices"));
            assertTrue(sample.getString("phashV1").startsWith("1:"));
            assertTrue(sample.getString("phashV2").startsWith("2:"));
        }
    }

    /**
     * Verifies {@link DeviceFixtures#isAvailable} returns false for a topic
     * with only an oracle file (no JSONL stanza dump) and false for a
     * non-existent topic.
     *
     * @implNote
     * The {@code self-identity} corpus only commits the
     * {@code .expected.json} oracle; the JSONL pathway should not report
     * available.
     */
    @Test
    void isAvailableDiscriminates() {
        assertFalse(DeviceFixtures.isAvailable("self-identity"));
        assertFalse(DeviceFixtures.isAvailable("does-not-exist"));
    }

    /**
     * Verifies {@link DeviceFixtures#temporaryStore} returns a store with the
     * caller-supplied self PN and LID set.
     */
    @Test
    void temporaryStoreReflectsCallerJids() {
        var pn = Jid.of("19254863482@s.whatsapp.net");
        var lid = Jid.of("83116928594056@lid");
        var store = DeviceFixtures.temporaryStore(pn, lid);
        assertEquals(pn, store.jid().orElseThrow());
        assertEquals(lid, store.lid().orElseThrow());
    }
}
