package com.github.auties00.cobalt.node.mex.json.group;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.OptionalLong;

/**
 * Fetches full metadata for a group, including bot participants as regular
 * members.
 *
 * <p>This is the bot-aware variant of the standard group info query: the
 * participant edge list returned in the response includes bot accounts
 * alongside human participants. It is used by chat UIs that need to render
 * bots as first-class members (for example showing bot display names,
 * assigned roles and username info).
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL query. Manual edits will be overwritten
 * on the next generation run.
 *
 * @implNote WAWebMexFetchGroupInfoIncludBotsJob.mexGetGroupInfoIncludBots:
 * sends {@code WAWebMexFetchGroupInfoIncludBotsJobQuery} through
 * {@code WAWebMexClient.fetchQuery} and reads
 * {@code xwa2_group_query_by_id} with bot participants included.
 */
@WhatsAppWebModule(moduleName = "WAWebMexFetchGroupInfoIncludBotsJob")
@WhatsAppWebModule(moduleName = "WAWebMexFetchGroupInfoIncludBotsJobQuery.graphql")
public sealed interface FetchGroupInfoIncludBotsMex extends MexJsonOperation permits FetchGroupInfoIncludBotsMex.Request, FetchGroupInfoIncludBotsMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexFetchGroupInfoIncludBotsJobQuery} GraphQL operation.
     *
     * @implNote WAWebMexFetchGroupInfoIncludBotsJobQuery.graphql: corresponds
     * to the {@code params.id} field of the compiled query.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexFetchGroupInfoIncludBotsJobQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "26342357488707090";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchGroupInfoIncludBotsMex {
        private final String id;
        private final Boolean includeUsername;
        private final String participantsPhash;
        private final String queryContext;

        public Request(String id, Boolean includeUsername, String participantsPhash, String queryContext) {
            this.id = id;
            this.includeUsername = includeUsername;
            this.participantsPhash = participantsPhash;
            this.queryContext = queryContext;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexFetchGroupInfoIncludBotsJob.mexGetGroupInfoIncludBots:
         * the variables mirror the WA Web call with {@code id},
         * {@code include_username}, {@code participants_phash} (for
         * incremental updates) and {@code query_context}.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexFetchGroupInfoIncludBotsJob", exports = "mexGetGroupInfoIncludBots",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (id != null) {
                    writer.writeName("id");
                    writer.writeColon();
                    writer.writeString(id);
                }
                if (includeUsername != null) {
                    writer.writeName("include_username");
                    writer.writeColon();
                    writer.writeBool(includeUsername);
                }
                if (participantsPhash != null) {
                    writer.writeName("participants_phash");
                    writer.writeColon();
                    writer.writeString(participantsPhash);
                }
                if (queryContext != null) {
                    writer.writeName("query_context");
                    writer.writeColon();
                    writer.writeString(queryContext);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchGroupInfoIncludBotsMex {
        private final String id;
        private final Long creationTime;
        private final Creator creator;
        private final String state;
        private final Subject subject;
        private final Description description;
        private final Participants participants;
        private final Long totalParticipantsCount;
        private final String missingParticipantIdentification;
        private final Properties properties;
        private final String membershipApprovalRequest;

        private Response(String id, Long creationTime, Creator creator, String state, Subject subject, Description description, Participants participants, Long totalParticipantsCount, String missingParticipantIdentification, Properties properties, String membershipApprovalRequest) {
            this.id = id;
            this.creationTime = creationTime;
            this.creator = creator;
            this.state = state;
            this.subject = subject;
            this.description = description;
            this.participants = participants;
            this.totalParticipantsCount = totalParticipantsCount;
            this.missingParticipantIdentification = missingParticipantIdentification;
            this.properties = properties;
            this.membershipApprovalRequest = membershipApprovalRequest;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexFetchGroupInfoIncludBotsJob.mexGetGroupInfoIncludBots:
         * reads the full {@code data.xwa2_group_query_by_id} object including
         * participant edges and group properties.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexFetchGroupInfoIncludBotsJob", exports = "mexGetGroupInfoIncludBots",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> id() {
            return Optional.ofNullable(id);
        }

        /**
         * Returns the {@code creation_time} field.
         *
         * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
         */
        public Optional<Instant> creationTime() {
            return Optional.ofNullable(creationTime).map(Instant::ofEpochSecond);
        }

        /**
         * Returns the {@code creator} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<Creator> creator() {
            return Optional.ofNullable(creator);
        }

        /**
         * Returns the {@code state} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> state() {
            return Optional.ofNullable(state);
        }

        /**
         * Returns the {@code subject} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<Subject> subject() {
            return Optional.ofNullable(subject);
        }

        /**
         * Returns the {@code description} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<Description> description() {
            return Optional.ofNullable(description);
        }

        /**
         * Returns the {@code participants} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<Participants> participants() {
            return Optional.ofNullable(participants);
        }

        /**
         * Returns the {@code total_participants_count} field.
         *
         * @return an {@link OptionalLong} containing the value, or empty if absent
         */
        public OptionalLong totalParticipantsCount() {
            return totalParticipantsCount != null ? OptionalLong.of(totalParticipantsCount) : OptionalLong.empty();
        }

        /**
         * Returns the {@code missing_participant_identification} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> missingParticipantIdentification() {
            return Optional.ofNullable(missingParticipantIdentification);
        }

        /**
         * Returns the {@code properties} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<Properties> properties() {
            return Optional.ofNullable(properties);
        }

        /**
         * Returns the {@code membership_approval_request} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> membershipApprovalRequest() {
            return Optional.ofNullable(membershipApprovalRequest);
        }

        /**
         * A parsed {@code Creator} object.
         */
        public static final class Creator {
            private final String id;
            private final String lid;
            private final String pn;
            private final UsernameInfo usernameInfo;

            private Creator(String id, String lid, String pn, UsernameInfo usernameInfo) {
                this.id = id;
                this.lid = lid;
                this.pn = pn;
                this.usernameInfo = usernameInfo;
            }

            /**
             * Returns the {@code id} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> id() {
                return Optional.ofNullable(id);
            }

            /**
             * Returns the {@code lid} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> lid() {
                return Optional.ofNullable(lid);
            }

            /**
             * Returns the {@code pn} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> pn() {
                return Optional.ofNullable(pn);
            }

            /**
             * Returns the {@code username_info} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<UsernameInfo> usernameInfo() {
                return Optional.ofNullable(usernameInfo);
            }

            /**
             * A parsed {@code UsernameInfo} object.
             */
            public static final class UsernameInfo {
                private final String username;

                private UsernameInfo(String username) {
                    this.username = username;
                }

                /**
                 * Returns the {@code username} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> username() {
                    return Optional.ofNullable(username);
                }

                /**
                 * Parses a {@code UsernameInfo} from the given JSON object.
                 *
                 * @param obj the JSON object to parse
                 * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                 */
                static Optional<UsernameInfo> of(JSONObject obj) {
                    if (obj == null) {
                        return Optional.empty();
                    }

                    var username = obj.getString("username");
                    return Optional.of(new UsernameInfo(username));
                }

                /**
                 * Parses a list of {@code UsernameInfo} from the given JSON array.
                 *
                 * @param arr the JSON array to parse
                 * @return the list of parsed results, empty if {@code arr} is {@code null}
                 */
                static List<UsernameInfo> ofArray(JSONArray arr) {
                    if (arr == null) {
                        return List.of();
                    }

                    var result = new ArrayList<UsernameInfo>(arr.size());
                    for (var i = 0; i < arr.size(); i++) {
                        of(arr.getJSONObject(i)).ifPresent(result::add);
                    }
                    return result;
                }
            }

            /**
             * Parses a {@code Creator} from the given JSON object.
             *
             * @param obj the JSON object to parse
             * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
             */
            static Optional<Creator> of(JSONObject obj) {
                if (obj == null) {
                    return Optional.empty();
                }

                var id = obj.getString("id");
                var lid = obj.getString("lid");
                var pn = obj.getString("pn");
                var usernameInfo = UsernameInfo.of(obj.getJSONObject("username_info")).orElse(null);
                return Optional.of(new Creator(id, lid, pn, usernameInfo));
            }

            /**
             * Parses a list of {@code Creator} from the given JSON array.
             *
             * @param arr the JSON array to parse
             * @return the list of parsed results, empty if {@code arr} is {@code null}
             */
            static List<Creator> ofArray(JSONArray arr) {
                if (arr == null) {
                    return List.of();
                }

                var result = new ArrayList<Creator>(arr.size());
                for (var i = 0; i < arr.size(); i++) {
                    of(arr.getJSONObject(i)).ifPresent(result::add);
                }
                return result;
            }
        }

        /**
         * A parsed {@code Subject} object.
         */
        public static final class Subject {
            private final Creator creator;
            private final Long creationTime;
            private final String value;

            private Subject(Creator creator, Long creationTime, String value) {
                this.creator = creator;
                this.creationTime = creationTime;
                this.value = value;
            }

            /**
             * Returns the {@code creator} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<Creator> creator() {
                return Optional.ofNullable(creator);
            }

            /**
             * Returns the {@code creation_time} field.
             *
             * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
             */
            public Optional<Instant> creationTime() {
                return Optional.ofNullable(creationTime).map(Instant::ofEpochSecond);
            }

            /**
             * Returns the {@code value} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> value() {
                return Optional.ofNullable(value);
            }

            /**
             * A parsed {@code Creator} object.
             */
            public static final class Creator {
                private final String id;
                private final String lid;
                private final String pn;
                private final UsernameInfo usernameInfo;

                private Creator(String id, String lid, String pn, UsernameInfo usernameInfo) {
                    this.id = id;
                    this.lid = lid;
                    this.pn = pn;
                    this.usernameInfo = usernameInfo;
                }

                /**
                 * Returns the {@code id} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> id() {
                    return Optional.ofNullable(id);
                }

                /**
                 * Returns the {@code lid} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> lid() {
                    return Optional.ofNullable(lid);
                }

                /**
                 * Returns the {@code pn} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> pn() {
                    return Optional.ofNullable(pn);
                }

                /**
                 * Returns the {@code username_info} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<UsernameInfo> usernameInfo() {
                    return Optional.ofNullable(usernameInfo);
                }

                /**
                 * A parsed {@code UsernameInfo} object.
                 */
                public static final class UsernameInfo {
                    private final String username;

                    private UsernameInfo(String username) {
                        this.username = username;
                    }

                    /**
                     * Returns the {@code username} field.
                     *
                     * @return an {@link Optional} containing the value, or empty if absent
                     */
                    public Optional<String> username() {
                        return Optional.ofNullable(username);
                    }

                    /**
                     * Parses a {@code UsernameInfo} from the given JSON object.
                     *
                     * @param obj the JSON object to parse
                     * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                     */
                    static Optional<UsernameInfo> of(JSONObject obj) {
                        if (obj == null) {
                            return Optional.empty();
                        }

                        var username = obj.getString("username");
                        return Optional.of(new UsernameInfo(username));
                    }

                    /**
                     * Parses a list of {@code UsernameInfo} from the given JSON array.
                     *
                     * @param arr the JSON array to parse
                     * @return the list of parsed results, empty if {@code arr} is {@code null}
                     */
                    static List<UsernameInfo> ofArray(JSONArray arr) {
                        if (arr == null) {
                            return List.of();
                        }

                        var result = new ArrayList<UsernameInfo>(arr.size());
                        for (var i = 0; i < arr.size(); i++) {
                            of(arr.getJSONObject(i)).ifPresent(result::add);
                        }
                        return result;
                    }
                }

                /**
                 * Parses a {@code Creator} from the given JSON object.
                 *
                 * @param obj the JSON object to parse
                 * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                 */
                static Optional<Creator> of(JSONObject obj) {
                    if (obj == null) {
                        return Optional.empty();
                    }

                    var id = obj.getString("id");
                    var lid = obj.getString("lid");
                    var pn = obj.getString("pn");
                    var usernameInfo = UsernameInfo.of(obj.getJSONObject("username_info")).orElse(null);
                    return Optional.of(new Creator(id, lid, pn, usernameInfo));
                }

                /**
                 * Parses a list of {@code Creator} from the given JSON array.
                 *
                 * @param arr the JSON array to parse
                 * @return the list of parsed results, empty if {@code arr} is {@code null}
                 */
                static List<Creator> ofArray(JSONArray arr) {
                    if (arr == null) {
                        return List.of();
                    }

                    var result = new ArrayList<Creator>(arr.size());
                    for (var i = 0; i < arr.size(); i++) {
                        of(arr.getJSONObject(i)).ifPresent(result::add);
                    }
                    return result;
                }
            }

            /**
             * Parses a {@code Subject} from the given JSON object.
             *
             * @param obj the JSON object to parse
             * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
             */
            static Optional<Subject> of(JSONObject obj) {
                if (obj == null) {
                    return Optional.empty();
                }

                var creator = Creator.of(obj.getJSONObject("creator")).orElse(null);
                var creationTime = obj.getLong("creation_time");
                var value = obj.getString("value");
                return Optional.of(new Subject(creator, creationTime, value));
            }

            /**
             * Parses a list of {@code Subject} from the given JSON array.
             *
             * @param arr the JSON array to parse
             * @return the list of parsed results, empty if {@code arr} is {@code null}
             */
            static List<Subject> ofArray(JSONArray arr) {
                if (arr == null) {
                    return List.of();
                }

                var result = new ArrayList<Subject>(arr.size());
                for (var i = 0; i < arr.size(); i++) {
                    of(arr.getJSONObject(i)).ifPresent(result::add);
                }
                return result;
            }
        }

        /**
         * A parsed {@code Description} object.
         */
        public static final class Description {
            private final String id;
            private final Long creationTime;
            private final Creator creator;
            private final String value;

            private Description(String id, Long creationTime, Creator creator, String value) {
                this.id = id;
                this.creationTime = creationTime;
                this.creator = creator;
                this.value = value;
            }

            /**
             * Returns the {@code id} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> id() {
                return Optional.ofNullable(id);
            }

            /**
             * Returns the {@code creation_time} field.
             *
             * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
             */
            public Optional<Instant> creationTime() {
                return Optional.ofNullable(creationTime).map(Instant::ofEpochSecond);
            }

            /**
             * Returns the {@code creator} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<Creator> creator() {
                return Optional.ofNullable(creator);
            }

            /**
             * Returns the {@code value} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> value() {
                return Optional.ofNullable(value);
            }

            /**
             * A parsed {@code Creator} object.
             */
            public static final class Creator {
                private final String id;
                private final String lid;
                private final String pn;
                private final UsernameInfo usernameInfo;

                private Creator(String id, String lid, String pn, UsernameInfo usernameInfo) {
                    this.id = id;
                    this.lid = lid;
                    this.pn = pn;
                    this.usernameInfo = usernameInfo;
                }

                /**
                 * Returns the {@code id} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> id() {
                    return Optional.ofNullable(id);
                }

                /**
                 * Returns the {@code lid} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> lid() {
                    return Optional.ofNullable(lid);
                }

                /**
                 * Returns the {@code pn} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> pn() {
                    return Optional.ofNullable(pn);
                }

                /**
                 * Returns the {@code username_info} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<UsernameInfo> usernameInfo() {
                    return Optional.ofNullable(usernameInfo);
                }

                /**
                 * A parsed {@code UsernameInfo} object.
                 */
                public static final class UsernameInfo {
                    private final String username;

                    private UsernameInfo(String username) {
                        this.username = username;
                    }

                    /**
                     * Returns the {@code username} field.
                     *
                     * @return an {@link Optional} containing the value, or empty if absent
                     */
                    public Optional<String> username() {
                        return Optional.ofNullable(username);
                    }

                    /**
                     * Parses a {@code UsernameInfo} from the given JSON object.
                     *
                     * @param obj the JSON object to parse
                     * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                     */
                    static Optional<UsernameInfo> of(JSONObject obj) {
                        if (obj == null) {
                            return Optional.empty();
                        }

                        var username = obj.getString("username");
                        return Optional.of(new UsernameInfo(username));
                    }

                    /**
                     * Parses a list of {@code UsernameInfo} from the given JSON array.
                     *
                     * @param arr the JSON array to parse
                     * @return the list of parsed results, empty if {@code arr} is {@code null}
                     */
                    static List<UsernameInfo> ofArray(JSONArray arr) {
                        if (arr == null) {
                            return List.of();
                        }

                        var result = new ArrayList<UsernameInfo>(arr.size());
                        for (var i = 0; i < arr.size(); i++) {
                            of(arr.getJSONObject(i)).ifPresent(result::add);
                        }
                        return result;
                    }
                }

                /**
                 * Parses a {@code Creator} from the given JSON object.
                 *
                 * @param obj the JSON object to parse
                 * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                 */
                static Optional<Creator> of(JSONObject obj) {
                    if (obj == null) {
                        return Optional.empty();
                    }

                    var id = obj.getString("id");
                    var lid = obj.getString("lid");
                    var pn = obj.getString("pn");
                    var usernameInfo = UsernameInfo.of(obj.getJSONObject("username_info")).orElse(null);
                    return Optional.of(new Creator(id, lid, pn, usernameInfo));
                }

                /**
                 * Parses a list of {@code Creator} from the given JSON array.
                 *
                 * @param arr the JSON array to parse
                 * @return the list of parsed results, empty if {@code arr} is {@code null}
                 */
                static List<Creator> ofArray(JSONArray arr) {
                    if (arr == null) {
                        return List.of();
                    }

                    var result = new ArrayList<Creator>(arr.size());
                    for (var i = 0; i < arr.size(); i++) {
                        of(arr.getJSONObject(i)).ifPresent(result::add);
                    }
                    return result;
                }
            }

            /**
             * Parses a {@code Description} from the given JSON object.
             *
             * @param obj the JSON object to parse
             * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
             */
            static Optional<Description> of(JSONObject obj) {
                if (obj == null) {
                    return Optional.empty();
                }

                var id = obj.getString("id");
                var creationTime = obj.getLong("creation_time");
                var creator = Creator.of(obj.getJSONObject("creator")).orElse(null);
                var value = obj.getString("value");
                return Optional.of(new Description(id, creationTime, creator, value));
            }

            /**
             * Parses a list of {@code Description} from the given JSON array.
             *
             * @param arr the JSON array to parse
             * @return the list of parsed results, empty if {@code arr} is {@code null}
             */
            static List<Description> ofArray(JSONArray arr) {
                if (arr == null) {
                    return List.of();
                }

                var result = new ArrayList<Description>(arr.size());
                for (var i = 0; i < arr.size(); i++) {
                    of(arr.getJSONObject(i)).ifPresent(result::add);
                }
                return result;
            }
        }

        /**
         * A parsed {@code Participants} object.
         */
        public static final class Participants {
            private final List<Edges> edges;
            private final Boolean participantsPhashMatch;

            private Participants(List<Edges> edges, Boolean participantsPhashMatch) {
                this.edges = edges;
                this.participantsPhashMatch = participantsPhashMatch;
            }

            /**
             * Returns the {@code edges} field.
             *
             * @return the list of values, empty if absent
             */
            public List<Edges> edges() {
                return edges;
            }

            /**
             * Returns the {@code participants_phash_match} field.
             *
             * @return {@code true} if the value is present and true, {@code false} otherwise
             */
            public boolean participantsPhashMatch() {
                return participantsPhashMatch != null && participantsPhashMatch;
            }

            /**
             * A parsed {@code Edges} object.
             */
            public static final class Edges {
                private final Participant participant;
                private final String role;

                private Edges(Participant participant, String role) {
                    this.participant = participant;
                    this.role = role;
                }

                /**
                 * Returns the {@code participant} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<Participant> participant() {
                    return Optional.ofNullable(participant);
                }

                /**
                 * Returns the {@code role} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> role() {
                    return Optional.ofNullable(role);
                }

                /**
                 * A parsed {@code Participant} object.
                 */
                public static final class Participant {
                    private final String id;
                    private final String lid;
                    private final String pn;
                    private final String displayName;
                    private final UsernameInfo usernameInfo;
                    private final String jid;

                    private Participant(String id, String lid, String pn, String displayName, UsernameInfo usernameInfo, String jid) {
                        this.id = id;
                        this.lid = lid;
                        this.pn = pn;
                        this.displayName = displayName;
                        this.usernameInfo = usernameInfo;
                        this.jid = jid;
                    }

                    /**
                     * Returns the {@code id} field.
                     *
                     * @return an {@link Optional} containing the value, or empty if absent
                     */
                    public Optional<String> id() {
                        return Optional.ofNullable(id);
                    }

                    /**
                     * Returns the {@code lid} field.
                     *
                     * @return an {@link Optional} containing the value, or empty if absent
                     */
                    public Optional<String> lid() {
                        return Optional.ofNullable(lid);
                    }

                    /**
                     * Returns the {@code pn} field.
                     *
                     * @return an {@link Optional} containing the value, or empty if absent
                     */
                    public Optional<String> pn() {
                        return Optional.ofNullable(pn);
                    }

                    /**
                     * Returns the {@code display_name} field.
                     *
                     * @return an {@link Optional} containing the value, or empty if absent
                     */
                    public Optional<String> displayName() {
                        return Optional.ofNullable(displayName);
                    }

                    /**
                     * Returns the {@code username_info} field.
                     *
                     * @return an {@link Optional} containing the value, or empty if absent
                     */
                    public Optional<UsernameInfo> usernameInfo() {
                        return Optional.ofNullable(usernameInfo);
                    }

                    /**
                     * Returns the {@code jid} field.
                     *
                     * @return an {@link Optional} containing the value, or empty if absent
                     */
                    public Optional<String> jid() {
                        return Optional.ofNullable(jid);
                    }

                    /**
                     * A parsed {@code UsernameInfo} object.
                     */
                    public static final class UsernameInfo {
                        private final String username;

                        private UsernameInfo(String username) {
                            this.username = username;
                        }

                        /**
                         * Returns the {@code username} field.
                         *
                         * @return an {@link Optional} containing the value, or empty if absent
                         */
                        public Optional<String> username() {
                            return Optional.ofNullable(username);
                        }

                        /**
                         * Parses a {@code UsernameInfo} from the given JSON object.
                         *
                         * @param obj the JSON object to parse
                         * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                         */
                        static Optional<UsernameInfo> of(JSONObject obj) {
                            if (obj == null) {
                                return Optional.empty();
                            }

                            var username = obj.getString("username");
                            return Optional.of(new UsernameInfo(username));
                        }

                        /**
                         * Parses a list of {@code UsernameInfo} from the given JSON array.
                         *
                         * @param arr the JSON array to parse
                         * @return the list of parsed results, empty if {@code arr} is {@code null}
                         */
                        static List<UsernameInfo> ofArray(JSONArray arr) {
                            if (arr == null) {
                                return List.of();
                            }

                            var result = new ArrayList<UsernameInfo>(arr.size());
                            for (var i = 0; i < arr.size(); i++) {
                                of(arr.getJSONObject(i)).ifPresent(result::add);
                            }
                            return result;
                        }
                    }

                    /**
                     * Parses a {@code Participant} from the given JSON object.
                     *
                     * @param obj the JSON object to parse
                     * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                     */
                    static Optional<Participant> of(JSONObject obj) {
                        if (obj == null) {
                            return Optional.empty();
                        }

                        var id = obj.getString("id");
                        var lid = obj.getString("lid");
                        var pn = obj.getString("pn");
                        var displayName = obj.getString("display_name");
                        var usernameInfo = UsernameInfo.of(obj.getJSONObject("username_info")).orElse(null);
                        var jid = obj.getString("jid");
                        return Optional.of(new Participant(id, lid, pn, displayName, usernameInfo, jid));
                    }

                    /**
                     * Parses a list of {@code Participant} from the given JSON array.
                     *
                     * @param arr the JSON array to parse
                     * @return the list of parsed results, empty if {@code arr} is {@code null}
                     */
                    static List<Participant> ofArray(JSONArray arr) {
                        if (arr == null) {
                            return List.of();
                        }

                        var result = new ArrayList<Participant>(arr.size());
                        for (var i = 0; i < arr.size(); i++) {
                            of(arr.getJSONObject(i)).ifPresent(result::add);
                        }
                        return result;
                    }
                }

                /**
                 * Parses a {@code Edges} from the given JSON object.
                 *
                 * @param obj the JSON object to parse
                 * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                 */
                static Optional<Edges> of(JSONObject obj) {
                    if (obj == null) {
                        return Optional.empty();
                    }

                    var participant = Participant.of(obj.getJSONObject("participant")).orElse(null);
                    var role = obj.getString("role");
                    return Optional.of(new Edges(participant, role));
                }

                /**
                 * Parses a list of {@code Edges} from the given JSON array.
                 *
                 * @param arr the JSON array to parse
                 * @return the list of parsed results, empty if {@code arr} is {@code null}
                 */
                static List<Edges> ofArray(JSONArray arr) {
                    if (arr == null) {
                        return List.of();
                    }

                    var result = new ArrayList<Edges>(arr.size());
                    for (var i = 0; i < arr.size(); i++) {
                        of(arr.getJSONObject(i)).ifPresent(result::add);
                    }
                    return result;
                }
            }

            /**
             * Parses a {@code Participants} from the given JSON object.
             *
             * @param obj the JSON object to parse
             * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
             */
            static Optional<Participants> of(JSONObject obj) {
                if (obj == null) {
                    return Optional.empty();
                }

                var edges = Edges.ofArray(obj.getJSONArray("edges"));
                var participantsPhashMatch = obj.getBoolean("participants_phash_match");
                return Optional.of(new Participants(edges, participantsPhashMatch));
            }

            /**
             * Parses a list of {@code Participants} from the given JSON array.
             *
             * @param arr the JSON array to parse
             * @return the list of parsed results, empty if {@code arr} is {@code null}
             */
            static List<Participants> ofArray(JSONArray arr) {
                if (arr == null) {
                    return List.of();
                }

                var result = new ArrayList<Participants>(arr.size());
                for (var i = 0; i < arr.size(); i++) {
                    of(arr.getJSONObject(i)).ifPresent(result::add);
                }
                return result;
            }
        }

        /**
         * A parsed {@code Properties} object.
         */
        public static final class Properties {
            private final Boolean allowNonAdminSubGroupCreation;
            private final String closedByMembershipApprovalMode;
            private final LimitSharing limitSharing;
            private final LidMigrationState lidMigrationState;
            private final Ephemeral ephemeral;
            private final GrowthLocked2 growthLocked2;
            private final String memberAddMode;
            private final String parentGroupJid;
            private final String groupSafetyCheck;
            private final Boolean allowAdminReports;
            private final String announcement;
            private final String locked;
            private final String memberLinkMode;
            private final String memberShareGroupHistoryMode;
            private final Boolean membershipApprovalModeEnabled;
            private final String generalChat;
            private final Boolean autoAddDisabled;
            private final String hiddenGroup;
            private final String capi;
            private final String support;

            private Properties(Boolean allowNonAdminSubGroupCreation, String closedByMembershipApprovalMode, LimitSharing limitSharing, LidMigrationState lidMigrationState, Ephemeral ephemeral, GrowthLocked2 growthLocked2, String memberAddMode, String parentGroupJid, String groupSafetyCheck, Boolean allowAdminReports, String announcement, String locked, String memberLinkMode, String memberShareGroupHistoryMode, Boolean membershipApprovalModeEnabled, String generalChat, Boolean autoAddDisabled, String hiddenGroup, String capi, String support) {
                this.allowNonAdminSubGroupCreation = allowNonAdminSubGroupCreation;
                this.closedByMembershipApprovalMode = closedByMembershipApprovalMode;
                this.limitSharing = limitSharing;
                this.lidMigrationState = lidMigrationState;
                this.ephemeral = ephemeral;
                this.growthLocked2 = growthLocked2;
                this.memberAddMode = memberAddMode;
                this.parentGroupJid = parentGroupJid;
                this.groupSafetyCheck = groupSafetyCheck;
                this.allowAdminReports = allowAdminReports;
                this.announcement = announcement;
                this.locked = locked;
                this.memberLinkMode = memberLinkMode;
                this.memberShareGroupHistoryMode = memberShareGroupHistoryMode;
                this.membershipApprovalModeEnabled = membershipApprovalModeEnabled;
                this.generalChat = generalChat;
                this.autoAddDisabled = autoAddDisabled;
                this.hiddenGroup = hiddenGroup;
                this.capi = capi;
                this.support = support;
            }

            /**
             * Returns the {@code allow_non_admin_sub_group_creation} field.
             *
             * @return {@code true} if the value is present and true, {@code false} otherwise
             */
            public boolean allowNonAdminSubGroupCreation() {
                return allowNonAdminSubGroupCreation != null && allowNonAdminSubGroupCreation;
            }

            /**
             * Returns the {@code closed_by_membership_approval_mode} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> closedByMembershipApprovalMode() {
                return Optional.ofNullable(closedByMembershipApprovalMode);
            }

            /**
             * Returns the {@code limit_sharing} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<LimitSharing> limitSharing() {
                return Optional.ofNullable(limitSharing);
            }

            /**
             * Returns the {@code lid_migration_state} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<LidMigrationState> lidMigrationState() {
                return Optional.ofNullable(lidMigrationState);
            }

            /**
             * Returns the {@code ephemeral} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<Ephemeral> ephemeral() {
                return Optional.ofNullable(ephemeral);
            }

            /**
             * Returns the {@code growth_locked2} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<GrowthLocked2> growthLocked2() {
                return Optional.ofNullable(growthLocked2);
            }

            /**
             * Returns the {@code member_add_mode} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> memberAddMode() {
                return Optional.ofNullable(memberAddMode);
            }

            /**
             * Returns the {@code parent_group_jid} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> parentGroupJid() {
                return Optional.ofNullable(parentGroupJid);
            }

            /**
             * Returns the {@code group_safety_check} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> groupSafetyCheck() {
                return Optional.ofNullable(groupSafetyCheck);
            }

            /**
             * Returns the {@code allow_admin_reports} field.
             *
             * @return {@code true} if the value is present and true, {@code false} otherwise
             */
            public boolean allowAdminReports() {
                return allowAdminReports != null && allowAdminReports;
            }

            /**
             * Returns the {@code announcement} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> announcement() {
                return Optional.ofNullable(announcement);
            }

            /**
             * Returns the {@code locked} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> locked() {
                return Optional.ofNullable(locked);
            }

            /**
             * Returns the {@code member_link_mode} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> memberLinkMode() {
                return Optional.ofNullable(memberLinkMode);
            }

            /**
             * Returns the {@code member_share_group_history_mode} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> memberShareGroupHistoryMode() {
                return Optional.ofNullable(memberShareGroupHistoryMode);
            }

            /**
             * Returns the {@code membership_approval_mode_enabled} field.
             *
             * @return {@code true} if the value is present and true, {@code false} otherwise
             */
            public boolean membershipApprovalModeEnabled() {
                return membershipApprovalModeEnabled != null && membershipApprovalModeEnabled;
            }

            /**
             * Returns the {@code general_chat} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> generalChat() {
                return Optional.ofNullable(generalChat);
            }

            /**
             * Returns the {@code auto_add_disabled} field.
             *
             * @return {@code true} if the value is present and true, {@code false} otherwise
             */
            public boolean autoAddDisabled() {
                return autoAddDisabled != null && autoAddDisabled;
            }

            /**
             * Returns the {@code hidden_group} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> hiddenGroup() {
                return Optional.ofNullable(hiddenGroup);
            }

            /**
             * Returns the {@code capi} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> capi() {
                return Optional.ofNullable(capi);
            }

            /**
             * Returns the {@code support} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> support() {
                return Optional.ofNullable(support);
            }

            /**
             * A parsed {@code LimitSharing} object.
             */
            public static final class LimitSharing {
                private final Boolean limitSharingEnabled;

                private LimitSharing(Boolean limitSharingEnabled) {
                    this.limitSharingEnabled = limitSharingEnabled;
                }

                /**
                 * Returns the {@code limit_sharing_enabled} field.
                 *
                 * @return {@code true} if the value is present and true, {@code false} otherwise
                 */
                public boolean limitSharingEnabled() {
                    return limitSharingEnabled != null && limitSharingEnabled;
                }

                /**
                 * Parses a {@code LimitSharing} from the given JSON object.
                 *
                 * @param obj the JSON object to parse
                 * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                 */
                static Optional<LimitSharing> of(JSONObject obj) {
                    if (obj == null) {
                        return Optional.empty();
                    }

                    var limitSharingEnabled = obj.getBoolean("limit_sharing_enabled");
                    return Optional.of(new LimitSharing(limitSharingEnabled));
                }

                /**
                 * Parses a list of {@code LimitSharing} from the given JSON array.
                 *
                 * @param arr the JSON array to parse
                 * @return the list of parsed results, empty if {@code arr} is {@code null}
                 */
                static List<LimitSharing> ofArray(JSONArray arr) {
                    if (arr == null) {
                        return List.of();
                    }

                    var result = new ArrayList<LimitSharing>(arr.size());
                    for (var i = 0; i < arr.size(); i++) {
                        of(arr.getJSONObject(i)).ifPresent(result::add);
                    }
                    return result;
                }
            }

            /**
             * A parsed {@code LidMigrationState} object.
             */
            public static final class LidMigrationState {
                private final String addressingMode;

                private LidMigrationState(String addressingMode) {
                    this.addressingMode = addressingMode;
                }

                /**
                 * Returns the {@code addressing_mode} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> addressingMode() {
                    return Optional.ofNullable(addressingMode);
                }

                /**
                 * Parses a {@code LidMigrationState} from the given JSON object.
                 *
                 * @param obj the JSON object to parse
                 * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                 */
                static Optional<LidMigrationState> of(JSONObject obj) {
                    if (obj == null) {
                        return Optional.empty();
                    }

                    var addressingMode = obj.getString("addressing_mode");
                    return Optional.of(new LidMigrationState(addressingMode));
                }

                /**
                 * Parses a list of {@code LidMigrationState} from the given JSON array.
                 *
                 * @param arr the JSON array to parse
                 * @return the list of parsed results, empty if {@code arr} is {@code null}
                 */
                static List<LidMigrationState> ofArray(JSONArray arr) {
                    if (arr == null) {
                        return List.of();
                    }

                    var result = new ArrayList<LidMigrationState>(arr.size());
                    for (var i = 0; i < arr.size(); i++) {
                        of(arr.getJSONObject(i)).ifPresent(result::add);
                    }
                    return result;
                }
            }

            /**
             * A parsed {@code Ephemeral} object.
             */
            public static final class Ephemeral {
                private final Long expirationTimeInSec;

                private Ephemeral(Long expirationTimeInSec) {
                    this.expirationTimeInSec = expirationTimeInSec;
                }

                /**
                 * Returns the {@code expiration_time_in_sec} field.
                 *
                 * @return an {@link Optional} containing the value as a {@link Duration}, or empty if absent
                 */
                public Optional<Duration> expirationTimeInSec() {
                    return Optional.ofNullable(expirationTimeInSec).map(Duration::ofSeconds);
                }

                /**
                 * Parses a {@code Ephemeral} from the given JSON object.
                 *
                 * @param obj the JSON object to parse
                 * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                 */
                static Optional<Ephemeral> of(JSONObject obj) {
                    if (obj == null) {
                        return Optional.empty();
                    }

                    var expirationTimeInSec = obj.getLong("expiration_time_in_sec");
                    return Optional.of(new Ephemeral(expirationTimeInSec));
                }

                /**
                 * Parses a list of {@code Ephemeral} from the given JSON array.
                 *
                 * @param arr the JSON array to parse
                 * @return the list of parsed results, empty if {@code arr} is {@code null}
                 */
                static List<Ephemeral> ofArray(JSONArray arr) {
                    if (arr == null) {
                        return List.of();
                    }

                    var result = new ArrayList<Ephemeral>(arr.size());
                    for (var i = 0; i < arr.size(); i++) {
                        of(arr.getJSONObject(i)).ifPresent(result::add);
                    }
                    return result;
                }
            }

            /**
             * A parsed {@code GrowthLocked2} object.
             */
            public static final class GrowthLocked2 {
                private final String locked;

                private GrowthLocked2(String locked) {
                    this.locked = locked;
                }

                /**
                 * Returns the {@code locked} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> locked() {
                    return Optional.ofNullable(locked);
                }

                /**
                 * Parses a {@code GrowthLocked2} from the given JSON object.
                 *
                 * @param obj the JSON object to parse
                 * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                 */
                static Optional<GrowthLocked2> of(JSONObject obj) {
                    if (obj == null) {
                        return Optional.empty();
                    }

                    var locked = obj.getString("locked");
                    return Optional.of(new GrowthLocked2(locked));
                }

                /**
                 * Parses a list of {@code GrowthLocked2} from the given JSON array.
                 *
                 * @param arr the JSON array to parse
                 * @return the list of parsed results, empty if {@code arr} is {@code null}
                 */
                static List<GrowthLocked2> ofArray(JSONArray arr) {
                    if (arr == null) {
                        return List.of();
                    }

                    var result = new ArrayList<GrowthLocked2>(arr.size());
                    for (var i = 0; i < arr.size(); i++) {
                        of(arr.getJSONObject(i)).ifPresent(result::add);
                    }
                    return result;
                }
            }

            /**
             * Parses a {@code Properties} from the given JSON object.
             *
             * @param obj the JSON object to parse
             * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
             */
            static Optional<Properties> of(JSONObject obj) {
                if (obj == null) {
                    return Optional.empty();
                }

                var allowNonAdminSubGroupCreation = obj.getBoolean("allow_non_admin_sub_group_creation");
                var closedByMembershipApprovalMode = obj.getString("closed_by_membership_approval_mode");
                var limitSharing = LimitSharing.of(obj.getJSONObject("limit_sharing")).orElse(null);
                var lidMigrationState = LidMigrationState.of(obj.getJSONObject("lid_migration_state")).orElse(null);
                var ephemeral = Ephemeral.of(obj.getJSONObject("ephemeral")).orElse(null);
                var growthLocked2 = GrowthLocked2.of(obj.getJSONObject("growth_locked2")).orElse(null);
                var memberAddMode = obj.getString("member_add_mode");
                var parentGroupJid = obj.getString("parent_group_jid");
                var groupSafetyCheck = obj.getString("group_safety_check");
                var allowAdminReports = obj.getBoolean("allow_admin_reports");
                var announcement = obj.getString("announcement");
                var locked = obj.getString("locked");
                var memberLinkMode = obj.getString("member_link_mode");
                var memberShareGroupHistoryMode = obj.getString("member_share_group_history_mode");
                var membershipApprovalModeEnabled = obj.getBoolean("membership_approval_mode_enabled");
                var generalChat = obj.getString("general_chat");
                var autoAddDisabled = obj.getBoolean("auto_add_disabled");
                var hiddenGroup = obj.getString("hidden_group");
                var capi = obj.getString("capi");
                var support = obj.getString("support");
                return Optional.of(new Properties(allowNonAdminSubGroupCreation, closedByMembershipApprovalMode, limitSharing, lidMigrationState, ephemeral, growthLocked2, memberAddMode, parentGroupJid, groupSafetyCheck, allowAdminReports, announcement, locked, memberLinkMode, memberShareGroupHistoryMode, membershipApprovalModeEnabled, generalChat, autoAddDisabled, hiddenGroup, capi, support));
            }

            /**
             * Parses a list of {@code Properties} from the given JSON array.
             *
             * @param arr the JSON array to parse
             * @return the list of parsed results, empty if {@code arr} is {@code null}
             */
            static List<Properties> ofArray(JSONArray arr) {
                if (arr == null) {
                    return List.of();
                }

                var result = new ArrayList<Properties>(arr.size());
                for (var i = 0; i < arr.size(); i++) {
                    of(arr.getJSONObject(i)).ifPresent(result::add);
                }
                return result;
            }
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_group_query_by_id");
            if (root == null) {
                return Optional.empty();
            }

            var id = root.getString("id");
            var creationTime = root.getLong("creation_time");
            var creator = Creator.of(root.getJSONObject("creator")).orElse(null);
            var state = root.getString("state");
            var subject = Subject.of(root.getJSONObject("subject")).orElse(null);
            var description = Description.of(root.getJSONObject("description")).orElse(null);
            var participants = Participants.of(root.getJSONObject("participants")).orElse(null);
            var totalParticipantsCount = root.getLong("total_participants_count");
            var missingParticipantIdentification = root.getString("missing_participant_identification");
            var properties = Properties.of(root.getJSONObject("properties")).orElse(null);
            var membershipApprovalRequest = root.getString("membership_approval_request");

            return Optional.of(new Response(id, creationTime, creator, state, subject, description, participants, totalParticipantsCount, missingParticipantIdentification, properties, membershipApprovalRequest));
        }
    }
}
