package com.github.auties00.cobalt.node.mex.json.group;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX query operation for the {@code FetchGroupInfo} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface FetchGroupInfoMex extends MexJsonOperation permits FetchGroupInfoMex.Request, FetchGroupInfoMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "24996236089970735";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchGroupInfoMex {
        private final String id;
        private final boolean includeUsername;
        private final String participantsPhash;
        private final String queryContext;

        public Request(String id, boolean includeUsername, String participantsPhash, String queryContext) {
            this.id = id;
            this.includeUsername = includeUsername;
            this.participantsPhash = participantsPhash;
            this.queryContext = queryContext;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("id");
                writer.writeColon();
                writer.writeString(id);
                writer.writeName("include_username");
                writer.writeColon();
                writer.writeBool(includeUsername);
                writer.writeName("participants_phash");
                writer.writeColon();
                writer.writeString(participantsPhash);
                writer.writeName("query_context");
                writer.writeColon();
                writer.writeString(queryContext);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchGroupInfoMex {
        private final String id;
        private final String creationTime;
        private final String creatorId;
        private final String creatorLid;
        private final String creatorPn;
        private final String state;
        private final String subjectCreationTime;
        private final String subjectValue;
        private final String descriptionId;
        private final String descriptionCreationTime;
        private final String descriptionValue;
        private final String participantsParticipantsPhashMatch;
        private final String totalParticipantsCount;
        private final String missingParticipantIdentification;

        private Response(String id, String creationTime, String creatorId, String creatorLid, String creatorPn, String state, String subjectCreationTime, String subjectValue, String descriptionId, String descriptionCreationTime, String descriptionValue, String participantsParticipantsPhashMatch, String totalParticipantsCount, String missingParticipantIdentification) {
            this.id = id;
            this.creationTime = creationTime;
            this.creatorId = creatorId;
            this.creatorLid = creatorLid;
            this.creatorPn = creatorPn;
            this.state = state;
            this.subjectCreationTime = subjectCreationTime;
            this.subjectValue = subjectValue;
            this.descriptionId = descriptionId;
            this.descriptionCreationTime = descriptionCreationTime;
            this.descriptionValue = descriptionValue;
            this.participantsParticipantsPhashMatch = participantsParticipantsPhashMatch;
            this.totalParticipantsCount = totalParticipantsCount;
            this.missingParticipantIdentification = missingParticipantIdentification;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> id() {
            return Optional.ofNullable(id);
        }

        /**
         * Returns the {@code creation_time} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> creationTime() {
            return Optional.ofNullable(creationTime);
        }

        /**
         * Returns the {@code creator.id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> creatorId() {
            return Optional.ofNullable(creatorId);
        }

        /**
         * Returns the {@code creator.lid} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> creatorLid() {
            return Optional.ofNullable(creatorLid);
        }

        /**
         * Returns the {@code creator.pn} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> creatorPn() {
            return Optional.ofNullable(creatorPn);
        }

        /**
         * Returns the {@code state} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> state() {
            return Optional.ofNullable(state);
        }

        /**
         * Returns the {@code subject.creation_time} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> subjectCreationTime() {
            return Optional.ofNullable(subjectCreationTime);
        }

        /**
         * Returns the {@code subject.value} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> subjectValue() {
            return Optional.ofNullable(subjectValue);
        }

        /**
         * Returns the {@code description.id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> descriptionId() {
            return Optional.ofNullable(descriptionId);
        }

        /**
         * Returns the {@code description.creation_time} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> descriptionCreationTime() {
            return Optional.ofNullable(descriptionCreationTime);
        }

        /**
         * Returns the {@code description.value} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> descriptionValue() {
            return Optional.ofNullable(descriptionValue);
        }

        /**
         * Returns the {@code participants.participants_phash_match} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> participantsParticipantsPhashMatch() {
            return Optional.ofNullable(participantsParticipantsPhashMatch);
        }

        /**
         * Returns the {@code total_participants_count} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> totalParticipantsCount() {
            return Optional.ofNullable(totalParticipantsCount);
        }

        /**
         * Returns the {@code missing_participant_identification} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> missingParticipantIdentification() {
            return Optional.ofNullable(missingParticipantIdentification);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_group_query_by_id");
            if (root == null) {
                return Optional.empty();
            }

            var id = root.getString("id");
            var creationTime = root.getString("creation_time");
            var state = root.getString("state");
            var totalParticipantsCount = root.getString("total_participants_count");
            var missingParticipantIdentification = root.getString("missing_participant_identification");
            var creator = root.getJSONObject("creator");
            var creatorId = creator != null ? creator.getString("id") : null;
            var creatorLid = creator != null ? creator.getString("lid") : null;
            var creatorPn = creator != null ? creator.getString("pn") : null;
            var subject = root.getJSONObject("subject");
            var subjectCreationTime = subject != null ? subject.getString("creation_time") : null;
            var subjectValue = subject != null ? subject.getString("value") : null;
            var description = root.getJSONObject("description");
            var descriptionId = description != null ? description.getString("id") : null;
            var descriptionCreationTime = description != null ? description.getString("creation_time") : null;
            var descriptionValue = description != null ? description.getString("value") : null;
            var participants = root.getJSONObject("participants");
            var participantsParticipantsPhashMatch = participants != null ? participants.getString("participants_phash_match") : null;

            return Optional.of(new Response(id, creationTime, creatorId, creatorLid, creatorPn, state, subjectCreationTime, subjectValue, descriptionId, descriptionCreationTime, descriptionValue, participantsParticipantsPhashMatch, totalParticipantsCount, missingParticipantIdentification));
        }
    }
}
