package com.github.auties00.cobalt.node.mex.json.group;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX mutation operation for the {@code UpdateGroupProperty} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface UpdateGroupPropertyMex extends MexJsonOperation permits UpdateGroupPropertyMex.Request, UpdateGroupPropertyMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "9418211574894172";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements UpdateGroupPropertyMex {
        private final String groupId;
        private final String update;

        public Request(String groupId, String update) {
            this.groupId = groupId;
            this.update = update;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("group_id");
                writer.writeColon();
                writer.writeString(groupId);
                writer.writeName("update");
                writer.writeColon();
                writer.writeString(update);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements UpdateGroupPropertyMex {
        private final String id;
        private final String state;

        private Response(String id, String state) {
            this.id = id;
            this.state = state;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> id() {
            return Optional.ofNullable(id);
        }

        /**
         * Returns the {@code state} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> state() {
            return Optional.ofNullable(state);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_group_update_property");
            if (root == null) {
                return Optional.empty();
            }

            var id = root.getString("id");
            var state = root.getString("state");

            return Optional.of(new Response(id, state));
        }
    }
}
