package com.github.auties00.cobalt.node.mex.json.user;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX query operation for the {@code GetUsername} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface GetUsernameMex extends MexJsonOperation permits GetUsernameMex.Request, GetUsernameMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "25347099718279209";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements GetUsernameMex {

        public Request() {
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements GetUsernameMex {
        private final String usernameInfoUsername;
        private final String usernameInfoState;
        private final String usernameInfoPin;

        private Response(String usernameInfoUsername, String usernameInfoState, String usernameInfoPin) {
            this.usernameInfoUsername = usernameInfoUsername;
            this.usernameInfoState = usernameInfoState;
            this.usernameInfoPin = usernameInfoPin;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code username_info.username} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> usernameInfoUsername() {
            return Optional.ofNullable(usernameInfoUsername);
        }

        /**
         * Returns the {@code username_info.state} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> usernameInfoState() {
            return Optional.ofNullable(usernameInfoState);
        }

        /**
         * Returns the {@code username_info.pin} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> usernameInfoPin() {
            return Optional.ofNullable(usernameInfoPin);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_username_get");
            if (root == null) {
                return Optional.empty();
            }

            var usernameInfo = root.getJSONObject("username_info");
            var usernameInfoUsername = usernameInfo != null ? usernameInfo.getString("username") : null;
            var usernameInfoState = usernameInfo != null ? usernameInfo.getString("state") : null;
            var usernameInfoPin = usernameInfo != null ? usernameInfo.getString("pin") : null;

            return Optional.of(new Response(usernameInfoUsername, usernameInfoState, usernameInfoPin));
        }
    }
}
