package com.github.auties00.cobalt.node.mex.json.user;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX mutation operation for the {@code SetUsername} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface SetUsernameMex extends MexJsonOperation permits SetUsernameMex.Request, SetUsernameMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "25757341163897635";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements SetUsernameMex {
        private final String input;
        private final boolean reserved;
        private final String sessionId;
        private final String source;

        public Request(String input, boolean reserved, String sessionId, String source) {
            this.input = input;
            this.reserved = reserved;
            this.sessionId = sessionId;
            this.source = source;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("input");
                writer.writeColon();
                writer.writeString(input);
                writer.writeName("reserved");
                writer.writeColon();
                writer.writeBool(reserved);
                writer.writeName("session_id");
                writer.writeColon();
                writer.writeString(sessionId);
                writer.writeName("source");
                writer.writeColon();
                writer.writeString(source);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements SetUsernameMex {
        private final String result;

        private Response(String result) {
            this.result = result;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code result} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> result() {
            return Optional.ofNullable(result);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_username_set");
            if (root == null) {
                return Optional.empty();
            }

            var result = root.getString("result");

            return Optional.of(new Response(result));
        }
    }
}
