package com.github.auties00.cobalt.node.mex.json.user;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX query operation for the {@code UsernameAvailability} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface UsernameAvailabilityMex extends MexJsonOperation permits UsernameAvailabilityMex.Request, UsernameAvailabilityMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "9615795045169045";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements UsernameAvailabilityMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("input");
                writer.writeColon();
                writer.writeString(input);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements UsernameAvailabilityMex {
        private final String result;
        private final String suggestions;

        private Response(String result, String suggestions) {
            this.result = result;
            this.suggestions = suggestions;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code result} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> result() {
            return Optional.ofNullable(result);
        }

        /**
         * Returns the {@code suggestions} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> suggestions() {
            return Optional.ofNullable(suggestions);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_username_check");
            if (root == null) {
                return Optional.empty();
            }

            var result = root.getString("result");
            var suggestions = root.getString("suggestions");

            return Optional.of(new Response(result, suggestions));
        }
    }
}
