package com.github.auties00.cobalt.device.fanout;

import com.alibaba.fastjson2.JSONObject;
import com.github.auties00.cobalt.device.DeviceFixtures;
import com.github.auties00.cobalt.model.jid.Jid;
import com.github.auties00.cobalt.model.props.ABProp;
import com.github.auties00.cobalt.props.TestABPropsService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exercises {@link DevicePhashCalculator} against live-bundle Known Answer Test vectors and
 * structural edge cases.
 *
 * @apiNote
 * Validates Cobalt's V1 and V2 implementations against the wire output of
 * {@code WAWebPhashUtils.phashV1} and {@code WAWebPhashUtils.phashV2}. The {@link WaWebOracleKat}
 * nested class is the byte-equality parity layer; the remaining nested classes carry structural
 * checks (prefix shape, determinism, bot-injection gating) that exercise edge cases the
 * captured corpus does not.
 *
 * @implNote
 * This implementation loads KAT vectors from
 * {@code modules/lib/src/test/resources/fixtures/device/phash-samples.expected.json} via
 * {@link DeviceFixtures#loadOracle(String)}; the corpus is regenerated by re-running
 * {@code src/test/resources/fixtures/device/generate.mjs} without touching test code.
 */
@DisplayName("DevicePhashCalculator")
class DevicePhashCalculatorTest {
    private static final Jid PEER = Jid.of("393495089819@s.whatsapp.net");
    private static final Jid PEER_DEV_1 = Jid.of("393495089819:1@s.whatsapp.net");
    private static final Jid SELF = Jid.of("19254863482@s.whatsapp.net");
    private static final Jid SELF_DEV_15 = Jid.of("19254863482:15@s.whatsapp.net");

    /**
     * Holds the KAT vectors and parity assertions against the live WA Web bundle.
     */
    @Nested
    @DisplayName("WA Web oracle parity (Known Answer Test)")
    class WaWebOracleKat {
        /**
         * One captured KAT vector pinning live {@code phashV1} and {@code phashV2} output for
         * a specific device set.
         *
         * @apiNote
         * Inputs are the device JID strings fed to {@code phashV1} and {@code phashV2}; the
         * two output strings are the exact return values of the live JS bundle.
         *
         * @param tag      the human-readable sample id from the oracle JSON
         * @param devices  the device JID strings under test
         * @param phashV1  the expected V1 output captured from the live bundle
         * @param phashV2  the expected V2 output captured from the live bundle
         */
        private record Vector(String tag, List<String> devices, String phashV1, String phashV2) {
        }

        /**
         * Loads every KAT vector from the bundled oracle JSON.
         *
         * @apiNote
         * The oracle is captured via {@code mcp__whatsapp__web_live_debug_eval_to_file} and
         * persisted at {@code fixtures/device/phash-samples.expected.json}; one entry per
         * sample is returned.
         *
         * @return the parsed KAT vectors in oracle order
         */
        private static List<Vector> loadVectors() {
            var oracle = DeviceFixtures.loadOracle("phash-samples");
            var vectors = new ArrayList<Vector>(oracle.size());
            for (var entry : oracle.entrySet()) {
                var sample = (JSONObject) entry.getValue();
                var devices = sample.getJSONArray("devices");
                var deviceStrings = new ArrayList<String>(devices.size());
                for (var i = 0; i < devices.size(); i++) {
                    deviceStrings.add(devices.getString(i));
                }
                vectors.add(new Vector(
                        entry.getKey(),
                        List.copyOf(deviceStrings),
                        sample.getString("phashV1"),
                        sample.getString("phashV2")));
            }
            return vectors;
        }

        /**
         * Cobalt's V1 output is byte-equal to the live bundle's {@code phashV1} on every
         * captured vector.
         */
        @Test
        @DisplayName("V1 byte-equality against live bundle")
        void phashV1MatchesLiveBundle() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            for (var v : loadVectors()) {
                var jids = toJidSet(v.devices());
                var actual = calculator.calculate(jids, DevicePhashVersion.V1, false);
                assertEquals(v.phashV1(), actual, "phashV1 mismatch on vector '" + v.tag() + "'");
            }
        }

        /**
         * Cobalt's V2 output is byte-equal to the live bundle's {@code phashV2} on every
         * captured vector.
         */
        @Test
        @DisplayName("V2 byte-equality against live bundle")
        void phashV2MatchesLiveBundle() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            for (var v : loadVectors()) {
                var jids = toJidSet(v.devices());
                var actual = calculator.calculate(jids, DevicePhashVersion.V2, false);
                assertEquals(v.phashV2(), actual, "phashV2 mismatch on vector '" + v.tag() + "'");
            }
        }

        /**
         * Materialises the captured device JID strings into a {@link LinkedHashSet} of
         * {@link Jid}.
         *
         * @apiNote
         * Uses {@link LinkedHashSet} to preserve the capture order so a debug failure can
         * point at the offending JID.
         *
         * @param devices the captured device JID strings
         * @return the parsed JIDs in capture order
         */
        private static Set<Jid> toJidSet(List<String> devices) {
            var jids = new LinkedHashSet<Jid>();
            for (var s : devices) {
                jids.add(Jid.of(s));
            }
            return jids;
        }
    }

    /**
     * Groups the V1-shape structural checks; these run without an oracle.
     */
    @Nested
    @DisplayName("V1 phash")
    class V1 {
        /**
         * V1 output starts with the {@code "1:"} prefix.
         */
        @Test
        @DisplayName("starts with the V1 prefix")
        void prefix() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var phash = calculator.calculate(Set.of(PEER), DevicePhashVersion.V1, false);
            assertTrue(phash.startsWith(DevicePhashVersion.V1.prefix()),
                    "phash should start with V1 prefix '" + DevicePhashVersion.V1.prefix() + "' but was: " + phash);
        }

        /**
         * The base64 portion of the V1 output is exactly 8 characters wide (6 bytes encoded
         * without padding).
         */
        @Test
        @DisplayName("emits a base64 hash that decodes to 6 bytes")
        void truncationLength() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var phash = calculator.calculate(Set.of(PEER, PEER_DEV_1), DevicePhashVersion.V1, false);
            var base64Part = phash.substring(DevicePhashVersion.V1.prefix().length());
            assertEquals(8, base64Part.length());
        }

        /**
         * Two calls with the same set of JIDs in different insertion order produce the same
         * V1 output.
         */
        @Test
        @DisplayName("is order-independent for the same set of JIDs")
        void orderIndependent() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var a = calculator.calculate(Set.of(PEER, SELF), DevicePhashVersion.V1, false);
            var b = calculator.calculate(Set.of(SELF, PEER), DevicePhashVersion.V1, false);
            assertEquals(a, b);
        }
    }

    /**
     * Groups the V2-shape structural checks.
     */
    @Nested
    @DisplayName("V2 phash")
    class V2 {
        /**
         * V2 output starts with the {@code "2:"} prefix.
         */
        @Test
        @DisplayName("starts with the V2 prefix")
        void prefix() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var phash = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, false);
            assertTrue(phash.startsWith(DevicePhashVersion.V2.prefix()),
                    "phash should start with V2 prefix '" + DevicePhashVersion.V2.prefix() + "' but was: " + phash);
        }

        /**
         * V1 and V2 produce different outputs for the same input because the digest, the
         * legacy-string format, and the prefix all differ.
         */
        @Test
        @DisplayName("V1 and V2 produce different phashes for the same input")
        void differsFromV1() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var devices = Set.of(PEER_DEV_1, SELF_DEV_15);
            var v1 = calculator.calculate(devices, DevicePhashVersion.V1, false);
            var v2 = calculator.calculate(devices, DevicePhashVersion.V2, false);
            assertNotEquals(v1, v2);
        }

        /**
         * Changing a device id under V2 changes the output (because V2's legacy-string format
         * includes the device id).
         */
        @Test
        @DisplayName("differs when one device id changes")
        void differsByDeviceId() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var a = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, false);
            var b = calculator.calculate(Set.of(Jid.of("393495089819:2@s.whatsapp.net")), DevicePhashVersion.V2, false);
            assertNotEquals(a, b);
        }
    }

    /**
     * Groups the Meta AI bot injection gating scenarios; pins the interaction between the
     * per-call boolean flags and the AB-prop gating predicates.
     */
    @Nested
    @DisplayName("Meta AI bot gating")
    class MetaAiBotGating {
        /**
         * Passing {@code allowIncludeOpenBot=false} leaves the open bot out even when the
         * gating AB props are on.
         */
        @Test
        @DisplayName("does not include the open bot when allowIncludeOpenBot=false")
        void openBotNotIncludedWithoutFlag() throws NoSuchAlgorithmException {
            var props = TestABPropsService.builder()
                    .with(ABProp.WEB_AI_GROUP_OPEN_SUPPORT, true)
                    .with(ABProp.AI_GROUP_PARTICIPATION_ENABLED, true)
                    .build();
            var calculator = new DevicePhashCalculator(props);

            var without = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, false);
            var withOpenBot = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, true);

            assertNotEquals(without, withOpenBot,
                    "phash should change when the open bot is injected via the flag");
        }

        /**
         * The {@code allowIncludeOpenBot=true} flag is ignored when the gating AB props are
         * off.
         */
        @Test
        @DisplayName("does not include the open bot when the gating AB props are off")
        void openBotNotIncludedWhenAbPropsDisabled() throws NoSuchAlgorithmException {
            var props = TestABPropsService.builder()
                    .with(ABProp.WEB_AI_GROUP_OPEN_SUPPORT, false)
                    .with(ABProp.AI_GROUP_PARTICIPATION_ENABLED, false)
                    .build();
            var calculator = new DevicePhashCalculator(props);

            var without = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, false);
            var withOpenBot = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, true);

            assertEquals(without, withOpenBot,
                    "phash should NOT change when the open bot flag is set but AB props deny inclusion");
        }

        /**
         * The TEE bot is injected when both {@code allowIncludeTeeBot} and the matching AB
         * props are set.
         */
        @Test
        @DisplayName("includes the TEE bot when both the flag and the gating AB props are on")
        void teeBotIncluded() throws NoSuchAlgorithmException {
            var props = TestABPropsService.builder()
                    .with(ABProp.WEB_AI_GROUP_OPEN_SUPPORT, true)
                    .with(ABProp.AI_GROUP_PARTICIPATION_ADD_TEE_ENABLED, true)
                    .build();
            var calculator = new DevicePhashCalculator(props);

            var without = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, false, false);
            var withTeeBot = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, false, true);

            assertNotEquals(without, withTeeBot);
        }

        /**
         * V1 never injects bots, regardless of which flags or AB props are set.
         */
        @Test
        @DisplayName("V1 ignores bot inclusion flags regardless of AB props")
        void v1IgnoresBots() throws NoSuchAlgorithmException {
            var props = TestABPropsService.builder()
                    .with(ABProp.WEB_AI_GROUP_OPEN_SUPPORT, true)
                    .with(ABProp.AI_GROUP_PARTICIPATION_ENABLED, true)
                    .with(ABProp.AI_GROUP_PARTICIPATION_ADD_TEE_ENABLED, true)
                    .build();
            var calculator = new DevicePhashCalculator(props);

            var without = calculator.calculate(Set.of(PEER), DevicePhashVersion.V1, false, false);
            var withBots = calculator.calculate(Set.of(PEER), DevicePhashVersion.V1, true, true);

            assertEquals(without, withBots, "V1 must not inject bots");
        }
    }

    /**
     * Groups the determinism checks; the calculator must be a pure function of its inputs.
     */
    @Nested
    @DisplayName("determinism")
    class Determinism {
        /**
         * Repeated calls with identical inputs produce identical outputs.
         */
        @Test
        @DisplayName("repeated calls with identical inputs produce identical outputs")
        void deterministic() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var phash1 = calculator.calculate(Set.of(PEER, PEER_DEV_1, SELF_DEV_15), DevicePhashVersion.V2, false);
            var phash2 = calculator.calculate(Set.of(PEER, PEER_DEV_1, SELF_DEV_15), DevicePhashVersion.V2, false);
            assertEquals(phash1, phash2);
        }

        /**
         * Adding a device to the input set changes the output.
         */
        @Test
        @DisplayName("adding a device changes the phash")
        void differentForDifferentSets() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var a = calculator.calculate(Set.of(PEER, PEER_DEV_1), DevicePhashVersion.V2, false);
            var b = calculator.calculate(Set.of(PEER, PEER_DEV_1, SELF_DEV_15), DevicePhashVersion.V2, false);
            assertNotEquals(a, b);
        }
    }
}
