package com.github.auties00.cobalt.node.mex.json.newsletter;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX mutation operation for the {@code CreateNewsletter} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface CreateNewsletterMex extends MexJsonOperation permits CreateNewsletterMex.Request, CreateNewsletterMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "25149874324715067";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements CreateNewsletterMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("input");
                writer.writeColon();
                writer.writeString(input);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements CreateNewsletterMex {
        private final String id;
        private final String stateType;
        private final String threadMetadataInvite;
        private final String threadMetadataHandle;
        private final String threadMetadataVerification;
        private final String threadMetadataSubscribersCount;
        private final String threadMetadataCreationTime;
        private final String viewerMetadataRole;

        private Response(String id, String stateType, String threadMetadataInvite, String threadMetadataHandle, String threadMetadataVerification, String threadMetadataSubscribersCount, String threadMetadataCreationTime, String viewerMetadataRole) {
            this.id = id;
            this.stateType = stateType;
            this.threadMetadataInvite = threadMetadataInvite;
            this.threadMetadataHandle = threadMetadataHandle;
            this.threadMetadataVerification = threadMetadataVerification;
            this.threadMetadataSubscribersCount = threadMetadataSubscribersCount;
            this.threadMetadataCreationTime = threadMetadataCreationTime;
            this.viewerMetadataRole = viewerMetadataRole;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> id() {
            return Optional.ofNullable(id);
        }

        /**
         * Returns the {@code state.type} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> stateType() {
            return Optional.ofNullable(stateType);
        }

        /**
         * Returns the {@code thread_metadata.invite} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> threadMetadataInvite() {
            return Optional.ofNullable(threadMetadataInvite);
        }

        /**
         * Returns the {@code thread_metadata.handle} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> threadMetadataHandle() {
            return Optional.ofNullable(threadMetadataHandle);
        }

        /**
         * Returns the {@code thread_metadata.verification} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> threadMetadataVerification() {
            return Optional.ofNullable(threadMetadataVerification);
        }

        /**
         * Returns the {@code thread_metadata.subscribers_count} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> threadMetadataSubscribersCount() {
            return Optional.ofNullable(threadMetadataSubscribersCount);
        }

        /**
         * Returns the {@code thread_metadata.creation_time} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> threadMetadataCreationTime() {
            return Optional.ofNullable(threadMetadataCreationTime);
        }

        /**
         * Returns the {@code viewer_metadata.role} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> viewerMetadataRole() {
            return Optional.ofNullable(viewerMetadataRole);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_newsletter_create");
            if (root == null) {
                return Optional.empty();
            }

            var id = root.getString("id");
            var state = root.getJSONObject("state");
            var stateType = state != null ? state.getString("type") : null;
            var threadMetadata = root.getJSONObject("thread_metadata");
            var threadMetadataInvite = threadMetadata != null ? threadMetadata.getString("invite") : null;
            var threadMetadataHandle = threadMetadata != null ? threadMetadata.getString("handle") : null;
            var threadMetadataVerification = threadMetadata != null ? threadMetadata.getString("verification") : null;
            var threadMetadataSubscribersCount = threadMetadata != null ? threadMetadata.getString("subscribers_count") : null;
            var threadMetadataCreationTime = threadMetadata != null ? threadMetadata.getString("creation_time") : null;
            var viewerMetadata = root.getJSONObject("viewer_metadata");
            var viewerMetadataRole = viewerMetadata != null ? viewerMetadata.getString("role") : null;

            return Optional.of(new Response(id, stateType, threadMetadataInvite, threadMetadataHandle, threadMetadataVerification, threadMetadataSubscribersCount, threadMetadataCreationTime, viewerMetadataRole));
        }
    }
}
