package com.github.auties00.cobalt.node.mex.json.newsletter;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX mutation operation for the {@code CreateNewsletterAdminInvite} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface CreateNewsletterAdminInviteMex extends MexJsonOperation permits CreateNewsletterAdminInviteMex.Request, CreateNewsletterAdminInviteMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "9387141988078609";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements CreateNewsletterAdminInviteMex {
        private final String newsletterId;
        private final String userId;

        public Request(String newsletterId, String userId) {
            this.newsletterId = newsletterId;
            this.userId = userId;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("newsletter_id");
                writer.writeColon();
                writer.writeString(newsletterId);
                writer.writeName("user_id");
                writer.writeColon();
                writer.writeString(userId);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements CreateNewsletterAdminInviteMex {
        private final String inviteExpirationTime;

        private Response(String inviteExpirationTime) {
            this.inviteExpirationTime = inviteExpirationTime;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code invite_expiration_time} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> inviteExpirationTime() {
            return Optional.ofNullable(inviteExpirationTime);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_newsletter_admin_invite_create");
            if (root == null) {
                return Optional.empty();
            }

            var inviteExpirationTime = root.getString("invite_expiration_time");

            return Optional.of(new Response(inviteExpirationTime));
        }
    }
}
