package com.github.auties00.cobalt.node.mex.json.newsletter;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX query operation for the {@code FetchNewsletter} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface FetchNewsletterMex extends MexJsonOperation permits FetchNewsletterMex.Request, FetchNewsletterMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "25383075034668475";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchNewsletterMex {
        private final boolean fetchCreationTime;
        private final boolean fetchFullImage;
        private final boolean fetchViewerMetadata;
        private final boolean fetchWamoSub;
        private final String input;

        public Request(boolean fetchCreationTime, boolean fetchFullImage, boolean fetchViewerMetadata, boolean fetchWamoSub, String input) {
            this.fetchCreationTime = fetchCreationTime;
            this.fetchFullImage = fetchFullImage;
            this.fetchViewerMetadata = fetchViewerMetadata;
            this.fetchWamoSub = fetchWamoSub;
            this.input = input;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("fetch_creation_time");
                writer.writeColon();
                writer.writeBool(fetchCreationTime);
                writer.writeName("fetch_full_image");
                writer.writeColon();
                writer.writeBool(fetchFullImage);
                writer.writeName("fetch_viewer_metadata");
                writer.writeColon();
                writer.writeBool(fetchViewerMetadata);
                writer.writeName("fetch_wamo_sub");
                writer.writeColon();
                writer.writeBool(fetchWamoSub);
                writer.writeName("input");
                writer.writeColon();
                writer.writeString(input);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchNewsletterMex {
        private final String id;
        private final String stateType;
        private final String threadMetadataInvite;
        private final String threadMetadataHandle;
        private final String threadMetadataSubscribersCount;
        private final String threadMetadataVerification;

        private Response(String id, String stateType, String threadMetadataInvite, String threadMetadataHandle, String threadMetadataSubscribersCount, String threadMetadataVerification) {
            this.id = id;
            this.stateType = stateType;
            this.threadMetadataInvite = threadMetadataInvite;
            this.threadMetadataHandle = threadMetadataHandle;
            this.threadMetadataSubscribersCount = threadMetadataSubscribersCount;
            this.threadMetadataVerification = threadMetadataVerification;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> id() {
            return Optional.ofNullable(id);
        }

        /**
         * Returns the {@code state.type} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> stateType() {
            return Optional.ofNullable(stateType);
        }

        /**
         * Returns the {@code thread_metadata.invite} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> threadMetadataInvite() {
            return Optional.ofNullable(threadMetadataInvite);
        }

        /**
         * Returns the {@code thread_metadata.handle} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> threadMetadataHandle() {
            return Optional.ofNullable(threadMetadataHandle);
        }

        /**
         * Returns the {@code thread_metadata.subscribers_count} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> threadMetadataSubscribersCount() {
            return Optional.ofNullable(threadMetadataSubscribersCount);
        }

        /**
         * Returns the {@code thread_metadata.verification} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> threadMetadataVerification() {
            return Optional.ofNullable(threadMetadataVerification);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_newsletter");
            if (root == null) {
                return Optional.empty();
            }

            var id = root.getString("id");
            var state = root.getJSONObject("state");
            var stateType = state != null ? state.getString("type") : null;
            var threadMetadata = root.getJSONObject("thread_metadata");
            var threadMetadataInvite = threadMetadata != null ? threadMetadata.getString("invite") : null;
            var threadMetadataHandle = threadMetadata != null ? threadMetadata.getString("handle") : null;
            var threadMetadataSubscribersCount = threadMetadata != null ? threadMetadata.getString("subscribers_count") : null;
            var threadMetadataVerification = threadMetadata != null ? threadMetadata.getString("verification") : null;

            return Optional.of(new Response(id, stateType, threadMetadataInvite, threadMetadataHandle, threadMetadataSubscribersCount, threadMetadataVerification));
        }
    }
}
