package com.github.auties00.cobalt.node.mex.json.newsletter;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX query operation for the {@code FetchNewsletterInsights} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface FetchNewsletterInsightsMex extends MexJsonOperation permits FetchNewsletterInsightsMex.Request, FetchNewsletterInsightsMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "9853618868050977";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchNewsletterInsightsMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("input");
                writer.writeColon();
                writer.writeString(input);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchNewsletterInsightsMex {
        private final String newsletterId;
        private final String stateType;
        private final String lastUpdateTime;
        private final String metricsStatus;

        private Response(String newsletterId, String stateType, String lastUpdateTime, String metricsStatus) {
            this.newsletterId = newsletterId;
            this.stateType = stateType;
            this.lastUpdateTime = lastUpdateTime;
            this.metricsStatus = metricsStatus;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code newsletter_id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> newsletterId() {
            return Optional.ofNullable(newsletterId);
        }

        /**
         * Returns the {@code state.type} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> stateType() {
            return Optional.ofNullable(stateType);
        }

        /**
         * Returns the {@code last_update_time} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> lastUpdateTime() {
            return Optional.ofNullable(lastUpdateTime);
        }

        /**
         * Returns the {@code metrics_status} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> metricsStatus() {
            return Optional.ofNullable(metricsStatus);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_newsletter_admin_insights");
            if (root == null) {
                return Optional.empty();
            }

            var newsletterId = root.getString("newsletter_id");
            var lastUpdateTime = root.getString("last_update_time");
            var metricsStatus = root.getString("metrics_status");
            var state = root.getJSONObject("state");
            var stateType = state != null ? state.getString("type") : null;

            return Optional.of(new Response(newsletterId, stateType, lastUpdateTime, metricsStatus));
        }
    }
}
