package com.github.auties00.cobalt.node.mex.json.newsletter;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX query operation for the {@code FetchNewsletterDirectoryList} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface FetchNewsletterDirectoryListMex extends MexJsonOperation permits FetchNewsletterDirectoryListMex.Request, FetchNewsletterDirectoryListMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "23877680335183432";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchNewsletterDirectoryListMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("input");
                writer.writeColon();
                writer.writeString(input);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchNewsletterDirectoryListMex {
        private final String pageInfoHasNextPage;
        private final String pageInfoHasPreviousPage;
        private final String pageInfoStartCursor;
        private final String pageInfoEndCursor;

        private Response(String pageInfoHasNextPage, String pageInfoHasPreviousPage, String pageInfoStartCursor, String pageInfoEndCursor) {
            this.pageInfoHasNextPage = pageInfoHasNextPage;
            this.pageInfoHasPreviousPage = pageInfoHasPreviousPage;
            this.pageInfoStartCursor = pageInfoStartCursor;
            this.pageInfoEndCursor = pageInfoEndCursor;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code page_info.hasNextPage} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> pageInfoHasNextPage() {
            return Optional.ofNullable(pageInfoHasNextPage);
        }

        /**
         * Returns the {@code page_info.hasPreviousPage} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> pageInfoHasPreviousPage() {
            return Optional.ofNullable(pageInfoHasPreviousPage);
        }

        /**
         * Returns the {@code page_info.startCursor} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> pageInfoStartCursor() {
            return Optional.ofNullable(pageInfoStartCursor);
        }

        /**
         * Returns the {@code page_info.endCursor} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> pageInfoEndCursor() {
            return Optional.ofNullable(pageInfoEndCursor);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_newsletters_directory_list");
            if (root == null) {
                return Optional.empty();
            }

            var pageInfo = root.getJSONObject("page_info");
            var pageInfoHasNextPage = pageInfo != null ? pageInfo.getString("hasNextPage") : null;
            var pageInfoHasPreviousPage = pageInfo != null ? pageInfo.getString("hasPreviousPage") : null;
            var pageInfoStartCursor = pageInfo != null ? pageInfo.getString("startCursor") : null;
            var pageInfoEndCursor = pageInfo != null ? pageInfo.getString("endCursor") : null;

            return Optional.of(new Response(pageInfoHasNextPage, pageInfoHasPreviousPage, pageInfoStartCursor, pageInfoEndCursor));
        }
    }
}
