package com.github.auties00.cobalt.wam.privatestats;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

import java.util.Objects;

/**
 * The outcome of one successful {@code <sign_credential>} IQ
 * round-trip, carrying the secret token nonce that the client kept and
 * the shared secret derived for authenticating the matching upload.
 *
 * @apiNote
 * Returned by {@link WamPrivateStatsTokenIssuer#issue} and consumed by
 * {@link WamPrivateStatsUploader#upload(byte[])}. Mirrors the
 * {@code {token, sharedSecret}} object produced by
 * {@link WhatsAppWebModule WAACSTokenUtils} {@code .getSharedSecret}
 * and stored by {@code WAWebCRUDOperationsACSTokens.storeACSTokenForProject}.
 *
 * @implNote
 * This implementation defensively clones {@code token} and
 * {@code sharedSecret} on entry and exit so callers cannot mutate the
 * stored byte arrays, matching the immutability that the JS
 * {@code Uint8Array} carriers enjoy by being copied through structured
 * clones across the WA Web storage boundary.
 *
 * @param token        the 32-byte secret nonce randomly generated by
 *                     the client; never released to the server
 * @param sharedSecret the 64-byte {@code SHA-512(token || unblindedSignedToken)}
 *                     used as the upload authentication key
 */
@WhatsAppWebModule(moduleName = "WAWebIssuePrivateStatsToken")
public record WamPrivateStatsToken(byte[] token, byte[] sharedSecret) {
    /**
     * The length in bytes of the secret token nonce.
     *
     * @apiNote
     * Matches the {@code new Uint8Array(32)} buffer that
     * {@link WhatsAppWebModule WAACSTokenUtils} {@code .getBlindedToken}
     * fills with {@code crypto.getRandomValues}.
     */
    public static final int TOKEN_BYTES = 32;

    /**
     * The length in bytes of the derived shared secret, equal to a
     * full SHA-512 digest.
     *
     * @apiNote
     * Matches the output length of {@link WhatsAppWebModule WACryptoPrimitives}
     * {@code .hash} invoked by {@link WhatsAppWebModule WAACSTokenUtils}
     * {@code .getSharedSecret} on the concatenated {@code token || unblindedSignedToken}.
     */
    public static final int SHARED_SECRET_BYTES = 64;

    /**
     * Validates the component lengths and clones both arrays so the
     * record stores an isolated copy.
     *
     * @apiNote
     * The exact byte lengths are part of the wire contract; a
     * wrong-sized token leaks the bug as a length error rather than
     * a silent authentication failure downstream.
     *
     * @throws NullPointerException     if either component is
     *                                  {@code null}
     * @throws IllegalArgumentException if {@code token} is not
     *                                  {@value #TOKEN_BYTES} bytes
     *                                  or {@code sharedSecret} is not
     *                                  {@value #SHARED_SECRET_BYTES}
     *                                  bytes
     */
    public WamPrivateStatsToken {
        Objects.requireNonNull(token, "token must not be null");
        Objects.requireNonNull(sharedSecret, "sharedSecret must not be null");
        if (token.length != TOKEN_BYTES) {
            throw new IllegalArgumentException(
                    "token must be " + TOKEN_BYTES + " bytes, was " + token.length);
        }
        if (sharedSecret.length != SHARED_SECRET_BYTES) {
            throw new IllegalArgumentException(
                    "sharedSecret must be " + SHARED_SECRET_BYTES + " bytes, was " + sharedSecret.length);
        }
        token = token.clone();
        sharedSecret = sharedSecret.clone();
    }

    /**
     * Returns a fresh clone of the secret token nonce.
     *
     * @apiNote
     * The clone makes the record safe to hand to callers that may
     * mutate the array (for example the multipart-body assembler in
     * {@link WamPrivateStatsUploader}).
     *
     * @return a freshly allocated copy of the {@value #TOKEN_BYTES}
     *         token bytes
     */
    @Override
    public byte[] token() {
        return token.clone();
    }

    /**
     * Returns a fresh clone of the derived shared secret.
     *
     * @apiNote
     * The clone protects the stored bytes from being mutated by the
     * caller through the {@link javax.crypto.spec.SecretKeySpec}
     * constructor that consumes the array.
     *
     * @return a freshly allocated copy of the
     *         {@value #SHARED_SECRET_BYTES} shared-secret bytes
     */
    @Override
    public byte[] sharedSecret() {
        return sharedSecret.clone();
    }
}
