// Generated by jextract

package com.github.auties00.cobalt.call.internal.transport.sctp.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct in6_addr {
 *     uint8_t s6_addr[16];
 * }
 * }
 */
public class in6_addr {

    in6_addr() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(16, UsrSctp.C_CHAR).withName("s6_addr")
    ).withName("in6_addr");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout s6_addr$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("s6_addr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t s6_addr[16]
     * }
     */
    public static final SequenceLayout s6_addr$layout() {
        return s6_addr$LAYOUT;
    }

    private static final long s6_addr$OFFSET = $LAYOUT.byteOffset(groupElement("s6_addr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t s6_addr[16]
     * }
     */
    public static final long s6_addr$offset() {
        return s6_addr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t s6_addr[16]
     * }
     */
    public static MemorySegment s6_addr(MemorySegment struct) {
        return struct.asSlice(s6_addr$OFFSET, s6_addr$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t s6_addr[16]
     * }
     */
    public static void s6_addr(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, s6_addr$OFFSET, s6_addr$LAYOUT.byteSize());
    }

    private static long[] s6_addr$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t s6_addr[16]
     * }
     */
    public static long[] s6_addr$dimensions() {
        return s6_addr$DIMS;
    }
    private static final VarHandle s6_addr$ELEM_HANDLE = s6_addr$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t s6_addr[16]
     * }
     */
    public static byte s6_addr(MemorySegment struct, long index0) {
        return (byte)s6_addr$ELEM_HANDLE.get(struct, s6_addr$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t s6_addr[16]
     * }
     */
    public static void s6_addr(MemorySegment struct, long index0, byte fieldValue) {
        s6_addr$ELEM_HANDLE.set(struct, s6_addr$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

