// Generated by jextract

package com.github.auties00.cobalt.call.internal.transport.sctp.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sctp_initmsg {
 *     uint16_t sinit_num_ostreams;
 *     uint16_t sinit_max_instreams;
 *     uint16_t sinit_max_attempts;
 *     uint16_t sinit_max_init_timeo;
 * }
 * }
 */
public class sctp_initmsg {

    sctp_initmsg() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        UsrSctp.C_SHORT.withName("sinit_num_ostreams"),
        UsrSctp.C_SHORT.withName("sinit_max_instreams"),
        UsrSctp.C_SHORT.withName("sinit_max_attempts"),
        UsrSctp.C_SHORT.withName("sinit_max_init_timeo")
    ).withName("sctp_initmsg");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort sinit_num_ostreams$LAYOUT = (OfShort)$LAYOUT.select(groupElement("sinit_num_ostreams"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t sinit_num_ostreams
     * }
     */
    public static final OfShort sinit_num_ostreams$layout() {
        return sinit_num_ostreams$LAYOUT;
    }

    private static final long sinit_num_ostreams$OFFSET = $LAYOUT.byteOffset(groupElement("sinit_num_ostreams"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t sinit_num_ostreams
     * }
     */
    public static final long sinit_num_ostreams$offset() {
        return sinit_num_ostreams$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t sinit_num_ostreams
     * }
     */
    public static short sinit_num_ostreams(MemorySegment struct) {
        return struct.get(sinit_num_ostreams$LAYOUT, sinit_num_ostreams$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t sinit_num_ostreams
     * }
     */
    public static void sinit_num_ostreams(MemorySegment struct, short fieldValue) {
        struct.set(sinit_num_ostreams$LAYOUT, sinit_num_ostreams$OFFSET, fieldValue);
    }

    private static final OfShort sinit_max_instreams$LAYOUT = (OfShort)$LAYOUT.select(groupElement("sinit_max_instreams"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t sinit_max_instreams
     * }
     */
    public static final OfShort sinit_max_instreams$layout() {
        return sinit_max_instreams$LAYOUT;
    }

    private static final long sinit_max_instreams$OFFSET = $LAYOUT.byteOffset(groupElement("sinit_max_instreams"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t sinit_max_instreams
     * }
     */
    public static final long sinit_max_instreams$offset() {
        return sinit_max_instreams$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t sinit_max_instreams
     * }
     */
    public static short sinit_max_instreams(MemorySegment struct) {
        return struct.get(sinit_max_instreams$LAYOUT, sinit_max_instreams$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t sinit_max_instreams
     * }
     */
    public static void sinit_max_instreams(MemorySegment struct, short fieldValue) {
        struct.set(sinit_max_instreams$LAYOUT, sinit_max_instreams$OFFSET, fieldValue);
    }

    private static final OfShort sinit_max_attempts$LAYOUT = (OfShort)$LAYOUT.select(groupElement("sinit_max_attempts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t sinit_max_attempts
     * }
     */
    public static final OfShort sinit_max_attempts$layout() {
        return sinit_max_attempts$LAYOUT;
    }

    private static final long sinit_max_attempts$OFFSET = $LAYOUT.byteOffset(groupElement("sinit_max_attempts"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t sinit_max_attempts
     * }
     */
    public static final long sinit_max_attempts$offset() {
        return sinit_max_attempts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t sinit_max_attempts
     * }
     */
    public static short sinit_max_attempts(MemorySegment struct) {
        return struct.get(sinit_max_attempts$LAYOUT, sinit_max_attempts$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t sinit_max_attempts
     * }
     */
    public static void sinit_max_attempts(MemorySegment struct, short fieldValue) {
        struct.set(sinit_max_attempts$LAYOUT, sinit_max_attempts$OFFSET, fieldValue);
    }

    private static final OfShort sinit_max_init_timeo$LAYOUT = (OfShort)$LAYOUT.select(groupElement("sinit_max_init_timeo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t sinit_max_init_timeo
     * }
     */
    public static final OfShort sinit_max_init_timeo$layout() {
        return sinit_max_init_timeo$LAYOUT;
    }

    private static final long sinit_max_init_timeo$OFFSET = $LAYOUT.byteOffset(groupElement("sinit_max_init_timeo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t sinit_max_init_timeo
     * }
     */
    public static final long sinit_max_init_timeo$offset() {
        return sinit_max_init_timeo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t sinit_max_init_timeo
     * }
     */
    public static short sinit_max_init_timeo(MemorySegment struct) {
        return struct.get(sinit_max_init_timeo$LAYOUT, sinit_max_init_timeo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t sinit_max_init_timeo
     * }
     */
    public static void sinit_max_init_timeo(MemorySegment struct, short fieldValue) {
        struct.set(sinit_max_init_timeo$LAYOUT, sinit_max_init_timeo$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

