// Generated by jextract

package com.github.auties00.cobalt.call.internal.transport.sctp.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sctp_assoc_value {
 *     sctp_assoc_t assoc_id;
 *     uint32_t assoc_value;
 * }
 * }
 */
public class sctp_assoc_value {

    sctp_assoc_value() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        UsrSctp.C_INT.withName("assoc_id"),
        UsrSctp.C_INT.withName("assoc_value")
    ).withName("sctp_assoc_value");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt assoc_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("assoc_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * sctp_assoc_t assoc_id
     * }
     */
    public static final OfInt assoc_id$layout() {
        return assoc_id$LAYOUT;
    }

    private static final long assoc_id$OFFSET = $LAYOUT.byteOffset(groupElement("assoc_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * sctp_assoc_t assoc_id
     * }
     */
    public static final long assoc_id$offset() {
        return assoc_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * sctp_assoc_t assoc_id
     * }
     */
    public static int assoc_id(MemorySegment struct) {
        return struct.get(assoc_id$LAYOUT, assoc_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * sctp_assoc_t assoc_id
     * }
     */
    public static void assoc_id(MemorySegment struct, int fieldValue) {
        struct.set(assoc_id$LAYOUT, assoc_id$OFFSET, fieldValue);
    }

    private static final OfInt assoc_value$LAYOUT = (OfInt)$LAYOUT.select(groupElement("assoc_value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t assoc_value
     * }
     */
    public static final OfInt assoc_value$layout() {
        return assoc_value$LAYOUT;
    }

    private static final long assoc_value$OFFSET = $LAYOUT.byteOffset(groupElement("assoc_value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t assoc_value
     * }
     */
    public static final long assoc_value$offset() {
        return assoc_value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t assoc_value
     * }
     */
    public static int assoc_value(MemorySegment struct) {
        return struct.get(assoc_value$LAYOUT, assoc_value$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t assoc_value
     * }
     */
    public static void assoc_value(MemorySegment struct, int fieldValue) {
        struct.set(assoc_value$LAYOUT, assoc_value$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

