// Generated by jextract

package com.github.auties00.cobalt.call.internal.transport.sctp.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sockaddr_conn {
 *     uint16_t sconn_family;
 *     uint16_t sconn_port;
 *     void *sconn_addr;
 * }
 * }
 */
public class sockaddr_conn {

    sockaddr_conn() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        UsrSctp.C_SHORT.withName("sconn_family"),
        UsrSctp.C_SHORT.withName("sconn_port"),
        MemoryLayout.paddingLayout(4),
        UsrSctp.C_POINTER.withName("sconn_addr")
    ).withName("sockaddr_conn");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort sconn_family$LAYOUT = (OfShort)$LAYOUT.select(groupElement("sconn_family"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t sconn_family
     * }
     */
    public static final OfShort sconn_family$layout() {
        return sconn_family$LAYOUT;
    }

    private static final long sconn_family$OFFSET = $LAYOUT.byteOffset(groupElement("sconn_family"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t sconn_family
     * }
     */
    public static final long sconn_family$offset() {
        return sconn_family$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t sconn_family
     * }
     */
    public static short sconn_family(MemorySegment struct) {
        return struct.get(sconn_family$LAYOUT, sconn_family$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t sconn_family
     * }
     */
    public static void sconn_family(MemorySegment struct, short fieldValue) {
        struct.set(sconn_family$LAYOUT, sconn_family$OFFSET, fieldValue);
    }

    private static final OfShort sconn_port$LAYOUT = (OfShort)$LAYOUT.select(groupElement("sconn_port"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t sconn_port
     * }
     */
    public static final OfShort sconn_port$layout() {
        return sconn_port$LAYOUT;
    }

    private static final long sconn_port$OFFSET = $LAYOUT.byteOffset(groupElement("sconn_port"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t sconn_port
     * }
     */
    public static final long sconn_port$offset() {
        return sconn_port$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t sconn_port
     * }
     */
    public static short sconn_port(MemorySegment struct) {
        return struct.get(sconn_port$LAYOUT, sconn_port$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t sconn_port
     * }
     */
    public static void sconn_port(MemorySegment struct, short fieldValue) {
        struct.set(sconn_port$LAYOUT, sconn_port$OFFSET, fieldValue);
    }

    private static final AddressLayout sconn_addr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sconn_addr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *sconn_addr
     * }
     */
    public static final AddressLayout sconn_addr$layout() {
        return sconn_addr$LAYOUT;
    }

    private static final long sconn_addr$OFFSET = $LAYOUT.byteOffset(groupElement("sconn_addr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *sconn_addr
     * }
     */
    public static final long sconn_addr$offset() {
        return sconn_addr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *sconn_addr
     * }
     */
    public static MemorySegment sconn_addr(MemorySegment struct) {
        return struct.get(sconn_addr$LAYOUT, sconn_addr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *sconn_addr
     * }
     */
    public static void sconn_addr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(sconn_addr$LAYOUT, sconn_addr$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

