// Generated by jextract

package com.github.auties00.cobalt.call.internal.transport.sctp.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * int (*receive_cb)(struct socket *, union sctp_sockstore, void *, size_t, struct sctp_rcvinfo, int, void *)
 * }
 */
public final class usrsctp_socket$receive_cb {

    private usrsctp_socket$receive_cb() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3, MemorySegment _x4, int _x5, MemorySegment _x6);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        UsrSctp.C_INT,
        UsrSctp.C_POINTER,
        sctp_sockstore.layout(),
        UsrSctp.C_POINTER,
        UsrSctp.C_LONG_LONG,
        sctp_rcvinfo.layout(),
        UsrSctp.C_INT,
        UsrSctp.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = UsrSctp.upcallHandle(usrsctp_socket$receive_cb.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(usrsctp_socket$receive_cb.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3, MemorySegment _x4, int _x5, MemorySegment _x6) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

