// Generated by jextract

package com.github.auties00.cobalt.call.internal.video.vpx.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct vpx_codec_ctx {
 *     const char *name;
 *     vpx_codec_iface_t *iface;
 *     vpx_codec_err_t err;
 *     const char *err_detail;
 *     vpx_codec_flags_t init_flags;
 *     union {
 *         const struct vpx_codec_dec_cfg *dec;
 *         const struct vpx_codec_enc_cfg *enc;
 *         const void *raw;
 *     } config;
 *     vpx_codec_priv_t *priv;
 * }
 * }
 */
public class vpx_codec_ctx {

    vpx_codec_ctx() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        LibVpx.C_POINTER.withName("name"),
        LibVpx.C_POINTER.withName("iface"),
        LibVpx.C_INT.withName("err"),
        MemoryLayout.paddingLayout(4),
        LibVpx.C_POINTER.withName("err_detail"),
        LibVpx.C_LONG.withName("init_flags"),
        MemoryLayout.paddingLayout(4),
        vpx_codec_ctx.config.layout().withName("config"),
        LibVpx.C_POINTER.withName("priv")
    ).withName("vpx_codec_ctx");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = $LAYOUT.byteOffset(groupElement("name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    private static final AddressLayout iface$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("iface"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_codec_iface_t *iface
     * }
     */
    public static final AddressLayout iface$layout() {
        return iface$LAYOUT;
    }

    private static final long iface$OFFSET = $LAYOUT.byteOffset(groupElement("iface"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_codec_iface_t *iface
     * }
     */
    public static final long iface$offset() {
        return iface$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_codec_iface_t *iface
     * }
     */
    public static MemorySegment iface(MemorySegment struct) {
        return struct.get(iface$LAYOUT, iface$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_codec_iface_t *iface
     * }
     */
    public static void iface(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(iface$LAYOUT, iface$OFFSET, fieldValue);
    }

    private static final OfInt err$LAYOUT = (OfInt)$LAYOUT.select(groupElement("err"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_codec_err_t err
     * }
     */
    public static final OfInt err$layout() {
        return err$LAYOUT;
    }

    private static final long err$OFFSET = $LAYOUT.byteOffset(groupElement("err"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_codec_err_t err
     * }
     */
    public static final long err$offset() {
        return err$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_codec_err_t err
     * }
     */
    public static int err(MemorySegment struct) {
        return struct.get(err$LAYOUT, err$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_codec_err_t err
     * }
     */
    public static void err(MemorySegment struct, int fieldValue) {
        struct.set(err$LAYOUT, err$OFFSET, fieldValue);
    }

    private static final AddressLayout err_detail$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("err_detail"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *err_detail
     * }
     */
    public static final AddressLayout err_detail$layout() {
        return err_detail$LAYOUT;
    }

    private static final long err_detail$OFFSET = $LAYOUT.byteOffset(groupElement("err_detail"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *err_detail
     * }
     */
    public static final long err_detail$offset() {
        return err_detail$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *err_detail
     * }
     */
    public static MemorySegment err_detail(MemorySegment struct) {
        return struct.get(err_detail$LAYOUT, err_detail$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *err_detail
     * }
     */
    public static void err_detail(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(err_detail$LAYOUT, err_detail$OFFSET, fieldValue);
    }

    private static final OfInt init_flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("init_flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_codec_flags_t init_flags
     * }
     */
    public static final OfInt init_flags$layout() {
        return init_flags$LAYOUT;
    }

    private static final long init_flags$OFFSET = $LAYOUT.byteOffset(groupElement("init_flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_codec_flags_t init_flags
     * }
     */
    public static final long init_flags$offset() {
        return init_flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_codec_flags_t init_flags
     * }
     */
    public static int init_flags(MemorySegment struct) {
        return struct.get(init_flags$LAYOUT, init_flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_codec_flags_t init_flags
     * }
     */
    public static void init_flags(MemorySegment struct, int fieldValue) {
        struct.set(init_flags$LAYOUT, init_flags$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     const struct vpx_codec_dec_cfg *dec;
     *     const struct vpx_codec_enc_cfg *enc;
     *     const void *raw;
     * }
     * }
     */
    public static class config {

        config() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            LibVpx.C_POINTER.withName("dec"),
            LibVpx.C_POINTER.withName("enc"),
            LibVpx.C_POINTER.withName("raw")
        ).withName("$anon$206:3");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final AddressLayout dec$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("dec"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * const struct vpx_codec_dec_cfg *dec
         * }
         */
        public static final AddressLayout dec$layout() {
            return dec$LAYOUT;
        }

        private static final long dec$OFFSET = $LAYOUT.byteOffset(groupElement("dec"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * const struct vpx_codec_dec_cfg *dec
         * }
         */
        public static final long dec$offset() {
            return dec$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * const struct vpx_codec_dec_cfg *dec
         * }
         */
        public static MemorySegment dec(MemorySegment union) {
            return union.get(dec$LAYOUT, dec$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * const struct vpx_codec_dec_cfg *dec
         * }
         */
        public static void dec(MemorySegment union, MemorySegment fieldValue) {
            union.set(dec$LAYOUT, dec$OFFSET, fieldValue);
        }

        private static final AddressLayout enc$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("enc"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * const struct vpx_codec_enc_cfg *enc
         * }
         */
        public static final AddressLayout enc$layout() {
            return enc$LAYOUT;
        }

        private static final long enc$OFFSET = $LAYOUT.byteOffset(groupElement("enc"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * const struct vpx_codec_enc_cfg *enc
         * }
         */
        public static final long enc$offset() {
            return enc$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * const struct vpx_codec_enc_cfg *enc
         * }
         */
        public static MemorySegment enc(MemorySegment union) {
            return union.get(enc$LAYOUT, enc$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * const struct vpx_codec_enc_cfg *enc
         * }
         */
        public static void enc(MemorySegment union, MemorySegment fieldValue) {
            union.set(enc$LAYOUT, enc$OFFSET, fieldValue);
        }

        private static final AddressLayout raw$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("raw"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * const void *raw
         * }
         */
        public static final AddressLayout raw$layout() {
            return raw$LAYOUT;
        }

        private static final long raw$OFFSET = $LAYOUT.byteOffset(groupElement("raw"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * const void *raw
         * }
         */
        public static final long raw$offset() {
            return raw$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * const void *raw
         * }
         */
        public static MemorySegment raw(MemorySegment union) {
            return union.get(raw$LAYOUT, raw$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * const void *raw
         * }
         */
        public static void raw(MemorySegment union, MemorySegment fieldValue) {
            union.set(raw$LAYOUT, raw$OFFSET, fieldValue);
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout config$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("config"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     const struct vpx_codec_dec_cfg *dec;
     *     const struct vpx_codec_enc_cfg *enc;
     *     const void *raw;
     * } config
     * }
     */
    public static final GroupLayout config$layout() {
        return config$LAYOUT;
    }

    private static final long config$OFFSET = $LAYOUT.byteOffset(groupElement("config"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     const struct vpx_codec_dec_cfg *dec;
     *     const struct vpx_codec_enc_cfg *enc;
     *     const void *raw;
     * } config
     * }
     */
    public static final long config$offset() {
        return config$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     const struct vpx_codec_dec_cfg *dec;
     *     const struct vpx_codec_enc_cfg *enc;
     *     const void *raw;
     * } config
     * }
     */
    public static MemorySegment config(MemorySegment struct) {
        return struct.asSlice(config$OFFSET, config$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     const struct vpx_codec_dec_cfg *dec;
     *     const struct vpx_codec_enc_cfg *enc;
     *     const void *raw;
     * } config
     * }
     */
    public static void config(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, config$OFFSET, config$LAYOUT.byteSize());
    }

    private static final AddressLayout priv$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("priv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vpx_codec_priv_t *priv
     * }
     */
    public static final AddressLayout priv$layout() {
        return priv$LAYOUT;
    }

    private static final long priv$OFFSET = $LAYOUT.byteOffset(groupElement("priv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vpx_codec_priv_t *priv
     * }
     */
    public static final long priv$offset() {
        return priv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vpx_codec_priv_t *priv
     * }
     */
    public static MemorySegment priv(MemorySegment struct) {
        return struct.get(priv$LAYOUT, priv$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vpx_codec_priv_t *priv
     * }
     */
    public static void priv(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(priv$LAYOUT, priv$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

