package com.github.auties00.cobalt.node.mex.json.community;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX mutation operation for the {@code TransferCommunityOwnership} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface TransferCommunityOwnershipMex extends MexJsonOperation permits TransferCommunityOwnershipMex.Request, TransferCommunityOwnershipMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "29643783178598899";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements TransferCommunityOwnershipMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("input");
                writer.writeColon();
                writer.writeString(input);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements TransferCommunityOwnershipMex {
        private final String groupId;
        private final String lidMigrationStateAddressingMode;

        private Response(String groupId, String lidMigrationStateAddressingMode) {
            this.groupId = groupId;
            this.lidMigrationStateAddressingMode = lidMigrationStateAddressingMode;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code group_id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> groupId() {
            return Optional.ofNullable(groupId);
        }

        /**
         * Returns the {@code lid_migration_state.addressing_mode} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> lidMigrationStateAddressingMode() {
            return Optional.ofNullable(lidMigrationStateAddressingMode);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_group_update_users_role");
            if (root == null) {
                return Optional.empty();
            }

            var groupId = root.getString("group_id");
            var lidMigrationState = root.getJSONObject("lid_migration_state");
            var lidMigrationStateAddressingMode = lidMigrationState != null ? lidMigrationState.getString("addressing_mode") : null;

            return Optional.of(new Response(groupId, lidMigrationStateAddressingMode));
        }
    }
}
