package com.github.auties00.cobalt.calls2.core.participant;

import com.github.auties00.cobalt.calls2.common.CallDeviceJid;
import com.github.auties00.cobalt.calls2.common.VideoDecoderCapability;

import java.util.EnumSet;
import java.util.Objects;
import java.util.OptionalInt;
import java.util.Set;

/**
 * Holds the per-device state the engine tracks for one device of a multi-device call
 * participant.
 *
 * <p>A participant may join a call from several devices at once; the engine keeps one of
 * these records per device. Each record carries the device's {@link CallDeviceJid}, the
 * numeric participant/device id the server assigns ({@code pid}), the device's
 * advertised video-decode capabilities, a per-device video-enabled flag the engine
 * toggles as the device starts and stops its camera, the device's generated SSRC set, and
 * a per-device server-state code used when the device is serialized back into a membership
 * stanza.
 *
 * <p>This record is mutable: the engine flips the {@linkplain #videoEnabled() video-enabled
 * flag}, refreshes the {@linkplain #decoderCapabilities() decode capabilities} when a new
 * capability descriptor arrives, and fills the {@linkplain #mainSsrc() SSRC set} once it is
 * generated. The SSRC set is not generated here; it is computed by the secure-SSRC
 * generator from this device's JID-bound identifiers and installed through
 * {@link #ssrcs(int, int, int, int, int)}. Until the SSRC set is installed the SSRC
 * accessors report absent.
 *
 * <p>This class is not thread-safe; the engine mutates a device info only while holding
 * the membership lock that guards the owning {@link CallParticipant}.
 *
 * @implNote This implementation composes the {@code device_info} sub-record (stride
 * {@code 0x114} = 276 bytes) of the wa-voip WASM module {@code ff-tScznZ8P}
 * ({@code call_participant.cc} / {@code call_participant_media.cc}): the device JID
 * (word {@code 0x137}), the parsed capability object (word {@code +1}) and its version
 * (word {@code +2}), the per-device video-enabled flag ({@code +0x69}), the SSRC set
 * generated by {@code call_generate_device_ssrc} (fn10901) into the device's SSRC fields,
 * and the per-device server state ({@code +0x50}) the membership remove path
 * ({@code voip_signaling_call_remove_participant}, fn10823) sets to
 * {@code kParticipantStateInvalid}. The native struct inlines the first device at
 * {@code call_participant+0x4dc}; additional devices live in a heap array. The decode
 * capability is the bitmask {@code wa_call_device_info_update_vid_dec_cap} (fn10873)
 * parses from the capability string, defaulting to H264 on parse failure.
 */
public final class CallDeviceInfo {
    /**
     * Holds the sentinel the engine uses for an unassigned SSRC.
     *
     * <p>An SSRC field holds this value until the secure-SSRC generator fills it; the SSRC
     * accessors report absent while a field equals this sentinel.
     */
    public static final int UNASSIGNED_SSRC = 0;

    /**
     * Holds the sentinel the engine uses for an unassigned server-assigned participant id.
     *
     * <p>The {@code pid} field holds this value until the server assigns a participant id.
     */
    public static final int UNASSIGNED_PID = -1;

    /**
     * Holds this device's JID.
     */
    private final CallDeviceJid deviceJid;

    /**
     * Holds the numeric participant/device id the server assigns, or {@value #UNASSIGNED_PID}
     * when none has been assigned.
     */
    private int pid;

    /**
     * Holds the video-decode codecs this device has advertised.
     */
    private Set<VideoDecoderCapability> decoderCapabilities;

    /**
     * Holds whether this device currently has its outbound video enabled.
     */
    private boolean videoEnabled;

    /**
     * Holds the per-device server-state code used when this device is serialized into a
     * membership stanza.
     */
    private int serverState;

    /**
     * Holds this device's main RTP SSRC, or {@value #UNASSIGNED_SSRC} until generated.
     */
    private int mainSsrc;

    /**
     * Holds this device's app-data DataChannel SSRC, or {@value #UNASSIGNED_SSRC} until
     * generated.
     */
    private int appDataSsrc;

    /**
     * Holds this device's IMU-data SSRC, or {@value #UNASSIGNED_SSRC} until generated.
     */
    private int imuDataSsrc;

    /**
     * Holds this device's hop-by-hop FEC transmit SSRC, or {@value #UNASSIGNED_SSRC} until
     * generated.
     */
    private int hopByHopFecTxSsrc;

    /**
     * Holds this device's hop-by-hop FEC receive SSRC, or {@value #UNASSIGNED_SSRC} until
     * generated.
     */
    private int hopByHopFecRxSsrc;

    /**
     * Constructs a device info for the given device JID with no capabilities, video
     * disabled, an unassigned participant id and server state, and an unassigned SSRC set.
     *
     * @param deviceJid this device's JID; never {@code null}
     * @throws NullPointerException if {@code deviceJid} is {@code null}
     */
    public CallDeviceInfo(CallDeviceJid deviceJid) {
        this.deviceJid = Objects.requireNonNull(deviceJid, "deviceJid cannot be null");
        this.pid = UNASSIGNED_PID;
        this.decoderCapabilities = EnumSet.noneOf(VideoDecoderCapability.class);
        this.videoEnabled = false;
        this.serverState = CallParticipantState.INVALID.code();
        this.mainSsrc = UNASSIGNED_SSRC;
        this.appDataSsrc = UNASSIGNED_SSRC;
        this.imuDataSsrc = UNASSIGNED_SSRC;
        this.hopByHopFecTxSsrc = UNASSIGNED_SSRC;
        this.hopByHopFecRxSsrc = UNASSIGNED_SSRC;
    }

    /**
     * Returns this device's JID.
     *
     * @return the device JID; never {@code null}
     */
    public CallDeviceJid deviceJid() {
        return deviceJid;
    }

    /**
     * Returns the numeric participant/device id the server assigned to this device.
     *
     * @return the assigned participant id, or {@link OptionalInt#empty()} if none has been
     *         assigned
     */
    public OptionalInt pid() {
        return pid == UNASSIGNED_PID ? OptionalInt.empty() : OptionalInt.of(pid);
    }

    /**
     * Sets the numeric participant/device id the server assigned to this device.
     *
     * @param pid the participant id to record
     * @return this device info
     */
    public CallDeviceInfo pid(int pid) {
        this.pid = pid;
        return this;
    }

    /**
     * Returns the video-decode codecs this device has advertised.
     *
     * <p>The returned set is an unmodifiable snapshot; it is empty until a capability
     * descriptor has been recorded through {@link #decoderCapabilities(Set)}.
     *
     * @return an unmodifiable view of the advertised decode codecs
     */
    public Set<VideoDecoderCapability> decoderCapabilities() {
        return Set.copyOf(decoderCapabilities);
    }

    /**
     * Records the video-decode codecs this device has advertised.
     *
     * <p>The supplied set is copied defensively; callers typically pass the result of
     * {@link VideoDecoderCapability#parse(String)} over the device's capability descriptor,
     * which already applies the H264 fallback on a malformed descriptor.
     *
     * @param decoderCapabilities the advertised decode codecs; never {@code null}
     * @return this device info
     * @throws NullPointerException if {@code decoderCapabilities} is {@code null}
     */
    public CallDeviceInfo decoderCapabilities(Set<VideoDecoderCapability> decoderCapabilities) {
        Objects.requireNonNull(decoderCapabilities, "decoderCapabilities cannot be null");
        this.decoderCapabilities = decoderCapabilities.isEmpty()
                ? EnumSet.noneOf(VideoDecoderCapability.class)
                : EnumSet.copyOf(decoderCapabilities);
        return this;
    }

    /**
     * Returns whether this device currently has its outbound video enabled.
     *
     * @return {@code true} if the device's video is enabled
     */
    public boolean videoEnabled() {
        return videoEnabled;
    }

    /**
     * Sets whether this device currently has its outbound video enabled.
     *
     * @param videoEnabled {@code true} to mark the device's video enabled
     * @return this device info
     */
    public CallDeviceInfo videoEnabled(boolean videoEnabled) {
        this.videoEnabled = videoEnabled;
        return this;
    }

    /**
     * Returns the per-device server-state code used when this device is serialized into a
     * membership stanza.
     *
     * @return the server-state code
     */
    public int serverState() {
        return serverState;
    }

    /**
     * Sets the per-device server-state code used when this device is serialized into a
     * membership stanza.
     *
     * <p>The membership remove path sets this to {@link CallParticipantState#INVALID}'s
     * code to mark the device removed.
     *
     * @param serverState the server-state code to record
     * @return this device info
     */
    public CallDeviceInfo serverState(int serverState) {
        this.serverState = serverState;
        return this;
    }

    /**
     * Returns this device's main RTP SSRC.
     *
     * @return the main SSRC, or {@link OptionalInt#empty()} if the SSRC set has not been
     *         generated
     */
    public OptionalInt mainSsrc() {
        return mainSsrc == UNASSIGNED_SSRC ? OptionalInt.empty() : OptionalInt.of(mainSsrc);
    }

    /**
     * Returns this device's app-data DataChannel SSRC.
     *
     * @return the app-data SSRC, or {@link OptionalInt#empty()} if the SSRC set has not
     *         been generated
     */
    public OptionalInt appDataSsrc() {
        return appDataSsrc == UNASSIGNED_SSRC ? OptionalInt.empty() : OptionalInt.of(appDataSsrc);
    }

    /**
     * Returns this device's IMU-data SSRC.
     *
     * @return the IMU-data SSRC, or {@link OptionalInt#empty()} if the SSRC set has not
     *         been generated
     */
    public OptionalInt imuDataSsrc() {
        return imuDataSsrc == UNASSIGNED_SSRC ? OptionalInt.empty() : OptionalInt.of(imuDataSsrc);
    }

    /**
     * Returns this device's hop-by-hop FEC transmit SSRC.
     *
     * @return the hop-by-hop FEC transmit SSRC, or {@link OptionalInt#empty()} if the SSRC
     *         set has not been generated
     */
    public OptionalInt hopByHopFecTxSsrc() {
        return hopByHopFecTxSsrc == UNASSIGNED_SSRC ? OptionalInt.empty() : OptionalInt.of(hopByHopFecTxSsrc);
    }

    /**
     * Returns this device's hop-by-hop FEC receive SSRC.
     *
     * @return the hop-by-hop FEC receive SSRC, or {@link OptionalInt#empty()} if the SSRC
     *         set has not been generated
     */
    public OptionalInt hopByHopFecRxSsrc() {
        return hopByHopFecRxSsrc == UNASSIGNED_SSRC ? OptionalInt.empty() : OptionalInt.of(hopByHopFecRxSsrc);
    }

    /**
     * Installs the device-wide SSRC set generated for this device.
     *
     * <p>This records the main RTP SSRC plus the app-data, IMU-data, and hop-by-hop FEC
     * transmit and receive SSRCs. The per-stream video and screenshare SSRCs are held by
     * the participant media object rather than per device, so they are not installed here.
     *
     * @implNote This implementation receives the SSRCs that
     * {@code call_generate_device_ssrc} (fn10901) writes per device: the main SSRC, the
     * app-data SSRC (media-type {@code 6}, fn10903), the IMU-data SSRC (media-type
     * {@code 10}, fn10904), and the hop-by-hop FEC transmit and receive SSRCs (media-types
     * {@code 7} and {@code 8}). The SSRCs themselves are produced by the secure-SSRC
     * generator owned by the call crypto layer, not by this holder.
     * @param mainSsrc           the main RTP SSRC
     * @param appDataSsrc        the app-data DataChannel SSRC
     * @param imuDataSsrc        the IMU-data SSRC
     * @param hopByHopFecTxSsrc  the hop-by-hop FEC transmit SSRC
     * @param hopByHopFecRxSsrc  the hop-by-hop FEC receive SSRC
     * @return this device info
     */
    public CallDeviceInfo ssrcs(int mainSsrc, int appDataSsrc, int imuDataSsrc, int hopByHopFecTxSsrc, int hopByHopFecRxSsrc) {
        this.mainSsrc = mainSsrc;
        this.appDataSsrc = appDataSsrc;
        this.imuDataSsrc = imuDataSsrc;
        this.hopByHopFecTxSsrc = hopByHopFecTxSsrc;
        this.hopByHopFecRxSsrc = hopByHopFecRxSsrc;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        return obj == this || (obj instanceof CallDeviceInfo that && this.deviceJid.equals(that.deviceJid));
    }

    @Override
    public int hashCode() {
        return deviceJid.hashCode();
    }

    @Override
    public String toString() {
        return "CallDeviceInfo[deviceJid=" + deviceJid
                + ", pid=" + pid
                + ", videoEnabled=" + videoEnabled
                + ", serverState=" + serverState
                + ", decoderCapabilities=" + decoderCapabilities
                + ']';
    }
}
