// Generated by jextract

package com.github.auties00.cobalt.store.linked.protobuf.persistent.mdbx.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;

public class Mdbx extends Mdbx$shared {

    Mdbx() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int MDBX_ENV_DEFAULTS = (int)0L;
    /**
     * {@snippet lang=c :
     * enum MDBX_env_flags.MDBX_ENV_DEFAULTS = 0
     * }
     */
    public static int MDBX_ENV_DEFAULTS() {
        return MDBX_ENV_DEFAULTS;
    }
    private static final int MDBX_NOSTICKYTHREADS = (int)2097152L;
    /**
     * {@snippet lang=c :
     * enum MDBX_env_flags.MDBX_NOSTICKYTHREADS = 2097152
     * }
     */
    public static int MDBX_NOSTICKYTHREADS() {
        return MDBX_NOSTICKYTHREADS;
    }
    private static final int MDBX_LIFORECLAIM = (int)67108864L;
    /**
     * {@snippet lang=c :
     * enum MDBX_env_flags.MDBX_LIFORECLAIM = 67108864
     * }
     */
    public static int MDBX_LIFORECLAIM() {
        return MDBX_LIFORECLAIM;
    }
    private static final int MDBX_TXN_READWRITE = (int)0L;
    /**
     * {@snippet lang=c :
     * enum MDBX_txn_flags.MDBX_TXN_READWRITE = 0
     * }
     */
    public static int MDBX_TXN_READWRITE() {
        return MDBX_TXN_READWRITE;
    }
    private static final int MDBX_TXN_RDONLY = (int)131072L;
    /**
     * {@snippet lang=c :
     * enum MDBX_txn_flags.MDBX_TXN_RDONLY = 131072
     * }
     */
    public static int MDBX_TXN_RDONLY() {
        return MDBX_TXN_RDONLY;
    }
    private static final int MDBX_DB_DEFAULTS = (int)0L;
    /**
     * {@snippet lang=c :
     * enum MDBX_db_flags.MDBX_DB_DEFAULTS = 0
     * }
     */
    public static int MDBX_DB_DEFAULTS() {
        return MDBX_DB_DEFAULTS;
    }
    private static final int MDBX_CREATE = (int)262144L;
    /**
     * {@snippet lang=c :
     * enum MDBX_db_flags.MDBX_CREATE = 262144
     * }
     */
    public static int MDBX_CREATE() {
        return MDBX_CREATE;
    }
    private static final int MDBX_UPSERT = (int)0L;
    /**
     * {@snippet lang=c :
     * enum MDBX_put_flags.MDBX_UPSERT = 0
     * }
     */
    public static int MDBX_UPSERT() {
        return MDBX_UPSERT;
    }
    private static final int MDBX_RESERVE = (int)65536L;
    /**
     * {@snippet lang=c :
     * enum MDBX_put_flags.MDBX_RESERVE = 65536
     * }
     */
    public static int MDBX_RESERVE() {
        return MDBX_RESERVE;
    }
    private static final int MDBX_FIRST = (int)0L;
    /**
     * {@snippet lang=c :
     * enum MDBX_cursor_op.MDBX_FIRST = 0
     * }
     */
    public static int MDBX_FIRST() {
        return MDBX_FIRST;
    }
    private static final int MDBX_GET_CURRENT = (int)4L;
    /**
     * {@snippet lang=c :
     * enum MDBX_cursor_op.MDBX_GET_CURRENT = 4
     * }
     */
    public static int MDBX_GET_CURRENT() {
        return MDBX_GET_CURRENT;
    }
    private static final int MDBX_LAST = (int)6L;
    /**
     * {@snippet lang=c :
     * enum MDBX_cursor_op.MDBX_LAST = 6
     * }
     */
    public static int MDBX_LAST() {
        return MDBX_LAST;
    }
    private static final int MDBX_NEXT = (int)8L;
    /**
     * {@snippet lang=c :
     * enum MDBX_cursor_op.MDBX_NEXT = 8
     * }
     */
    public static int MDBX_NEXT() {
        return MDBX_NEXT;
    }
    private static final int MDBX_PREV = (int)12L;
    /**
     * {@snippet lang=c :
     * enum MDBX_cursor_op.MDBX_PREV = 12
     * }
     */
    public static int MDBX_PREV() {
        return MDBX_PREV;
    }
    private static final int MDBX_SET_RANGE = (int)17L;
    /**
     * {@snippet lang=c :
     * enum MDBX_cursor_op.MDBX_SET_RANGE = 17
     * }
     */
    public static int MDBX_SET_RANGE() {
        return MDBX_SET_RANGE;
    }
    private static final int MDBX_SUCCESS = (int)0L;
    /**
     * {@snippet lang=c :
     * enum MDBX_error.MDBX_SUCCESS = 0
     * }
     */
    public static int MDBX_SUCCESS() {
        return MDBX_SUCCESS;
    }
    private static final int MDBX_RESULT_TRUE = (int)-1L;
    /**
     * {@snippet lang=c :
     * enum MDBX_error.MDBX_RESULT_TRUE = -1
     * }
     */
    public static int MDBX_RESULT_TRUE() {
        return MDBX_RESULT_TRUE;
    }
    private static final int MDBX_NOTFOUND = (int)-30798L;
    /**
     * {@snippet lang=c :
     * enum MDBX_error.MDBX_NOTFOUND = -30798
     * }
     */
    public static int MDBX_NOTFOUND() {
        return MDBX_NOTFOUND;
    }
    private static final int MDBX_MAP_FULL = (int)-30792L;
    /**
     * {@snippet lang=c :
     * enum MDBX_error.MDBX_MAP_FULL = -30792
     * }
     */
    public static int MDBX_MAP_FULL() {
        return MDBX_MAP_FULL;
    }
    private static final int MDBX_TXN_FULL = (int)-30788L;
    /**
     * {@snippet lang=c :
     * enum MDBX_error.MDBX_TXN_FULL = -30788
     * }
     */
    public static int MDBX_TXN_FULL() {
        return MDBX_TXN_FULL;
    }
    private static final int MDBX_UNABLE_EXTEND_MAPSIZE = (int)-30785L;
    /**
     * {@snippet lang=c :
     * enum MDBX_error.MDBX_UNABLE_EXTEND_MAPSIZE = -30785
     * }
     */
    public static int MDBX_UNABLE_EXTEND_MAPSIZE() {
        return MDBX_UNABLE_EXTEND_MAPSIZE;
    }

    private static class mdbx_strerror {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_POINTER,
            Mdbx.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_strerror");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *mdbx_strerror(int errnum)
     * }
     */
    public static FunctionDescriptor mdbx_strerror$descriptor() {
        return mdbx_strerror.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *mdbx_strerror(int errnum)
     * }
     */
    public static MethodHandle mdbx_strerror$handle() {
        return mdbx_strerror.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *mdbx_strerror(int errnum)
     * }
     */
    public static MemorySegment mdbx_strerror$address() {
        return mdbx_strerror.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *mdbx_strerror(int errnum)
     * }
     */
    public static MemorySegment mdbx_strerror(int errnum) {
        var mh$ = mdbx_strerror.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_strerror", errnum);
            }
            return (MemorySegment)mh$.invokeExact(errnum);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_env_create {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_env_create");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_env_create(MDBX_env **penv)
     * }
     */
    public static FunctionDescriptor mdbx_env_create$descriptor() {
        return mdbx_env_create.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_env_create(MDBX_env **penv)
     * }
     */
    public static MethodHandle mdbx_env_create$handle() {
        return mdbx_env_create.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_env_create(MDBX_env **penv)
     * }
     */
    public static MemorySegment mdbx_env_create$address() {
        return mdbx_env_create.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_env_create(MDBX_env **penv)
     * }
     */
    public static int mdbx_env_create(MemorySegment penv) {
        var mh$ = mdbx_env_create.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_env_create", penv);
            }
            return (int)mh$.invokeExact(penv);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int MDBX_opt_max_db = (int)0L;
    /**
     * {@snippet lang=c :
     * enum MDBX_option.MDBX_opt_max_db = 0
     * }
     */
    public static int MDBX_opt_max_db() {
        return MDBX_opt_max_db;
    }
    private static final int MDBX_opt_max_readers = (int)1L;
    /**
     * {@snippet lang=c :
     * enum MDBX_option.MDBX_opt_max_readers = 1
     * }
     */
    public static int MDBX_opt_max_readers() {
        return MDBX_opt_max_readers;
    }

    private static class mdbx_env_set_option {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_INT,
            Mdbx.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_env_set_option");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_env_set_option(MDBX_env *env, const MDBX_option_t option, uint64_t value)
     * }
     */
    public static FunctionDescriptor mdbx_env_set_option$descriptor() {
        return mdbx_env_set_option.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_env_set_option(MDBX_env *env, const MDBX_option_t option, uint64_t value)
     * }
     */
    public static MethodHandle mdbx_env_set_option$handle() {
        return mdbx_env_set_option.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_env_set_option(MDBX_env *env, const MDBX_option_t option, uint64_t value)
     * }
     */
    public static MemorySegment mdbx_env_set_option$address() {
        return mdbx_env_set_option.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_env_set_option(MDBX_env *env, const MDBX_option_t option, uint64_t value)
     * }
     */
    public static int mdbx_env_set_option(MemorySegment env, int option, long value) {
        var mh$ = mdbx_env_set_option.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_env_set_option", env, option, value);
            }
            return (int)mh$.invokeExact(env, option, value);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_env_close_ex {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_BOOL
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_env_close_ex");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_env_close_ex(MDBX_env *env, _Bool dont_sync)
     * }
     */
    public static FunctionDescriptor mdbx_env_close_ex$descriptor() {
        return mdbx_env_close_ex.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_env_close_ex(MDBX_env *env, _Bool dont_sync)
     * }
     */
    public static MethodHandle mdbx_env_close_ex$handle() {
        return mdbx_env_close_ex.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_env_close_ex(MDBX_env *env, _Bool dont_sync)
     * }
     */
    public static MemorySegment mdbx_env_close_ex$address() {
        return mdbx_env_close_ex.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_env_close_ex(MDBX_env *env, _Bool dont_sync)
     * }
     */
    public static int mdbx_env_close_ex(MemorySegment env, boolean dont_sync) {
        var mh$ = mdbx_env_close_ex.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_env_close_ex", env, dont_sync);
            }
            return (int)mh$.invokeExact(env, dont_sync);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_env_set_geometry {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_LONG_LONG,
            Mdbx.C_LONG_LONG,
            Mdbx.C_LONG_LONG,
            Mdbx.C_LONG_LONG,
            Mdbx.C_LONG_LONG,
            Mdbx.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_env_set_geometry");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_env_set_geometry(MDBX_env *env, intptr_t size_lower, intptr_t size_now, intptr_t size_upper, intptr_t growth_step, intptr_t shrink_threshold, intptr_t pagesize)
     * }
     */
    public static FunctionDescriptor mdbx_env_set_geometry$descriptor() {
        return mdbx_env_set_geometry.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_env_set_geometry(MDBX_env *env, intptr_t size_lower, intptr_t size_now, intptr_t size_upper, intptr_t growth_step, intptr_t shrink_threshold, intptr_t pagesize)
     * }
     */
    public static MethodHandle mdbx_env_set_geometry$handle() {
        return mdbx_env_set_geometry.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_env_set_geometry(MDBX_env *env, intptr_t size_lower, intptr_t size_now, intptr_t size_upper, intptr_t growth_step, intptr_t shrink_threshold, intptr_t pagesize)
     * }
     */
    public static MemorySegment mdbx_env_set_geometry$address() {
        return mdbx_env_set_geometry.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_env_set_geometry(MDBX_env *env, intptr_t size_lower, intptr_t size_now, intptr_t size_upper, intptr_t growth_step, intptr_t shrink_threshold, intptr_t pagesize)
     * }
     */
    public static int mdbx_env_set_geometry(MemorySegment env, long size_lower, long size_now, long size_upper, long growth_step, long shrink_threshold, long pagesize) {
        var mh$ = mdbx_env_set_geometry.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_env_set_geometry", env, size_lower, size_now, size_upper, growth_step, shrink_threshold, pagesize);
            }
            return (int)mh$.invokeExact(env, size_lower, size_now, size_upper, growth_step, shrink_threshold, pagesize);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_txn_begin_ex {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_POINTER,
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_txn_begin_ex");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_txn_begin_ex(MDBX_env *env, MDBX_txn *parent, MDBX_txn_flags_t flags, MDBX_txn **txn, void *context)
     * }
     */
    public static FunctionDescriptor mdbx_txn_begin_ex$descriptor() {
        return mdbx_txn_begin_ex.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_txn_begin_ex(MDBX_env *env, MDBX_txn *parent, MDBX_txn_flags_t flags, MDBX_txn **txn, void *context)
     * }
     */
    public static MethodHandle mdbx_txn_begin_ex$handle() {
        return mdbx_txn_begin_ex.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_txn_begin_ex(MDBX_env *env, MDBX_txn *parent, MDBX_txn_flags_t flags, MDBX_txn **txn, void *context)
     * }
     */
    public static MemorySegment mdbx_txn_begin_ex$address() {
        return mdbx_txn_begin_ex.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_txn_begin_ex(MDBX_env *env, MDBX_txn *parent, MDBX_txn_flags_t flags, MDBX_txn **txn, void *context)
     * }
     */
    public static int mdbx_txn_begin_ex(MemorySegment env, MemorySegment parent, int flags, MemorySegment txn, MemorySegment context) {
        var mh$ = mdbx_txn_begin_ex.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_txn_begin_ex", env, parent, flags, txn, context);
            }
            return (int)mh$.invokeExact(env, parent, flags, txn, context);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_txn_commit_ex {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_txn_commit_ex");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_txn_commit_ex(MDBX_txn *txn, MDBX_commit_latency *latency)
     * }
     */
    public static FunctionDescriptor mdbx_txn_commit_ex$descriptor() {
        return mdbx_txn_commit_ex.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_txn_commit_ex(MDBX_txn *txn, MDBX_commit_latency *latency)
     * }
     */
    public static MethodHandle mdbx_txn_commit_ex$handle() {
        return mdbx_txn_commit_ex.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_txn_commit_ex(MDBX_txn *txn, MDBX_commit_latency *latency)
     * }
     */
    public static MemorySegment mdbx_txn_commit_ex$address() {
        return mdbx_txn_commit_ex.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_txn_commit_ex(MDBX_txn *txn, MDBX_commit_latency *latency)
     * }
     */
    public static int mdbx_txn_commit_ex(MemorySegment txn, MemorySegment latency) {
        var mh$ = mdbx_txn_commit_ex.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_txn_commit_ex", txn, latency);
            }
            return (int)mh$.invokeExact(txn, latency);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_txn_abort_ex {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_txn_abort_ex");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_txn_abort_ex(MDBX_txn *txn, MDBX_commit_latency *latency)
     * }
     */
    public static FunctionDescriptor mdbx_txn_abort_ex$descriptor() {
        return mdbx_txn_abort_ex.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_txn_abort_ex(MDBX_txn *txn, MDBX_commit_latency *latency)
     * }
     */
    public static MethodHandle mdbx_txn_abort_ex$handle() {
        return mdbx_txn_abort_ex.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_txn_abort_ex(MDBX_txn *txn, MDBX_commit_latency *latency)
     * }
     */
    public static MemorySegment mdbx_txn_abort_ex$address() {
        return mdbx_txn_abort_ex.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_txn_abort_ex(MDBX_txn *txn, MDBX_commit_latency *latency)
     * }
     */
    public static int mdbx_txn_abort_ex(MemorySegment txn, MemorySegment latency) {
        var mh$ = mdbx_txn_abort_ex.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_txn_abort_ex", txn, latency);
            }
            return (int)mh$.invokeExact(txn, latency);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_dbi_open {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_POINTER,
            Mdbx.C_INT,
            Mdbx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_dbi_open");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_dbi_open(MDBX_txn *txn, const char *name, MDBX_db_flags_t flags, MDBX_dbi *dbi)
     * }
     */
    public static FunctionDescriptor mdbx_dbi_open$descriptor() {
        return mdbx_dbi_open.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_dbi_open(MDBX_txn *txn, const char *name, MDBX_db_flags_t flags, MDBX_dbi *dbi)
     * }
     */
    public static MethodHandle mdbx_dbi_open$handle() {
        return mdbx_dbi_open.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_dbi_open(MDBX_txn *txn, const char *name, MDBX_db_flags_t flags, MDBX_dbi *dbi)
     * }
     */
    public static MemorySegment mdbx_dbi_open$address() {
        return mdbx_dbi_open.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_dbi_open(MDBX_txn *txn, const char *name, MDBX_db_flags_t flags, MDBX_dbi *dbi)
     * }
     */
    public static int mdbx_dbi_open(MemorySegment txn, MemorySegment name, int flags, MemorySegment dbi) {
        var mh$ = mdbx_dbi_open.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_dbi_open", txn, name, flags, dbi);
            }
            return (int)mh$.invokeExact(txn, name, flags, dbi);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_dbi_stat {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_dbi_stat");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_dbi_stat(const MDBX_txn *txn, MDBX_dbi dbi, MDBX_stat *stat, size_t bytes)
     * }
     */
    public static FunctionDescriptor mdbx_dbi_stat$descriptor() {
        return mdbx_dbi_stat.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_dbi_stat(const MDBX_txn *txn, MDBX_dbi dbi, MDBX_stat *stat, size_t bytes)
     * }
     */
    public static MethodHandle mdbx_dbi_stat$handle() {
        return mdbx_dbi_stat.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_dbi_stat(const MDBX_txn *txn, MDBX_dbi dbi, MDBX_stat *stat, size_t bytes)
     * }
     */
    public static MemorySegment mdbx_dbi_stat$address() {
        return mdbx_dbi_stat.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_dbi_stat(const MDBX_txn *txn, MDBX_dbi dbi, MDBX_stat *stat, size_t bytes)
     * }
     */
    public static int mdbx_dbi_stat(MemorySegment txn, int dbi, MemorySegment stat, long bytes) {
        var mh$ = mdbx_dbi_stat.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_dbi_stat", txn, dbi, stat, bytes);
            }
            return (int)mh$.invokeExact(txn, dbi, stat, bytes);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_get {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_get");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_get(const MDBX_txn *txn, MDBX_dbi dbi, const MDBX_val *key, MDBX_val *data)
     * }
     */
    public static FunctionDescriptor mdbx_get$descriptor() {
        return mdbx_get.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_get(const MDBX_txn *txn, MDBX_dbi dbi, const MDBX_val *key, MDBX_val *data)
     * }
     */
    public static MethodHandle mdbx_get$handle() {
        return mdbx_get.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_get(const MDBX_txn *txn, MDBX_dbi dbi, const MDBX_val *key, MDBX_val *data)
     * }
     */
    public static MemorySegment mdbx_get$address() {
        return mdbx_get.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_get(const MDBX_txn *txn, MDBX_dbi dbi, const MDBX_val *key, MDBX_val *data)
     * }
     */
    public static int mdbx_get(MemorySegment txn, int dbi, MemorySegment key, MemorySegment data) {
        var mh$ = mdbx_get.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_get", txn, dbi, key, data);
            }
            return (int)mh$.invokeExact(txn, dbi, key, data);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_put {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_POINTER,
            Mdbx.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_put");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_put(MDBX_txn *txn, MDBX_dbi dbi, const MDBX_val *key, MDBX_val *data, MDBX_put_flags_t flags)
     * }
     */
    public static FunctionDescriptor mdbx_put$descriptor() {
        return mdbx_put.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_put(MDBX_txn *txn, MDBX_dbi dbi, const MDBX_val *key, MDBX_val *data, MDBX_put_flags_t flags)
     * }
     */
    public static MethodHandle mdbx_put$handle() {
        return mdbx_put.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_put(MDBX_txn *txn, MDBX_dbi dbi, const MDBX_val *key, MDBX_val *data, MDBX_put_flags_t flags)
     * }
     */
    public static MemorySegment mdbx_put$address() {
        return mdbx_put.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_put(MDBX_txn *txn, MDBX_dbi dbi, const MDBX_val *key, MDBX_val *data, MDBX_put_flags_t flags)
     * }
     */
    public static int mdbx_put(MemorySegment txn, int dbi, MemorySegment key, MemorySegment data, int flags) {
        var mh$ = mdbx_put.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_put", txn, dbi, key, data, flags);
            }
            return (int)mh$.invokeExact(txn, dbi, key, data, flags);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_del {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_del");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_del(MDBX_txn *txn, MDBX_dbi dbi, const MDBX_val *key, const MDBX_val *data)
     * }
     */
    public static FunctionDescriptor mdbx_del$descriptor() {
        return mdbx_del.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_del(MDBX_txn *txn, MDBX_dbi dbi, const MDBX_val *key, const MDBX_val *data)
     * }
     */
    public static MethodHandle mdbx_del$handle() {
        return mdbx_del.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_del(MDBX_txn *txn, MDBX_dbi dbi, const MDBX_val *key, const MDBX_val *data)
     * }
     */
    public static MemorySegment mdbx_del$address() {
        return mdbx_del.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_del(MDBX_txn *txn, MDBX_dbi dbi, const MDBX_val *key, const MDBX_val *data)
     * }
     */
    public static int mdbx_del(MemorySegment txn, int dbi, MemorySegment key, MemorySegment data) {
        var mh$ = mdbx_del.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_del", txn, dbi, key, data);
            }
            return (int)mh$.invokeExact(txn, dbi, key, data);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_cursor_open {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_INT,
            Mdbx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_cursor_open");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_cursor_open(MDBX_txn *txn, MDBX_dbi dbi, MDBX_cursor **cursor)
     * }
     */
    public static FunctionDescriptor mdbx_cursor_open$descriptor() {
        return mdbx_cursor_open.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_cursor_open(MDBX_txn *txn, MDBX_dbi dbi, MDBX_cursor **cursor)
     * }
     */
    public static MethodHandle mdbx_cursor_open$handle() {
        return mdbx_cursor_open.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_cursor_open(MDBX_txn *txn, MDBX_dbi dbi, MDBX_cursor **cursor)
     * }
     */
    public static MemorySegment mdbx_cursor_open$address() {
        return mdbx_cursor_open.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_cursor_open(MDBX_txn *txn, MDBX_dbi dbi, MDBX_cursor **cursor)
     * }
     */
    public static int mdbx_cursor_open(MemorySegment txn, int dbi, MemorySegment cursor) {
        var mh$ = mdbx_cursor_open.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_cursor_open", txn, dbi, cursor);
            }
            return (int)mh$.invokeExact(txn, dbi, cursor);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_cursor_close2 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_cursor_close2");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_cursor_close2(MDBX_cursor *cursor)
     * }
     */
    public static FunctionDescriptor mdbx_cursor_close2$descriptor() {
        return mdbx_cursor_close2.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_cursor_close2(MDBX_cursor *cursor)
     * }
     */
    public static MethodHandle mdbx_cursor_close2$handle() {
        return mdbx_cursor_close2.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_cursor_close2(MDBX_cursor *cursor)
     * }
     */
    public static MemorySegment mdbx_cursor_close2$address() {
        return mdbx_cursor_close2.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_cursor_close2(MDBX_cursor *cursor)
     * }
     */
    public static int mdbx_cursor_close2(MemorySegment cursor) {
        var mh$ = mdbx_cursor_close2.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_cursor_close2", cursor);
            }
            return (int)mh$.invokeExact(cursor);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_cursor_get {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_POINTER,
            Mdbx.C_POINTER,
            Mdbx.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_cursor_get");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_cursor_get(MDBX_cursor *cursor, MDBX_val *key, MDBX_val *data, MDBX_cursor_op op)
     * }
     */
    public static FunctionDescriptor mdbx_cursor_get$descriptor() {
        return mdbx_cursor_get.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_cursor_get(MDBX_cursor *cursor, MDBX_val *key, MDBX_val *data, MDBX_cursor_op op)
     * }
     */
    public static MethodHandle mdbx_cursor_get$handle() {
        return mdbx_cursor_get.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_cursor_get(MDBX_cursor *cursor, MDBX_val *key, MDBX_val *data, MDBX_cursor_op op)
     * }
     */
    public static MemorySegment mdbx_cursor_get$address() {
        return mdbx_cursor_get.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_cursor_get(MDBX_cursor *cursor, MDBX_val *key, MDBX_val *data, MDBX_cursor_op op)
     * }
     */
    public static int mdbx_cursor_get(MemorySegment cursor, MemorySegment key, MemorySegment data, int op) {
        var mh$ = mdbx_cursor_get.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_cursor_get", cursor, key, data, op);
            }
            return (int)mh$.invokeExact(cursor, key, data, op);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_cursor_del {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_cursor_del");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_cursor_del(MDBX_cursor *cursor, MDBX_put_flags_t flags)
     * }
     */
    public static FunctionDescriptor mdbx_cursor_del$descriptor() {
        return mdbx_cursor_del.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_cursor_del(MDBX_cursor *cursor, MDBX_put_flags_t flags)
     * }
     */
    public static MethodHandle mdbx_cursor_del$handle() {
        return mdbx_cursor_del.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_cursor_del(MDBX_cursor *cursor, MDBX_put_flags_t flags)
     * }
     */
    public static MemorySegment mdbx_cursor_del$address() {
        return mdbx_cursor_del.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_cursor_del(MDBX_cursor *cursor, MDBX_put_flags_t flags)
     * }
     */
    public static int mdbx_cursor_del(MemorySegment cursor, int flags) {
        var mh$ = mdbx_cursor_del.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_cursor_del", cursor, flags);
            }
            return (int)mh$.invokeExact(cursor, flags);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class mdbx_env_openU {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mdbx.C_INT,
            Mdbx.C_POINTER,
            Mdbx.C_POINTER,
            Mdbx.C_INT,
            Mdbx.C_SHORT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("mdbx_env_openU");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int mdbx_env_openU(MDBX_env *env, const char *pathname, MDBX_env_flags_t flags, mdbx_mode_t mode)
     * }
     */
    public static FunctionDescriptor mdbx_env_openU$descriptor() {
        return mdbx_env_openU.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int mdbx_env_openU(MDBX_env *env, const char *pathname, MDBX_env_flags_t flags, mdbx_mode_t mode)
     * }
     */
    public static MethodHandle mdbx_env_openU$handle() {
        return mdbx_env_openU.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int mdbx_env_openU(MDBX_env *env, const char *pathname, MDBX_env_flags_t flags, mdbx_mode_t mode)
     * }
     */
    public static MemorySegment mdbx_env_openU$address() {
        return mdbx_env_openU.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int mdbx_env_openU(MDBX_env *env, const char *pathname, MDBX_env_flags_t flags, mdbx_mode_t mode)
     * }
     */
    public static int mdbx_env_openU(MemorySegment env, MemorySegment pathname, int flags, short mode) {
        var mh$ = mdbx_env_openU.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("mdbx_env_openU", env, pathname, flags, mode);
            }
            return (int)mh$.invokeExact(env, pathname, flags, mode);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

