package com.github.auties00.cobalt.call.transport.relay;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONObject;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;

/**
 * Loads parity-test fixtures from the test classpath.
 *
 * <p>Fixtures live under {@code src/test/resources/fixtures/} and are
 * generated by
 * {@code tools/web/js-scripts/generate-call-fixtures.mjs}. Loading
 * via the classpath avoids the brittle relative-path resolution that
 * Maven's {@code surefire} working directory imposes (which, for a
 * multi-module reactor build, can be the module directory or the
 * reactor root depending on how tests are invoked).
 */
final class Fixtures {
    /**
     * Hidden constructor.
     */
    private Fixtures() {
        throw new AssertionError("Fixtures is not instantiable");
    }

    /**
     * Loads the fixture at the given classpath-relative path and parses
     * it as JSON.
     *
     * @param resourcePath the path under {@code src/test/resources/}
     *                     (e.g. {@code "fixtures/relay/stun-bytes-raw.json"})
     * @return the parsed JSON document
     * @throws UncheckedIOException if the resource is missing or
     *                              cannot be read
     */
    static JSONObject readJson(String resourcePath) {
        return JSON.parseObject(readString(resourcePath));
    }

    /**
     * Loads the fixture at the given classpath-relative path and
     * returns it as a UTF-8 string.
     *
     * @param resourcePath the path under {@code src/test/resources/}
     * @return the file contents
     * @throws UncheckedIOException if the resource is missing or
     *                              cannot be read
     */
    static String readString(String resourcePath) {
        try (var in = open(resourcePath)) {
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("failed to read fixture: " + resourcePath, e);
        }
    }

    /**
     * Opens an input stream for the fixture at the given classpath
     * path.
     *
     * @param resourcePath the path under {@code src/test/resources/}
     * @return an input stream over the resource bytes
     * @throws IOException if the resource is missing
     */
    static InputStream open(String resourcePath) throws IOException {
        var stream = Fixtures.class.getResourceAsStream("/" + resourcePath);
        if (stream == null) {
            throw new IOException("fixture not found on classpath: " + resourcePath);
        }
        return stream;
    }
}
