// Generated by jextract

package com.github.auties00.cobalt.call.internal.video.h264.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ISVCDecoderVtbl {
 *     long (*Initialize)(ISVCDecoder *, const SDecodingParam *);
 *     long (*Uninitialize)(ISVCDecoder *);
 *     DECODING_STATE (*DecodeFrame)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, int *, int *, int *);
 *     DECODING_STATE (*DecodeFrameNoDelay)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, SBufferInfo *);
 *     DECODING_STATE (*DecodeFrame2)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, SBufferInfo *);
 *     DECODING_STATE (*FlushFrame)(ISVCDecoder *, unsigned char **, SBufferInfo *);
 *     DECODING_STATE (*DecodeParser)(ISVCDecoder *, const unsigned char *, const int, SParserBsInfo *);
 *     DECODING_STATE (*DecodeFrameEx)(ISVCDecoder *, const unsigned char *, const int, unsigned char *, int, int *, int *, int *, int *);
 *     long (*SetOption)(ISVCDecoder *, DECODER_OPTION, void *);
 *     long (*GetOption)(ISVCDecoder *, DECODER_OPTION, void *);
 * }
 * }
 */
public class ISVCDecoderVtbl {

    ISVCDecoderVtbl() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        OpenH264.C_POINTER.withName("Initialize"),
        OpenH264.C_POINTER.withName("Uninitialize"),
        OpenH264.C_POINTER.withName("DecodeFrame"),
        OpenH264.C_POINTER.withName("DecodeFrameNoDelay"),
        OpenH264.C_POINTER.withName("DecodeFrame2"),
        OpenH264.C_POINTER.withName("FlushFrame"),
        OpenH264.C_POINTER.withName("DecodeParser"),
        OpenH264.C_POINTER.withName("DecodeFrameEx"),
        OpenH264.C_POINTER.withName("SetOption"),
        OpenH264.C_POINTER.withName("GetOption")
    ).withName("ISVCDecoderVtbl");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * long (*Initialize)(ISVCDecoder *, const SDecodingParam *)
     * }
     */
    public final static class Initialize {

        private Initialize() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_LONG,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(Initialize.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Initialize.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Initialize$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Initialize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long (*Initialize)(ISVCDecoder *, const SDecodingParam *)
     * }
     */
    public static final AddressLayout Initialize$layout() {
        return Initialize$LAYOUT;
    }

    private static final long Initialize$OFFSET = $LAYOUT.byteOffset(groupElement("Initialize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long (*Initialize)(ISVCDecoder *, const SDecodingParam *)
     * }
     */
    public static final long Initialize$offset() {
        return Initialize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long (*Initialize)(ISVCDecoder *, const SDecodingParam *)
     * }
     */
    public static MemorySegment Initialize(MemorySegment struct) {
        return struct.get(Initialize$LAYOUT, Initialize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long (*Initialize)(ISVCDecoder *, const SDecodingParam *)
     * }
     */
    public static void Initialize(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Initialize$LAYOUT, Initialize$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * long (*Uninitialize)(ISVCDecoder *)
     * }
     */
    public final static class Uninitialize {

        private Uninitialize() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_LONG,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(Uninitialize.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Uninitialize.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Uninitialize$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Uninitialize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long (*Uninitialize)(ISVCDecoder *)
     * }
     */
    public static final AddressLayout Uninitialize$layout() {
        return Uninitialize$LAYOUT;
    }

    private static final long Uninitialize$OFFSET = $LAYOUT.byteOffset(groupElement("Uninitialize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long (*Uninitialize)(ISVCDecoder *)
     * }
     */
    public static final long Uninitialize$offset() {
        return Uninitialize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long (*Uninitialize)(ISVCDecoder *)
     * }
     */
    public static MemorySegment Uninitialize(MemorySegment struct) {
        return struct.get(Uninitialize$LAYOUT, Uninitialize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long (*Uninitialize)(ISVCDecoder *)
     * }
     */
    public static void Uninitialize(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Uninitialize$LAYOUT, Uninitialize$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrame)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, int *, int *, int *)
     * }
     */
    public final static class DecodeFrame {

        private DecodeFrame() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3, MemorySegment _x4, MemorySegment _x5, MemorySegment _x6);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER,
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(DecodeFrame.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(DecodeFrame.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3, MemorySegment _x4, MemorySegment _x5, MemorySegment _x6) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout DecodeFrame$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("DecodeFrame"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrame)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, int *, int *, int *)
     * }
     */
    public static final AddressLayout DecodeFrame$layout() {
        return DecodeFrame$LAYOUT;
    }

    private static final long DecodeFrame$OFFSET = $LAYOUT.byteOffset(groupElement("DecodeFrame"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrame)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, int *, int *, int *)
     * }
     */
    public static final long DecodeFrame$offset() {
        return DecodeFrame$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrame)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, int *, int *, int *)
     * }
     */
    public static MemorySegment DecodeFrame(MemorySegment struct) {
        return struct.get(DecodeFrame$LAYOUT, DecodeFrame$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrame)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, int *, int *, int *)
     * }
     */
    public static void DecodeFrame(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(DecodeFrame$LAYOUT, DecodeFrame$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrameNoDelay)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, SBufferInfo *)
     * }
     */
    public final static class DecodeFrameNoDelay {

        private DecodeFrameNoDelay() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3, MemorySegment _x4);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER,
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(DecodeFrameNoDelay.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(DecodeFrameNoDelay.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3, MemorySegment _x4) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout DecodeFrameNoDelay$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("DecodeFrameNoDelay"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrameNoDelay)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, SBufferInfo *)
     * }
     */
    public static final AddressLayout DecodeFrameNoDelay$layout() {
        return DecodeFrameNoDelay$LAYOUT;
    }

    private static final long DecodeFrameNoDelay$OFFSET = $LAYOUT.byteOffset(groupElement("DecodeFrameNoDelay"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrameNoDelay)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, SBufferInfo *)
     * }
     */
    public static final long DecodeFrameNoDelay$offset() {
        return DecodeFrameNoDelay$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrameNoDelay)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, SBufferInfo *)
     * }
     */
    public static MemorySegment DecodeFrameNoDelay(MemorySegment struct) {
        return struct.get(DecodeFrameNoDelay$LAYOUT, DecodeFrameNoDelay$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrameNoDelay)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, SBufferInfo *)
     * }
     */
    public static void DecodeFrameNoDelay(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(DecodeFrameNoDelay$LAYOUT, DecodeFrameNoDelay$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrame2)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, SBufferInfo *)
     * }
     */
    public final static class DecodeFrame2 {

        private DecodeFrame2() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3, MemorySegment _x4);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER,
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(DecodeFrame2.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(DecodeFrame2.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3, MemorySegment _x4) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout DecodeFrame2$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("DecodeFrame2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrame2)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, SBufferInfo *)
     * }
     */
    public static final AddressLayout DecodeFrame2$layout() {
        return DecodeFrame2$LAYOUT;
    }

    private static final long DecodeFrame2$OFFSET = $LAYOUT.byteOffset(groupElement("DecodeFrame2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrame2)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, SBufferInfo *)
     * }
     */
    public static final long DecodeFrame2$offset() {
        return DecodeFrame2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrame2)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, SBufferInfo *)
     * }
     */
    public static MemorySegment DecodeFrame2(MemorySegment struct) {
        return struct.get(DecodeFrame2$LAYOUT, DecodeFrame2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrame2)(ISVCDecoder *, const unsigned char *, const int, unsigned char **, SBufferInfo *)
     * }
     */
    public static void DecodeFrame2(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(DecodeFrame2$LAYOUT, DecodeFrame2$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * DECODING_STATE (*FlushFrame)(ISVCDecoder *, unsigned char **, SBufferInfo *)
     * }
     */
    public final static class FlushFrame {

        private FlushFrame() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(FlushFrame.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(FlushFrame.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout FlushFrame$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("FlushFrame"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DECODING_STATE (*FlushFrame)(ISVCDecoder *, unsigned char **, SBufferInfo *)
     * }
     */
    public static final AddressLayout FlushFrame$layout() {
        return FlushFrame$LAYOUT;
    }

    private static final long FlushFrame$OFFSET = $LAYOUT.byteOffset(groupElement("FlushFrame"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DECODING_STATE (*FlushFrame)(ISVCDecoder *, unsigned char **, SBufferInfo *)
     * }
     */
    public static final long FlushFrame$offset() {
        return FlushFrame$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DECODING_STATE (*FlushFrame)(ISVCDecoder *, unsigned char **, SBufferInfo *)
     * }
     */
    public static MemorySegment FlushFrame(MemorySegment struct) {
        return struct.get(FlushFrame$LAYOUT, FlushFrame$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DECODING_STATE (*FlushFrame)(ISVCDecoder *, unsigned char **, SBufferInfo *)
     * }
     */
    public static void FlushFrame(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(FlushFrame$LAYOUT, FlushFrame$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeParser)(ISVCDecoder *, const unsigned char *, const int, SParserBsInfo *)
     * }
     */
    public final static class DecodeParser {

        private DecodeParser() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER,
            OpenH264.C_INT,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(DecodeParser.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(DecodeParser.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout DecodeParser$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("DecodeParser"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeParser)(ISVCDecoder *, const unsigned char *, const int, SParserBsInfo *)
     * }
     */
    public static final AddressLayout DecodeParser$layout() {
        return DecodeParser$LAYOUT;
    }

    private static final long DecodeParser$OFFSET = $LAYOUT.byteOffset(groupElement("DecodeParser"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeParser)(ISVCDecoder *, const unsigned char *, const int, SParserBsInfo *)
     * }
     */
    public static final long DecodeParser$offset() {
        return DecodeParser$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeParser)(ISVCDecoder *, const unsigned char *, const int, SParserBsInfo *)
     * }
     */
    public static MemorySegment DecodeParser(MemorySegment struct) {
        return struct.get(DecodeParser$LAYOUT, DecodeParser$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeParser)(ISVCDecoder *, const unsigned char *, const int, SParserBsInfo *)
     * }
     */
    public static void DecodeParser(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(DecodeParser$LAYOUT, DecodeParser$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrameEx)(ISVCDecoder *, const unsigned char *, const int, unsigned char *, int, int *, int *, int *, int *)
     * }
     */
    public final static class DecodeFrameEx {

        private DecodeFrameEx() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3, int _x4, MemorySegment _x5, MemorySegment _x6, MemorySegment _x7, MemorySegment _x8);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER,
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_INT,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(DecodeFrameEx.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(DecodeFrameEx.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3, int _x4, MemorySegment _x5, MemorySegment _x6, MemorySegment _x7, MemorySegment _x8) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6, _x7, _x8);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout DecodeFrameEx$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("DecodeFrameEx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrameEx)(ISVCDecoder *, const unsigned char *, const int, unsigned char *, int, int *, int *, int *, int *)
     * }
     */
    public static final AddressLayout DecodeFrameEx$layout() {
        return DecodeFrameEx$LAYOUT;
    }

    private static final long DecodeFrameEx$OFFSET = $LAYOUT.byteOffset(groupElement("DecodeFrameEx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrameEx)(ISVCDecoder *, const unsigned char *, const int, unsigned char *, int, int *, int *, int *, int *)
     * }
     */
    public static final long DecodeFrameEx$offset() {
        return DecodeFrameEx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrameEx)(ISVCDecoder *, const unsigned char *, const int, unsigned char *, int, int *, int *, int *, int *)
     * }
     */
    public static MemorySegment DecodeFrameEx(MemorySegment struct) {
        return struct.get(DecodeFrameEx$LAYOUT, DecodeFrameEx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DECODING_STATE (*DecodeFrameEx)(ISVCDecoder *, const unsigned char *, const int, unsigned char *, int, int *, int *, int *, int *)
     * }
     */
    public static void DecodeFrameEx(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(DecodeFrameEx$LAYOUT, DecodeFrameEx$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * long (*SetOption)(ISVCDecoder *, DECODER_OPTION, void *)
     * }
     */
    public final static class SetOption {

        private SetOption() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_LONG,
            OpenH264.C_POINTER,
            OpenH264.C_INT,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(SetOption.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetOption.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetOption$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetOption"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long (*SetOption)(ISVCDecoder *, DECODER_OPTION, void *)
     * }
     */
    public static final AddressLayout SetOption$layout() {
        return SetOption$LAYOUT;
    }

    private static final long SetOption$OFFSET = $LAYOUT.byteOffset(groupElement("SetOption"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long (*SetOption)(ISVCDecoder *, DECODER_OPTION, void *)
     * }
     */
    public static final long SetOption$offset() {
        return SetOption$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long (*SetOption)(ISVCDecoder *, DECODER_OPTION, void *)
     * }
     */
    public static MemorySegment SetOption(MemorySegment struct) {
        return struct.get(SetOption$LAYOUT, SetOption$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long (*SetOption)(ISVCDecoder *, DECODER_OPTION, void *)
     * }
     */
    public static void SetOption(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetOption$LAYOUT, SetOption$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * long (*GetOption)(ISVCDecoder *, DECODER_OPTION, void *)
     * }
     */
    public final static class GetOption {

        private GetOption() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            OpenH264.C_LONG,
            OpenH264.C_POINTER,
            OpenH264.C_INT,
            OpenH264.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = OpenH264.upcallHandle(GetOption.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(GetOption.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout GetOption$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("GetOption"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long (*GetOption)(ISVCDecoder *, DECODER_OPTION, void *)
     * }
     */
    public static final AddressLayout GetOption$layout() {
        return GetOption$LAYOUT;
    }

    private static final long GetOption$OFFSET = $LAYOUT.byteOffset(groupElement("GetOption"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long (*GetOption)(ISVCDecoder *, DECODER_OPTION, void *)
     * }
     */
    public static final long GetOption$offset() {
        return GetOption$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long (*GetOption)(ISVCDecoder *, DECODER_OPTION, void *)
     * }
     */
    public static MemorySegment GetOption(MemorySegment struct) {
        return struct.get(GetOption$LAYOUT, GetOption$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long (*GetOption)(ISVCDecoder *, DECODER_OPTION, void *)
     * }
     */
    public static void GetOption(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(GetOption$LAYOUT, GetOption$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

