// Generated by jextract

package com.github.auties00.cobalt.call.internal.video.h264.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _tagVersion {
 *     unsigned int uMajor;
 *     unsigned int uMinor;
 *     unsigned int uRevision;
 *     unsigned int uReserved;
 * } OpenH264Version
 * }
 */
public class OpenH264Version extends _tagVersion {

    OpenH264Version() {
        // Should not be called directly
    }
}

