// Generated by jextract

package com.github.auties00.cobalt.call.internal.video.h264.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     unsigned char uiTemporalId;
 *     unsigned char uiSpatialId;
 *     unsigned char uiQualityId;
 *     EVideoFrameType eFrameType;
 *     unsigned char uiLayerType;
 *     int iSubSeqId;
 *     int iNalCount;
 *     int *pNalLengthInByte;
 *     unsigned char *pBsBuf;
 * }
 * }
 */
public class SLayerBSInfo {

    SLayerBSInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        OpenH264.C_CHAR.withName("uiTemporalId"),
        OpenH264.C_CHAR.withName("uiSpatialId"),
        OpenH264.C_CHAR.withName("uiQualityId"),
        MemoryLayout.paddingLayout(1),
        OpenH264.C_INT.withName("eFrameType"),
        OpenH264.C_CHAR.withName("uiLayerType"),
        MemoryLayout.paddingLayout(3),
        OpenH264.C_INT.withName("iSubSeqId"),
        OpenH264.C_INT.withName("iNalCount"),
        MemoryLayout.paddingLayout(4),
        OpenH264.C_POINTER.withName("pNalLengthInByte"),
        OpenH264.C_POINTER.withName("pBsBuf")
    ).withName("$anon$623:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte uiTemporalId$LAYOUT = (OfByte)$LAYOUT.select(groupElement("uiTemporalId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char uiTemporalId
     * }
     */
    public static final OfByte uiTemporalId$layout() {
        return uiTemporalId$LAYOUT;
    }

    private static final long uiTemporalId$OFFSET = $LAYOUT.byteOffset(groupElement("uiTemporalId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char uiTemporalId
     * }
     */
    public static final long uiTemporalId$offset() {
        return uiTemporalId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char uiTemporalId
     * }
     */
    public static byte uiTemporalId(MemorySegment struct) {
        return struct.get(uiTemporalId$LAYOUT, uiTemporalId$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char uiTemporalId
     * }
     */
    public static void uiTemporalId(MemorySegment struct, byte fieldValue) {
        struct.set(uiTemporalId$LAYOUT, uiTemporalId$OFFSET, fieldValue);
    }

    private static final OfByte uiSpatialId$LAYOUT = (OfByte)$LAYOUT.select(groupElement("uiSpatialId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char uiSpatialId
     * }
     */
    public static final OfByte uiSpatialId$layout() {
        return uiSpatialId$LAYOUT;
    }

    private static final long uiSpatialId$OFFSET = $LAYOUT.byteOffset(groupElement("uiSpatialId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char uiSpatialId
     * }
     */
    public static final long uiSpatialId$offset() {
        return uiSpatialId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char uiSpatialId
     * }
     */
    public static byte uiSpatialId(MemorySegment struct) {
        return struct.get(uiSpatialId$LAYOUT, uiSpatialId$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char uiSpatialId
     * }
     */
    public static void uiSpatialId(MemorySegment struct, byte fieldValue) {
        struct.set(uiSpatialId$LAYOUT, uiSpatialId$OFFSET, fieldValue);
    }

    private static final OfByte uiQualityId$LAYOUT = (OfByte)$LAYOUT.select(groupElement("uiQualityId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char uiQualityId
     * }
     */
    public static final OfByte uiQualityId$layout() {
        return uiQualityId$LAYOUT;
    }

    private static final long uiQualityId$OFFSET = $LAYOUT.byteOffset(groupElement("uiQualityId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char uiQualityId
     * }
     */
    public static final long uiQualityId$offset() {
        return uiQualityId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char uiQualityId
     * }
     */
    public static byte uiQualityId(MemorySegment struct) {
        return struct.get(uiQualityId$LAYOUT, uiQualityId$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char uiQualityId
     * }
     */
    public static void uiQualityId(MemorySegment struct, byte fieldValue) {
        struct.set(uiQualityId$LAYOUT, uiQualityId$OFFSET, fieldValue);
    }

    private static final OfInt eFrameType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("eFrameType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * EVideoFrameType eFrameType
     * }
     */
    public static final OfInt eFrameType$layout() {
        return eFrameType$LAYOUT;
    }

    private static final long eFrameType$OFFSET = $LAYOUT.byteOffset(groupElement("eFrameType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * EVideoFrameType eFrameType
     * }
     */
    public static final long eFrameType$offset() {
        return eFrameType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * EVideoFrameType eFrameType
     * }
     */
    public static int eFrameType(MemorySegment struct) {
        return struct.get(eFrameType$LAYOUT, eFrameType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * EVideoFrameType eFrameType
     * }
     */
    public static void eFrameType(MemorySegment struct, int fieldValue) {
        struct.set(eFrameType$LAYOUT, eFrameType$OFFSET, fieldValue);
    }

    private static final OfByte uiLayerType$LAYOUT = (OfByte)$LAYOUT.select(groupElement("uiLayerType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char uiLayerType
     * }
     */
    public static final OfByte uiLayerType$layout() {
        return uiLayerType$LAYOUT;
    }

    private static final long uiLayerType$OFFSET = $LAYOUT.byteOffset(groupElement("uiLayerType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char uiLayerType
     * }
     */
    public static final long uiLayerType$offset() {
        return uiLayerType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char uiLayerType
     * }
     */
    public static byte uiLayerType(MemorySegment struct) {
        return struct.get(uiLayerType$LAYOUT, uiLayerType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char uiLayerType
     * }
     */
    public static void uiLayerType(MemorySegment struct, byte fieldValue) {
        struct.set(uiLayerType$LAYOUT, uiLayerType$OFFSET, fieldValue);
    }

    private static final OfInt iSubSeqId$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iSubSeqId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int iSubSeqId
     * }
     */
    public static final OfInt iSubSeqId$layout() {
        return iSubSeqId$LAYOUT;
    }

    private static final long iSubSeqId$OFFSET = $LAYOUT.byteOffset(groupElement("iSubSeqId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int iSubSeqId
     * }
     */
    public static final long iSubSeqId$offset() {
        return iSubSeqId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int iSubSeqId
     * }
     */
    public static int iSubSeqId(MemorySegment struct) {
        return struct.get(iSubSeqId$LAYOUT, iSubSeqId$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int iSubSeqId
     * }
     */
    public static void iSubSeqId(MemorySegment struct, int fieldValue) {
        struct.set(iSubSeqId$LAYOUT, iSubSeqId$OFFSET, fieldValue);
    }

    private static final OfInt iNalCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iNalCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int iNalCount
     * }
     */
    public static final OfInt iNalCount$layout() {
        return iNalCount$LAYOUT;
    }

    private static final long iNalCount$OFFSET = $LAYOUT.byteOffset(groupElement("iNalCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int iNalCount
     * }
     */
    public static final long iNalCount$offset() {
        return iNalCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int iNalCount
     * }
     */
    public static int iNalCount(MemorySegment struct) {
        return struct.get(iNalCount$LAYOUT, iNalCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int iNalCount
     * }
     */
    public static void iNalCount(MemorySegment struct, int fieldValue) {
        struct.set(iNalCount$LAYOUT, iNalCount$OFFSET, fieldValue);
    }

    private static final AddressLayout pNalLengthInByte$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pNalLengthInByte"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *pNalLengthInByte
     * }
     */
    public static final AddressLayout pNalLengthInByte$layout() {
        return pNalLengthInByte$LAYOUT;
    }

    private static final long pNalLengthInByte$OFFSET = $LAYOUT.byteOffset(groupElement("pNalLengthInByte"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *pNalLengthInByte
     * }
     */
    public static final long pNalLengthInByte$offset() {
        return pNalLengthInByte$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *pNalLengthInByte
     * }
     */
    public static MemorySegment pNalLengthInByte(MemorySegment struct) {
        return struct.get(pNalLengthInByte$LAYOUT, pNalLengthInByte$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *pNalLengthInByte
     * }
     */
    public static void pNalLengthInByte(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pNalLengthInByte$LAYOUT, pNalLengthInByte$OFFSET, fieldValue);
    }

    private static final AddressLayout pBsBuf$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pBsBuf"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *pBsBuf
     * }
     */
    public static final AddressLayout pBsBuf$layout() {
        return pBsBuf$LAYOUT;
    }

    private static final long pBsBuf$OFFSET = $LAYOUT.byteOffset(groupElement("pBsBuf"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *pBsBuf
     * }
     */
    public static final long pBsBuf$offset() {
        return pBsBuf$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *pBsBuf
     * }
     */
    public static MemorySegment pBsBuf(MemorySegment struct) {
        return struct.get(pBsBuf$LAYOUT, pBsBuf$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *pBsBuf
     * }
     */
    public static void pBsBuf(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pBsBuf$LAYOUT, pBsBuf$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

