// Generated by jextract

package com.github.auties00.cobalt.call.internal.video.h264.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TagSVCDecodingParam {
 *     char *pFileNameRestructed;
 *     unsigned int uiCpuLoad;
 *     unsigned char uiTargetDqLayer;
 *     ERROR_CON_IDC eEcActiveIdc;
 *     bool bParseOnly;
 *     SVideoProperty sVideoProperty;
 * }
 * }
 */
public class TagSVCDecodingParam {

    TagSVCDecodingParam() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        OpenH264.C_POINTER.withName("pFileNameRestructed"),
        OpenH264.C_INT.withName("uiCpuLoad"),
        OpenH264.C_CHAR.withName("uiTargetDqLayer"),
        MemoryLayout.paddingLayout(3),
        OpenH264.C_INT.withName("eEcActiveIdc"),
        OpenH264.C_BOOL.withName("bParseOnly"),
        MemoryLayout.paddingLayout(3),
        SVideoProperty.layout().withName("sVideoProperty")
    ).withName("TagSVCDecodingParam");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout pFileNameRestructed$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pFileNameRestructed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *pFileNameRestructed
     * }
     */
    public static final AddressLayout pFileNameRestructed$layout() {
        return pFileNameRestructed$LAYOUT;
    }

    private static final long pFileNameRestructed$OFFSET = $LAYOUT.byteOffset(groupElement("pFileNameRestructed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *pFileNameRestructed
     * }
     */
    public static final long pFileNameRestructed$offset() {
        return pFileNameRestructed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *pFileNameRestructed
     * }
     */
    public static MemorySegment pFileNameRestructed(MemorySegment struct) {
        return struct.get(pFileNameRestructed$LAYOUT, pFileNameRestructed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *pFileNameRestructed
     * }
     */
    public static void pFileNameRestructed(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pFileNameRestructed$LAYOUT, pFileNameRestructed$OFFSET, fieldValue);
    }

    private static final OfInt uiCpuLoad$LAYOUT = (OfInt)$LAYOUT.select(groupElement("uiCpuLoad"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int uiCpuLoad
     * }
     */
    public static final OfInt uiCpuLoad$layout() {
        return uiCpuLoad$LAYOUT;
    }

    private static final long uiCpuLoad$OFFSET = $LAYOUT.byteOffset(groupElement("uiCpuLoad"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int uiCpuLoad
     * }
     */
    public static final long uiCpuLoad$offset() {
        return uiCpuLoad$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int uiCpuLoad
     * }
     */
    public static int uiCpuLoad(MemorySegment struct) {
        return struct.get(uiCpuLoad$LAYOUT, uiCpuLoad$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int uiCpuLoad
     * }
     */
    public static void uiCpuLoad(MemorySegment struct, int fieldValue) {
        struct.set(uiCpuLoad$LAYOUT, uiCpuLoad$OFFSET, fieldValue);
    }

    private static final OfByte uiTargetDqLayer$LAYOUT = (OfByte)$LAYOUT.select(groupElement("uiTargetDqLayer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char uiTargetDqLayer
     * }
     */
    public static final OfByte uiTargetDqLayer$layout() {
        return uiTargetDqLayer$LAYOUT;
    }

    private static final long uiTargetDqLayer$OFFSET = $LAYOUT.byteOffset(groupElement("uiTargetDqLayer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char uiTargetDqLayer
     * }
     */
    public static final long uiTargetDqLayer$offset() {
        return uiTargetDqLayer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char uiTargetDqLayer
     * }
     */
    public static byte uiTargetDqLayer(MemorySegment struct) {
        return struct.get(uiTargetDqLayer$LAYOUT, uiTargetDqLayer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char uiTargetDqLayer
     * }
     */
    public static void uiTargetDqLayer(MemorySegment struct, byte fieldValue) {
        struct.set(uiTargetDqLayer$LAYOUT, uiTargetDqLayer$OFFSET, fieldValue);
    }

    private static final OfInt eEcActiveIdc$LAYOUT = (OfInt)$LAYOUT.select(groupElement("eEcActiveIdc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ERROR_CON_IDC eEcActiveIdc
     * }
     */
    public static final OfInt eEcActiveIdc$layout() {
        return eEcActiveIdc$LAYOUT;
    }

    private static final long eEcActiveIdc$OFFSET = $LAYOUT.byteOffset(groupElement("eEcActiveIdc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ERROR_CON_IDC eEcActiveIdc
     * }
     */
    public static final long eEcActiveIdc$offset() {
        return eEcActiveIdc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ERROR_CON_IDC eEcActiveIdc
     * }
     */
    public static int eEcActiveIdc(MemorySegment struct) {
        return struct.get(eEcActiveIdc$LAYOUT, eEcActiveIdc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ERROR_CON_IDC eEcActiveIdc
     * }
     */
    public static void eEcActiveIdc(MemorySegment struct, int fieldValue) {
        struct.set(eEcActiveIdc$LAYOUT, eEcActiveIdc$OFFSET, fieldValue);
    }

    private static final OfBoolean bParseOnly$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("bParseOnly"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool bParseOnly
     * }
     */
    public static final OfBoolean bParseOnly$layout() {
        return bParseOnly$LAYOUT;
    }

    private static final long bParseOnly$OFFSET = $LAYOUT.byteOffset(groupElement("bParseOnly"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool bParseOnly
     * }
     */
    public static final long bParseOnly$offset() {
        return bParseOnly$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool bParseOnly
     * }
     */
    public static boolean bParseOnly(MemorySegment struct) {
        return struct.get(bParseOnly$LAYOUT, bParseOnly$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool bParseOnly
     * }
     */
    public static void bParseOnly(MemorySegment struct, boolean fieldValue) {
        struct.set(bParseOnly$LAYOUT, bParseOnly$OFFSET, fieldValue);
    }

    private static final GroupLayout sVideoProperty$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("sVideoProperty"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SVideoProperty sVideoProperty
     * }
     */
    public static final GroupLayout sVideoProperty$layout() {
        return sVideoProperty$LAYOUT;
    }

    private static final long sVideoProperty$OFFSET = $LAYOUT.byteOffset(groupElement("sVideoProperty"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SVideoProperty sVideoProperty
     * }
     */
    public static final long sVideoProperty$offset() {
        return sVideoProperty$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SVideoProperty sVideoProperty
     * }
     */
    public static MemorySegment sVideoProperty(MemorySegment struct) {
        return struct.asSlice(sVideoProperty$OFFSET, sVideoProperty$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SVideoProperty sVideoProperty
     * }
     */
    public static void sVideoProperty(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, sVideoProperty$OFFSET, sVideoProperty$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

