package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX mutation operation for the {@code CreateReportAppeal} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface CreateReportAppealMex extends MexJsonOperation permits CreateReportAppealMex.Request, CreateReportAppealMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "25877334095205200";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements CreateReportAppealMex {
        private final String reason;
        private final String reportId;

        public Request(String reason, String reportId) {
            this.reason = reason;
            this.reportId = reportId;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("reason");
                writer.writeColon();
                writer.writeString(reason);
                writer.writeName("report_id");
                writer.writeColon();
                writer.writeString(reportId);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements CreateReportAppealMex {
        private final String reportId;
        private final String status;
        private final String creationTime;
        private final String lastUpdateTime;
        private final String channelName;
        private final String channelJid;
        private final String serverMsgId;
        private final String responseServerMsgId;
        private final String notifyName;
        private final String appealState;
        private final String appealAppealReason;
        private final String appealCreationTime;
        private final String appealReportId;
        private final String appealAppealId;

        private Response(String reportId, String status, String creationTime, String lastUpdateTime, String channelName, String channelJid, String serverMsgId, String responseServerMsgId, String notifyName, String appealState, String appealAppealReason, String appealCreationTime, String appealReportId, String appealAppealId) {
            this.reportId = reportId;
            this.status = status;
            this.creationTime = creationTime;
            this.lastUpdateTime = lastUpdateTime;
            this.channelName = channelName;
            this.channelJid = channelJid;
            this.serverMsgId = serverMsgId;
            this.responseServerMsgId = responseServerMsgId;
            this.notifyName = notifyName;
            this.appealState = appealState;
            this.appealAppealReason = appealAppealReason;
            this.appealCreationTime = appealCreationTime;
            this.appealReportId = appealReportId;
            this.appealAppealId = appealAppealId;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code report_id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> reportId() {
            return Optional.ofNullable(reportId);
        }

        /**
         * Returns the {@code status} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> status() {
            return Optional.ofNullable(status);
        }

        /**
         * Returns the {@code creation_time} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> creationTime() {
            return Optional.ofNullable(creationTime);
        }

        /**
         * Returns the {@code last_update_time} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> lastUpdateTime() {
            return Optional.ofNullable(lastUpdateTime);
        }

        /**
         * Returns the {@code channel_name} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> channelName() {
            return Optional.ofNullable(channelName);
        }

        /**
         * Returns the {@code channel_jid} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> channelJid() {
            return Optional.ofNullable(channelJid);
        }

        /**
         * Returns the {@code server_msg_id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> serverMsgId() {
            return Optional.ofNullable(serverMsgId);
        }

        /**
         * Returns the {@code response_server_msg_id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> responseServerMsgId() {
            return Optional.ofNullable(responseServerMsgId);
        }

        /**
         * Returns the {@code notify_name} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> notifyName() {
            return Optional.ofNullable(notifyName);
        }

        /**
         * Returns the {@code appeal.state} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> appealState() {
            return Optional.ofNullable(appealState);
        }

        /**
         * Returns the {@code appeal.appeal_reason} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> appealAppealReason() {
            return Optional.ofNullable(appealAppealReason);
        }

        /**
         * Returns the {@code appeal.creation_time} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> appealCreationTime() {
            return Optional.ofNullable(appealCreationTime);
        }

        /**
         * Returns the {@code appeal.report_id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> appealReportId() {
            return Optional.ofNullable(appealReportId);
        }

        /**
         * Returns the {@code appeal.appeal_id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> appealAppealId() {
            return Optional.ofNullable(appealAppealId);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_create_channel_report_appeal_v2");
            if (root == null) {
                return Optional.empty();
            }

            var reportId = root.getString("report_id");
            var status = root.getString("status");
            var creationTime = root.getString("creation_time");
            var lastUpdateTime = root.getString("last_update_time");
            var channelName = root.getString("channel_name");
            var channelJid = root.getString("channel_jid");
            var serverMsgId = root.getString("server_msg_id");
            var responseServerMsgId = root.getString("response_server_msg_id");
            var notifyName = root.getString("notify_name");
            var appeal = root.getJSONObject("appeal");
            var appealState = appeal != null ? appeal.getString("state") : null;
            var appealAppealReason = appeal != null ? appeal.getString("appeal_reason") : null;
            var appealCreationTime = appeal != null ? appeal.getString("creation_time") : null;
            var appealReportId = appeal != null ? appeal.getString("report_id") : null;
            var appealAppealId = appeal != null ? appeal.getString("appeal_id") : null;

            return Optional.of(new Response(reportId, status, creationTime, lastUpdateTime, channelName, channelJid, serverMsgId, responseServerMsgId, notifyName, appealState, appealAppealReason, appealCreationTime, appealReportId, appealAppealId));
        }
    }
}
