package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX query operation for the {@code FetchPlaintextLinkPreview} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface FetchPlaintextLinkPreviewMex extends MexJsonOperation permits FetchPlaintextLinkPreviewMex.Request, FetchPlaintextLinkPreviewMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "9101130456653613";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchPlaintextLinkPreviewMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("input");
                writer.writeColon();
                writer.writeString(input);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchPlaintextLinkPreviewMex {
        private final String description;
        private final String directPath;
        private final String hash;
        private final String previewType;
        private final String thumbData;
        private final String title;
        private final String height;
        private final String width;

        private Response(String description, String directPath, String hash, String previewType, String thumbData, String title, String height, String width) {
            this.description = description;
            this.directPath = directPath;
            this.hash = hash;
            this.previewType = previewType;
            this.thumbData = thumbData;
            this.title = title;
            this.height = height;
            this.width = width;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code description} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> description() {
            return Optional.ofNullable(description);
        }

        /**
         * Returns the {@code direct_path} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> directPath() {
            return Optional.ofNullable(directPath);
        }

        /**
         * Returns the {@code hash} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> hash() {
            return Optional.ofNullable(hash);
        }

        /**
         * Returns the {@code preview_type} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> previewType() {
            return Optional.ofNullable(previewType);
        }

        /**
         * Returns the {@code thumb_data} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> thumbData() {
            return Optional.ofNullable(thumbData);
        }

        /**
         * Returns the {@code title} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> title() {
            return Optional.ofNullable(title);
        }

        /**
         * Returns the {@code height} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> height() {
            return Optional.ofNullable(height);
        }

        /**
         * Returns the {@code width} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> width() {
            return Optional.ofNullable(width);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_newsletter_link_preview");
            if (root == null) {
                return Optional.empty();
            }

            var description = root.getString("description");
            var directPath = root.getString("direct_path");
            var hash = root.getString("hash");
            var previewType = root.getString("preview_type");
            var thumbData = root.getString("thumb_data");
            var title = root.getString("title");
            var height = root.getString("height");
            var width = root.getString("width");

            return Optional.of(new Response(description, directPath, hash, previewType, thumbData, title, height, width));
        }
    }
}
