package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX query operation for the {@code FetchReachoutTimelock} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface FetchReachoutTimelockMex extends MexJsonOperation permits FetchReachoutTimelockMex.Request, FetchReachoutTimelockMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "23983697327930364";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchReachoutTimelockMex {

        public Request() {
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchReachoutTimelockMex {
        private final String isActive;
        private final String timeEnforcementEnds;
        private final String enforcementType;

        private Response(String isActive, String timeEnforcementEnds, String enforcementType) {
            this.isActive = isActive;
            this.timeEnforcementEnds = timeEnforcementEnds;
            this.enforcementType = enforcementType;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code is_active} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> isActive() {
            return Optional.ofNullable(isActive);
        }

        /**
         * Returns the {@code time_enforcement_ends} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> timeEnforcementEnds() {
            return Optional.ofNullable(timeEnforcementEnds);
        }

        /**
         * Returns the {@code enforcement_type} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> enforcementType() {
            return Optional.ofNullable(enforcementType);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_fetch_account_reachout_timelock");
            if (root == null) {
                return Optional.empty();
            }

            var isActive = root.getString("is_active");
            var timeEnforcementEnds = root.getString("time_enforcement_ends");
            var enforcementType = root.getString("enforcement_type");

            return Optional.of(new Response(isActive, timeEnforcementEnds, enforcementType));
        }
    }
}
