package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * A MEX query operation for the {@code FetchNewChatMessageCappingInfo} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface FetchNewChatMessageCappingInfoMex extends MexJsonOperation permits FetchNewChatMessageCappingInfoMex.Request, FetchNewChatMessageCappingInfoMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "24503548349331633";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchNewChatMessageCappingInfoMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link Node} ready to be sent
         */
        public Node toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("input");
                writer.writeColon();
                writer.writeString(input);
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchNewChatMessageCappingInfoMex {
        private final String totalQuota;
        private final String usedQuota;
        private final String cycleStartTimestamp;
        private final String cycleEndTimestamp;
        private final String serverSentTimestamp;
        private final String oteStatus;
        private final String mvStatus;
        private final String cappingStatus;

        private Response(String totalQuota, String usedQuota, String cycleStartTimestamp, String cycleEndTimestamp, String serverSentTimestamp, String oteStatus, String mvStatus, String cappingStatus) {
            this.totalQuota = totalQuota;
            this.usedQuota = usedQuota;
            this.cycleStartTimestamp = cycleStartTimestamp;
            this.cycleEndTimestamp = cycleEndTimestamp;
            this.serverSentTimestamp = serverSentTimestamp;
            this.oteStatus = oteStatus;
            this.mvStatus = mvStatus;
            this.cappingStatus = cappingStatus;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::parse);
        }

        /**
         * Returns the {@code total_quota} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> totalQuota() {
            return Optional.ofNullable(totalQuota);
        }

        /**
         * Returns the {@code used_quota} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> usedQuota() {
            return Optional.ofNullable(usedQuota);
        }

        /**
         * Returns the {@code cycle_start_timestamp} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> cycleStartTimestamp() {
            return Optional.ofNullable(cycleStartTimestamp);
        }

        /**
         * Returns the {@code cycle_end_timestamp} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> cycleEndTimestamp() {
            return Optional.ofNullable(cycleEndTimestamp);
        }

        /**
         * Returns the {@code server_sent_timestamp} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> serverSentTimestamp() {
            return Optional.ofNullable(serverSentTimestamp);
        }

        /**
         * Returns the {@code ote_status} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> oteStatus() {
            return Optional.ofNullable(oteStatus);
        }

        /**
         * Returns the {@code mv_status} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> mvStatus() {
            return Optional.ofNullable(mvStatus);
        }

        /**
         * Returns the {@code capping_status} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> cappingStatus() {
            return Optional.ofNullable(cappingStatus);
        }

        private static Optional<Response> parse(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_message_capping_info");
            if (root == null) {
                return Optional.empty();
            }

            var totalQuota = root.getString("total_quota");
            var usedQuota = root.getString("used_quota");
            var cycleStartTimestamp = root.getString("cycle_start_timestamp");
            var cycleEndTimestamp = root.getString("cycle_end_timestamp");
            var serverSentTimestamp = root.getString("server_sent_timestamp");
            var oteStatus = root.getString("ote_status");
            var mvStatus = root.getString("mv_status");
            var cappingStatus = root.getString("capping_status");

            return Optional.of(new Response(totalQuota, usedQuota, cycleStartTimestamp, cycleEndTimestamp, serverSentTimestamp, oteStatus, mvStatus, cappingStatus));
        }
    }
}
