package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * Creates an appeal against an enforcement decision previously taken by
 * WhatsApp on a report (for example a ban or content removal) and returns
 * the resulting appeal record.
 *
 * <p>This mutation is issued from the "appeal decision" flow surfaced to
 * newsletter admins and channel owners. The response carries the full
 * appeal state (report id, status, timestamps, channel metadata and the
 * associated server message ids) so the client can render the appeal
 * timeline immediately after submission.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL mutation. Manual edits will be
 * overwritten on the next generation run.
 *
 * @implNote WAWebMexCreateReportAppealJob.createReportAppeal: sends
 * {@code WAWebMexCreateReportAppealJobMutation} through
 * {@code WAWebMexClient.fetchQuery}.
 */
@WhatsAppWebModule(moduleName = "WAWebMexCreateReportAppealJob")
@WhatsAppWebModule(moduleName = "WAWebMexCreateReportAppealJobMutation.graphql")
public sealed interface CreateReportAppealMex extends MexJsonOperation permits CreateReportAppealMex.Request, CreateReportAppealMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexCreateReportAppealJobMutation} GraphQL operation.
     *
     * @implNote WAWebMexCreateReportAppealJobMutation.graphql: corresponds
     * to the {@code params.id} field of the compiled mutation.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexCreateReportAppealJobMutation.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "27283301737925761";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements CreateReportAppealMex {
        private final String reason;
        private final String reportId;

        public Request(String reason, String reportId) {
            this.reason = reason;
            this.reportId = reportId;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexCreateReportAppealJob.createReportAppeal: the
         * variables {@code reason} and {@code report_id} identify the
         * decision being contested and the free-form justification.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexCreateReportAppealJob", exports = "createReportAppeal",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (reason != null) {
                    writer.writeName("reason");
                    writer.writeColon();
                    writer.writeString(reason);
                }
                if (reportId != null) {
                    writer.writeName("report_id");
                    writer.writeColon();
                    writer.writeString(reportId);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements CreateReportAppealMex {
        private final String reportId;
        private final String status;
        private final Long creationTime;
        private final Long lastUpdateTime;
        private final String channelName;
        private final String channelJid;
        private final String serverMsgId;
        private final String responseServerMsgId;
        private final String notifyName;
        private final Appeal appeal;

        private Response(String reportId, String status, Long creationTime, Long lastUpdateTime, String channelName, String channelJid, String serverMsgId, String responseServerMsgId, String notifyName, Appeal appeal) {
            this.reportId = reportId;
            this.status = status;
            this.creationTime = creationTime;
            this.lastUpdateTime = lastUpdateTime;
            this.channelName = channelName;
            this.channelJid = channelJid;
            this.serverMsgId = serverMsgId;
            this.responseServerMsgId = responseServerMsgId;
            this.notifyName = notifyName;
            this.appeal = appeal;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexCreateReportAppealJob.createReportAppeal: reads
         * the {@code data.xwa2_create_channel_report_appeal_v2} payload
         * (an {@code XWA2ChannelsReport}) including the appeal record and
         * nested {@code reported_content_data} channel metadata.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexCreateReportAppealJob", exports = "createReportAppeal",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code report_id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> reportId() {
            return Optional.ofNullable(reportId);
        }

        /**
         * Returns the {@code status} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> status() {
            return Optional.ofNullable(status);
        }

        /**
         * Returns the {@code creation_time} field.
         *
         * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
         */
        public Optional<Instant> creationTime() {
            return Optional.ofNullable(creationTime).map(Instant::ofEpochSecond);
        }

        /**
         * Returns the {@code last_update_time} field.
         *
         * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
         */
        public Optional<Instant> lastUpdateTime() {
            return Optional.ofNullable(lastUpdateTime).map(Instant::ofEpochSecond);
        }

        /**
         * Returns the {@code channel_name} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> channelName() {
            return Optional.ofNullable(channelName);
        }

        /**
         * Returns the {@code channel_jid} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> channelJid() {
            return Optional.ofNullable(channelJid);
        }

        /**
         * Returns the {@code server_msg_id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> serverMsgId() {
            return Optional.ofNullable(serverMsgId);
        }

        /**
         * Returns the {@code response_server_msg_id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> responseServerMsgId() {
            return Optional.ofNullable(responseServerMsgId);
        }

        /**
         * Returns the {@code notify_name} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> notifyName() {
            return Optional.ofNullable(notifyName);
        }

        /**
         * Returns the {@code appeal} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<Appeal> appeal() {
            return Optional.ofNullable(appeal);
        }

        /**
         * A parsed {@code Appeal} object.
         */
        public static final class Appeal {
            private final String state;
            private final String appealReason;
            private final Long creationTime;
            private final String reportId;
            private final String appealId;

            private Appeal(String state, String appealReason, Long creationTime, String reportId, String appealId) {
                this.state = state;
                this.appealReason = appealReason;
                this.creationTime = creationTime;
                this.reportId = reportId;
                this.appealId = appealId;
            }

            /**
             * Returns the {@code state} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> state() {
                return Optional.ofNullable(state);
            }

            /**
             * Returns the {@code appeal_reason} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> appealReason() {
                return Optional.ofNullable(appealReason);
            }

            /**
             * Returns the {@code creation_time} field.
             *
             * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
             */
            public Optional<Instant> creationTime() {
                return Optional.ofNullable(creationTime).map(Instant::ofEpochSecond);
            }

            /**
             * Returns the {@code report_id} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> reportId() {
                return Optional.ofNullable(reportId);
            }

            /**
             * Returns the {@code appeal_id} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> appealId() {
                return Optional.ofNullable(appealId);
            }

            /**
             * Parses a {@code Appeal} from the given JSON object.
             *
             * @param obj the JSON object to parse
             * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
             */
            static Optional<Appeal> of(JSONObject obj) {
                if (obj == null) {
                    return Optional.empty();
                }

                var state = obj.getString("state");
                var appealReason = obj.getString("appeal_reason");
                var creationTime = obj.getLong("creation_time");
                var reportId = obj.getString("report_id");
                var appealId = obj.getString("appeal_id");
                return Optional.of(new Appeal(state, appealReason, creationTime, reportId, appealId));
            }

            /**
             * Parses a list of {@code Appeal} from the given JSON array.
             *
             * @param arr the JSON array to parse
             * @return the list of parsed results, empty if {@code arr} is {@code null}
             */
            static List<Appeal> ofArray(JSONArray arr) {
                if (arr == null) {
                    return List.of();
                }

                var result = new ArrayList<Appeal>(arr.size());
                for (var i = 0; i < arr.size(); i++) {
                    of(arr.getJSONObject(i)).ifPresent(result::add);
                }
                return result;
            }
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_create_channel_report_appeal_v2");
            if (root == null) {
                return Optional.empty();
            }

            var reportId = root.getString("report_id");
            var status = root.getString("status");
            var creationTime = root.getLong("creation_time");
            var lastUpdateTime = root.getLong("last_update_time");
            var channelName = root.getString("channel_name");
            var channelJid = root.getString("channel_jid");
            // WAWebMexCreateReportAppealJobMutation.graphql: server_msg_id, server_response_id and
            // notify_name are nested under reported_content_data (XWA2ChannelServerMsgData /
            // XWA2ChannelQuestionResponseData inline fragments).
            var reportedContentData = root.getJSONObject("reported_content_data");
            var serverMsgId = reportedContentData == null ? null : reportedContentData.getString("server_msg_id");
            var responseServerMsgId = reportedContentData == null ? null : reportedContentData.getString("server_response_id");
            var notifyName = reportedContentData == null ? null : reportedContentData.getString("notify_name");
            var appeal = Appeal.of(root.getJSONObject("appeal")).orElse(null);

            return Optional.of(new Response(reportId, status, creationTime, lastUpdateTime, channelName, channelJid, serverMsgId, responseServerMsgId, notifyName, appeal));
        }
    }
}
