package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * Fetches the current outbound messaging quota enforced on the account by
 * the new-chat messaging capping policy.
 *
 * <p>WhatsApp enforces a sliding-window quota on how many new chats a user
 * can initiate per billing cycle. This query returns the total quota, used
 * quota, cycle start/end timestamps and a series of status flags
 * ({@code oteStatus}, {@code mvStatus}, {@code cappingStatus}) that drive
 * the throttling UI and per-message warnings.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL query. Manual edits will be overwritten
 * on the next generation run.
 *
 * @implNote WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql: the
 * compiled GraphQL operation is dispatched through
 * {@code WAWebMexClient.fetchQuery} and returns the
 * {@code xwa2_fetch_new_chat_message_capping_info} payload.
 */
@WhatsAppWebModule(moduleName = "WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql")
public sealed interface FetchNewChatMessageCappingInfoMex extends MexJsonOperation permits FetchNewChatMessageCappingInfoMex.Request, FetchNewChatMessageCappingInfoMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexFetchNewChatMessageCappingInfoJobQuery} GraphQL operation.
     *
     * @implNote WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql:
     * corresponds to the {@code params.id} field of the compiled query.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "24503548349331633";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchNewChatMessageCappingInfoMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql:
         * the single {@code input} variable carries the serialised request
         * options.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql", exports = "params.id",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (input != null) {
                    writer.writeName("input");
                    writer.writeColon();
                    writer.writeString(input);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchNewChatMessageCappingInfoMex {
        private final String totalQuota;
        private final String usedQuota;
        private final String cycleStartTimestamp;
        private final String cycleEndTimestamp;
        private final String serverSentTimestamp;
        private final String oteStatus;
        private final String mvStatus;
        private final String cappingStatus;

        private Response(String totalQuota, String usedQuota, String cycleStartTimestamp, String cycleEndTimestamp, String serverSentTimestamp, String oteStatus, String mvStatus, String cappingStatus) {
            this.totalQuota = totalQuota;
            this.usedQuota = usedQuota;
            this.cycleStartTimestamp = cycleStartTimestamp;
            this.cycleEndTimestamp = cycleEndTimestamp;
            this.serverSentTimestamp = serverSentTimestamp;
            this.oteStatus = oteStatus;
            this.mvStatus = mvStatus;
            this.cappingStatus = cappingStatus;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql:
         * reads the quota counters and per-policy status flags from the
         * response payload.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql", exports = "params.id",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code total_quota} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> totalQuota() {
            return Optional.ofNullable(totalQuota);
        }

        /**
         * Returns the {@code used_quota} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> usedQuota() {
            return Optional.ofNullable(usedQuota);
        }

        /**
         * Returns the {@code cycle_start_timestamp} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> cycleStartTimestamp() {
            return Optional.ofNullable(cycleStartTimestamp);
        }

        /**
         * Returns the {@code cycle_end_timestamp} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> cycleEndTimestamp() {
            return Optional.ofNullable(cycleEndTimestamp);
        }

        /**
         * Returns the {@code server_sent_timestamp} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> serverSentTimestamp() {
            return Optional.ofNullable(serverSentTimestamp);
        }

        /**
         * Returns the {@code ote_status} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> oteStatus() {
            return Optional.ofNullable(oteStatus);
        }

        /**
         * Returns the {@code mv_status} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> mvStatus() {
            return Optional.ofNullable(mvStatus);
        }

        /**
         * Returns the {@code capping_status} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> cappingStatus() {
            return Optional.ofNullable(cappingStatus);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_message_capping_info");
            if (root == null) {
                return Optional.empty();
            }

            var totalQuota = root.getString("total_quota");
            var usedQuota = root.getString("used_quota");
            var cycleStartTimestamp = root.getString("cycle_start_timestamp");
            var cycleEndTimestamp = root.getString("cycle_end_timestamp");
            var serverSentTimestamp = root.getString("server_sent_timestamp");
            var oteStatus = root.getString("ote_status");
            var mvStatus = root.getString("mv_status");
            var cappingStatus = root.getString("capping_status");

            return Optional.of(new Response(totalQuota, usedQuota, cycleStartTimestamp, cycleEndTimestamp, serverSentTimestamp, oteStatus, mvStatus, cappingStatus));
        }
    }
}
