package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * Requests a Data Subject (Download/Deletion) Request Button reference
 * number, used by the privacy "request my info" and "delete my account"
 * flows required under data protection regulations.
 *
 * <p>Despite being a "get" operation this is modelled as a GraphQL
 * mutation on the server because submitting the request has side effects
 * (it kicks off a data export or deletion job). The response carries the
 * generated reference number so the user can check progress.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL mutation. Manual edits will be
 * overwritten on the next generation run.
 *
 * @implNote WAWebMexGetDsbInfoJob.mexGetDsbInfo: dispatches the compiled
 * {@code WAWebMexGetDsbInfoJobMutation} document through
 * {@code WAWebMexClient.fetchQuery}; {@code WAWebGetDsbInfoJob.getDsbInfo}
 * wraps that call in a non-persisted UI-action job.
 */
@WhatsAppWebModule(moduleName = "WAWebMexGetDsbInfoJob")
@WhatsAppWebModule(moduleName = "WAWebGetDsbInfoJob")
@WhatsAppWebModule(moduleName = "WAWebMexGetDsbInfoJobMutation.graphql")
public sealed interface GetDsbInfoMex extends MexJsonOperation permits GetDsbInfoMex.Request, GetDsbInfoMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexGetDsbInfoJobMutation} GraphQL operation.
     *
     * @implNote WAWebMexGetDsbInfoJobMutation.graphql: corresponds to the
     * {@code params.id} field of the compiled mutation.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexGetDsbInfoJobMutation.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "9982897848413251";

    /**
     * The request payload for this MEX mutation.
     *
     * @implNote WAWebMexGetDsbInfoJob.mexGetDsbInfo: wraps the supplied
     * entity identifier as {@code {input: {entity_id: e}}} before passing
     * the GraphQL variables to {@code WAWebMexClient.fetchQuery}.
     */
    final class Request implements GetDsbInfoMex {
        private final String entityId;

        /**
         * Constructs a new request for the supplied entity identifier.
         *
         * @implNote WAWebMexGetDsbInfoJob.mexGetDsbInfo: the single positional
         * argument {@code e} is the entity identifier embedded under
         * {@code variables.input.entity_id}.
         * @param entityId the entity identifier whose data subject request
         *                 should be initiated
         */
        @WhatsAppWebExport(moduleName = "WAWebMexGetDsbInfoJob", exports = "mexGetDsbInfo",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public Request(String entityId) {
            this.entityId = entityId;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexGetDsbInfoJob.mexGetDsbInfo: builds the
         * {@code {input: {entity_id: e}}} variables envelope and forwards
         * it to {@code WAWebMexClient.fetchQuery} together with the
         * compiled mutation document.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexGetDsbInfoJob", exports = "mexGetDsbInfo",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.writeName("input");
                writer.writeColon();
                writer.startObject();
                if (entityId != null) {
                    writer.writeName("entity_id");
                    writer.writeColon();
                    writer.writeString(entityId);
                }
                writer.endObject();
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements GetDsbInfoMex {
        private final String referenceNumber;

        private Response(String referenceNumber) {
            this.referenceNumber = referenceNumber;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexGetDsbInfoJob.mexGetDsbInfo: reads
         * {@code xwa2_get_dsb_info.reference_number} from the GraphQL
         * payload returned by {@code WAWebMexClient.fetchQuery}.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexGetDsbInfoJob", exports = "mexGetDsbInfo",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code reference_number} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> referenceNumber() {
            return Optional.ofNullable(referenceNumber);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_get_dsb_info");
            if (root == null) {
                return Optional.empty();
            }

            var referenceNumber = root.getString("reference_number");

            return Optional.of(new Response(referenceNumber));
        }
    }
}
