package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.MexOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * Inbound parsed response of the {@link GetDsbInfoMexRequest} mutation,
 * exposing the relay-generated reference number carried by the
 * {@code xwa2_get_dsb_info} envelope.
 *
 * @apiNote The reference number is the user-visible token surfaced in
 * WA Web's data-subject-request confirmation UI; callers display it to
 * the user so they can quote it when checking on the request's
 * processing state.
 *
 * @implNote This implementation surfaces the lone {@code reference_number}
 * scalar as an {@link Optional} so absence stays observable; WA Web's
 * wrapper reads {@code n.xwa2_get_dsb_info.reference_number} directly and
 * throws when the envelope is {@code null}.
 */
@WhatsAppWebModule(moduleName = "WAWebMexGetDsbInfoJob")
public final class GetDsbInfoMexResponse implements MexOperation.Response.Json {
    /**
     * The {@code reference_number} scalar generated by the relay so the
     * user can track the data-subject request.
     */
    private final String referenceNumber;

    /**
     * Constructs a new response wrapping the {@code reference_number}
     * scalar.
     *
     * @apiNote Private; instances are produced by the {@link #of(Node)}
     * parser.
     *
     * @param referenceNumber the relay-generated reference number, may be {@code null}
     */
    private GetDsbInfoMexResponse(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }

    /**
     * Parses the MEX response carried by an inbound IQ stanza.
     *
     * @apiNote Reads the {@code <result>} child's byte content and routes
     * it through the private byte-level parser. Returns
     * {@link Optional#empty()} when the stanza carries no result or when
     * the {@code data.xwa2_get_dsb_info} envelope is absent; WA Web's
     * wrapper raises a {@code ServerStatusCodeError(500)} in the same
     * situation.
     *
     * @param node the inbound IQ stanza carrying the {@code <result>} child
     * @return an {@link Optional} wrapping the parsed response, or
     *         {@link Optional#empty()} if the expected JSON shape is absent
     */
    @WhatsAppWebExport(moduleName = "WAWebMexGetDsbInfoJob", exports = "mexGetDsbInfo",
            adaptation = WhatsAppAdaptation.ADAPTED)
    public static Optional<GetDsbInfoMexResponse> of(Node node) {
        return node.getChild("result")
                .flatMap(Node::toContentBytes)
                .flatMap(GetDsbInfoMexResponse::of);
    }

    /**
     * Returns the relay-generated reference number.
     *
     * @return an {@link Optional} containing the reference number, or
     *         {@link Optional#empty()} if the relay omitted the scalar
     */
    public Optional<String> referenceNumber() {
        return Optional.ofNullable(referenceNumber);
    }

    /**
     * Parses the JSON payload carried by the {@code <result>} child into a
     * {@link GetDsbInfoMexResponse}.
     *
     * @apiNote Private; routed through {@link #of(Node)} after the byte
     * content of the {@code <result>} child is extracted. Returns
     * {@link Optional#empty()} when the envelope, the {@code data} branch,
     * or the {@code xwa2_get_dsb_info} child is absent.
     *
     * @param json the UTF-8 encoded JSON payload
     * @return an {@link Optional} wrapping the parsed response, or
     *         {@link Optional#empty()} if the {@code data.xwa2_get_dsb_info}
     *         envelope is absent
     */
    private static Optional<GetDsbInfoMexResponse> of(byte[] json) {
        var jsonObject = JSON.parseObject(json);
        if (jsonObject == null) {
            return Optional.empty();
        }

        var data = jsonObject.getJSONObject("data");
        if (data == null) {
            return Optional.empty();
        }

        var root = data.getJSONObject("xwa2_get_dsb_info");
        if (root == null) {
            return Optional.empty();
        }

        var referenceNumber = root.getString("reference_number");

        return Optional.of(new GetDsbInfoMexResponse(referenceNumber));
    }
}
